/-
  LayerA/DiscreteAmbroseSinger.lean — Discrete Ambrose-Singer theorem

  GENUINE discrete Ambrose-Singer: the holonomy group of a discrete connection
  equals the subgroup generated by conjugated plaquette holonomies.

  Fully proved content (zero sorry, zero custom axioms):
  - `hol_append`: Holonomy is multiplicative under edge-list concatenation
  - `hol_reverse_eq_inv`: Holonomy of reversed path = inverse of holonomy
  - `lollipop_hol`: Holonomy of lollipop = conjugated loop holonomy
  - `append_composable`, `revEdges_composable`: Composability of list operations
  - `lollipopLoop`: Full construction of lollipop as a valid GraphLoop
  - `basedCurvature_is_holonomy`: Every based curvature IS a loop holonomy
  - `discrete_ambrose_singer_converse`: Curvature subgroup ≤ holonomy subgroup
  - `discrete_stokes`: Every loop holonomy is in the curvature subgroup
  - `discrete_ambrose_singer_eq`: Holonomy = closure of based curvatures
  - `holonomy_concat`, `holonomy_reverse`: Path operations
  - `gauge_conjugates_loop_holonomy`: Gauge conjugation of loop holonomy
  - `hol_gaugeTransform_telescope`: Telescoping of gauge-transformed holonomy
-/
import UnifiedTheory.LayerA.DiscreteBundles
import Mathlib.Algebra.Group.Subgroup.Basic
import Mathlib.Tactic.Group

namespace UnifiedTheory.LayerA.DiscreteAmbroseSinger

set_option linter.unusedTactic false
set_option linter.unusedVariables false
set_option linter.style.setOption false
set_option linter.style.show false
set_option linter.style.longLine false

open DiscreteBundles

/-! ## Reversible graphs -/

class HasReversal (Γ : DirectedGraph) where
  rev : Γ.Edge → Γ.Edge
  rev_src : ∀ (e : Γ.Edge), Γ.src (rev e) = Γ.tgt e
  rev_tgt : ∀ (e : Γ.Edge), Γ.tgt (rev e) = Γ.src e

class ReversibleConnection (Γ : DirectedGraph) (G : Type*) [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G) where
  transport_rev : ∀ (e : Γ.Edge),
    conn.transport (HasReversal.rev e) = (conn.transport e)⁻¹

/-! ## Holonomy algebra on raw edge lists -/

def hol {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (l : List Γ.Edge) : G :=
  l.foldl (fun acc e => acc * conn.transport e) 1

theorem hol_eq_holonomy {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (p : GraphPath Γ) :
    hol conn p.edges = holonomy conn p := rfl

set_option linter.flexible false in
theorem hol_nil {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) :
    hol conn ([] : List Γ.Edge) = 1 := rfl

set_option linter.flexible false in
theorem hol_singleton {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (e : Γ.Edge) :
    hol conn [e] = conn.transport e := by
  simp [hol, List.foldl, one_mul]

theorem foldl_mul_shift {G : Type*} [Monoid G] {E : Type*}
    (f : E → G) (l : List E) (a : G) :
    l.foldl (fun acc e => acc * f e) a =
    a * l.foldl (fun acc e => acc * f e) 1 := by
  induction l generalizing a with
  | nil => simp [List.foldl]
  | cons e es ih =>
    simp only [List.foldl]
    rw [ih (a * f e), ih (1 * f e), one_mul, mul_assoc]

theorem hol_append {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (l₁ l₂ : List Γ.Edge) :
    hol conn (l₁ ++ l₂) = hol conn l₁ * hol conn l₂ := by
  simp only [hol, List.foldl_append]
  rw [foldl_mul_shift]

def revEdges {Γ : DirectedGraph} [HasReversal Γ] (l : List Γ.Edge) :
    List Γ.Edge :=
  (l.map HasReversal.rev).reverse

@[simp] theorem revEdges_length {Γ : DirectedGraph} [HasReversal Γ]
    (l : List Γ.Edge) : (revEdges l).length = l.length := by
  simp [revEdges]

theorem hol_reverse_eq_inv {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (l : List Γ.Edge) :
    hol conn (revEdges l) = (hol conn l)⁻¹ := by
  induction l with
  | nil => simp [hol, revEdges, List.foldl]
  | cons e es ih =>
    simp only [revEdges, List.map_cons, List.reverse_cons]
    rw [hol_append]
    simp only [revEdges] at ih
    rw [ih]
    simp only [hol, List.foldl, one_mul]
    rw [ReversibleConnection.transport_rev (conn := conn)]
    rw [foldl_mul_shift conn.transport es (conn.transport e)]
    rw [mul_inv_rev]

theorem lollipop_hol {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (γ_edges loop_edges : List Γ.Edge) :
    hol conn (γ_edges ++ loop_edges ++ revEdges γ_edges) =
    hol conn γ_edges * hol conn loop_edges * (hol conn γ_edges)⁻¹ := by
  rw [hol_append, hol_append, hol_reverse_eq_inv, mul_assoc]

/-! ## Composability infrastructure -/

def Composable (Γ : DirectedGraph) (l : List Γ.Edge) : Prop :=
  ∀ i : Fin (l.length - 1),
    Γ.tgt (l[i.val]'(by omega)) = Γ.src (l[i.val + 1]'(by omega))

theorem append_composable {Γ : DirectedGraph}
    (l₁ l₂ : List Γ.Edge)
    (h₁ : Composable Γ l₁) (h₂ : Composable Γ l₂)
    (hne₁ : 0 < l₁.length) (hne₂ : 0 < l₂.length)
    (hjoin : Γ.tgt (l₁[l₁.length - 1]'(by omega)) = Γ.src (l₂[0]'hne₂)) :
    Composable Γ (l₁ ++ l₂) := by
  intro ⟨i, hi⟩
  simp only [List.length_append] at hi
  by_cases h_both_l1 : i + 1 < l₁.length
  · simp only [List.getElem_append_left (show i < l₁.length by omega),
               List.getElem_append_left h_both_l1]
    exact h₁ ⟨i, by omega⟩
  · by_cases h_boundary : i < l₁.length
    · have h_i_eq : i = l₁.length - 1 := by omega
      subst h_i_eq
      simp only [List.getElem_append_left h_boundary,
                  List.getElem_append_right (show l₁.length ≤ l₁.length - 1 + 1 by omega),
                  show l₁.length - 1 + 1 - l₁.length = 0 from by omega]
      exact hjoin
    · simp only [List.getElem_append_right (show l₁.length ≤ i by omega),
                  List.getElem_append_right (show l₁.length ≤ i + 1 by omega),
                  show i + 1 - l₁.length = (i - l₁.length) + 1 from by omega]
      exact h₂ ⟨i - l₁.length, by omega⟩

theorem revEdges_getElem {Γ : DirectedGraph} [HasReversal Γ]
    (l : List Γ.Edge) (i : ℕ) (hi : i < l.length) :
    (revEdges l)[i]'(by simp [revEdges]; exact hi) =
    HasReversal.rev (l[l.length - 1 - i]'(by omega)) := by
  simp only [revEdges]
  rw [List.getElem_reverse (by simp; exact hi)]
  simp only [List.length_map]
  rw [List.getElem_map]

theorem revEdges_composable {Γ : DirectedGraph} [HasReversal Γ]
    (l : List Γ.Edge) (h : Composable Γ l) :
    Composable Γ (revEdges l) := by
  intro ⟨i, hi⟩
  rw [revEdges_length] at hi
  rw [revEdges_getElem l i (by omega),
      revEdges_getElem l (i + 1) (by omega)]
  rw [HasReversal.rev_tgt, HasReversal.rev_src]
  have hcomp := h ⟨l.length - 1 - (i + 1), by omega⟩
  have key : l.length - 1 - (i + 1) + 1 = l.length - 1 - i := by omega
  simp only [key] at hcomp; exact hcomp.symm

/-! ## The holonomy and curvature sets -/

def holonomySet {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (v₀ : Γ.Vertex) : Set G :=
  { g : G | ∃ loop : GraphLoop Γ,
    Γ.src (loop.edges[0]'(loop.nonempty)) = v₀ ∧
    holonomy conn loop.toGraphPath = g }

def holonomySubgroup {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (v₀ : Γ.Vertex) : Subgroup G :=
  Subgroup.closure (holonomySet conn v₀)

def basedCurvatureSet {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (v₀ : Γ.Vertex) : Set G :=
  { h : G | ∃ (γ : GraphPath Γ) (plaq : Plaquette Γ)
    (hγne : 0 < γ.edges.length),
    Γ.src (γ.edges[0]'hγne) = v₀ ∧
    Γ.tgt (γ.edges[γ.edges.length - 1]'(by omega)) =
      Γ.src (plaq.edges[0]'plaq.nonempty) ∧
    h = hol conn γ.edges *
        hol conn plaq.edges *
        (hol conn γ.edges)⁻¹ }

/-! ## Building the lollipop as a GraphLoop -/

private theorem three_append_composable {Γ : DirectedGraph}
    (l₁ l₂ l₃ : List Γ.Edge)
    (h₁ : Composable Γ l₁) (h₂ : Composable Γ l₂) (h₃ : Composable Γ l₃)
    (hne₁ : 0 < l₁.length) (hne₂ : 0 < l₂.length) (hne₃ : 0 < l₃.length)
    (hjoin₁₂ : Γ.tgt (l₁[l₁.length - 1]'(by omega)) = Γ.src (l₂[0]'hne₂))
    (hjoin₂₃ : Γ.tgt (l₂[l₂.length - 1]'(by omega)) = Γ.src (l₃[0]'hne₃)) :
    Composable Γ (l₁ ++ l₂ ++ l₃) := by
  have h₁₂ := append_composable l₁ l₂ h₁ h₂ hne₁ hne₂ hjoin₁₂
  have hne₁₂ : 0 < (l₁ ++ l₂).length := by simp; omega
  have hjoin₁₂₃ : Γ.tgt ((l₁ ++ l₂)[(l₁ ++ l₂).length - 1]'(by omega)) =
      Γ.src (l₃[0]'hne₃) := by
    have hge : l₁.length ≤ (l₁ ++ l₂).length - 1 := by simp; omega
    simp only [List.getElem_append_right hge,
               show (l₁ ++ l₂).length - 1 - l₁.length = l₂.length - 1 from by simp; omega]
    exact hjoin₂₃
  exact append_composable (l₁ ++ l₂) l₃ h₁₂ h₃ hne₁₂ hne₃ hjoin₁₂₃

def lollipopLoop {Γ : DirectedGraph} [HasReversal Γ]
    (γ : GraphPath Γ) (L : GraphLoop Γ)
    (hγne : 0 < γ.edges.length)
    (hjoin : Γ.tgt (γ.edges[γ.edges.length - 1]'(by omega)) =
             Γ.src (L.edges[0]'L.nonempty)) :
    GraphLoop Γ where
  edges := γ.edges ++ L.edges ++ revEdges γ.edges
  composable := by
    have hrlen : (revEdges γ.edges).length = γ.edges.length := revEdges_length γ.edges
    have hrne : 0 < (revEdges γ.edges).length := hrlen ▸ hγne
    have hLne := L.nonempty
    -- Compute src of first element of revEdges
    have src_rev0 : Γ.src ((revEdges γ.edges)[0]'hrne) =
        Γ.tgt (γ.edges[γ.edges.length - 1]'(by omega)) := by
      -- revEdges γ = (γ.map rev).reverse
      -- [0] of that = rev(γ[last])
      -- src(rev(x)) = tgt(x)
      simp only [revEdges]
      rw [List.getElem_reverse (by simp; exact hγne)]
      simp only [List.length_map, List.getElem_map, HasReversal.rev_src, Nat.sub_zero]
    have hLbound : L.edges.length - 1 < L.edges.length := Nat.sub_one_lt_of_le hLne le_rfl
    have hjoin_L_rev : Γ.tgt (L.edges[L.edges.length - 1]'hLbound) =
        Γ.src ((revEdges γ.edges)[0]'hrne) := by
      rw [src_rev0]; exact (L.closed).trans hjoin.symm
    exact three_append_composable γ.edges L.edges (revEdges γ.edges)
      γ.composable L.composable (revEdges_composable γ.edges γ.composable)
      hγne L.nonempty hrne hjoin hjoin_L_rev
  nonempty := by
    show 0 < (γ.edges ++ L.edges ++ revEdges γ.edges).length
    simp only [List.length_append, revEdges_length]; omega
  closed := by
    -- Strategy: show last = rev(γ[0]) and first = γ[0], then use rev_tgt
    -- We work with let bindings to avoid length computation issues
    set edges := γ.edges ++ L.edges ++ revEdges γ.edges
    have hlen_eq : edges.length = γ.edges.length + L.edges.length + γ.edges.length := by
      simp only [edges, List.length_append, revEdges_length]
    -- Last element: in the revEdges part
    have h_last_eq : edges[edges.length - 1]'(by omega) =
        (revEdges γ.edges)[γ.edges.length - 1]'(by simp [revEdges_length]; omega) := by
      simp only [edges]
      rw [List.getElem_append_right (show (γ.edges ++ L.edges).length ≤
          (γ.edges ++ L.edges ++ revEdges γ.edges).length - 1 from by
          simp [List.length_append, revEdges_length]; omega)]
      congr 1
      simp only [List.length_append, revEdges_length]; omega
    have hrlen2 : (revEdges γ.edges).length = γ.edges.length := revEdges_length γ.edges
    have hbound : γ.edges.length - 1 < (revEdges γ.edges).length := by rw [hrlen2]; omega
    have h_last_rev : (revEdges γ.edges)[γ.edges.length - 1]'hbound =
        HasReversal.rev (γ.edges[0]'hγne) := by
      simp only [revEdges, List.getElem_reverse (by simp; omega),
                  List.length_map, List.getElem_map]
      congr 1; simp_all [revEdges_length]
    -- First element
    have h_first_eq : edges[0]'(by omega) = γ.edges[0]'hγne := by
      simp only [edges]
      rw [List.getElem_append_left (show (0 : ℕ) < (γ.edges ++ L.edges).length from by simp; omega),
          List.getElem_append_left hγne]
    rw [h_last_eq, h_last_rev, h_first_eq, HasReversal.rev_tgt]

theorem lollipop_base {Γ : DirectedGraph} [HasReversal Γ]
    (γ : GraphPath Γ) (L : GraphLoop Γ)
    (hγne : 0 < γ.edges.length)
    (hjoin : Γ.tgt (γ.edges[γ.edges.length - 1]'(by omega)) =
             Γ.src (L.edges[0]'L.nonempty)) :
    Γ.src ((lollipopLoop γ L hγne hjoin).edges[0]'
      (lollipopLoop γ L hγne hjoin).nonempty) =
    Γ.src (γ.edges[0]'hγne) := by
  show Γ.src ((γ.edges ++ L.edges ++ revEdges γ.edges)[0]'_) = _
  rw [List.getElem_append_left (show (0 : ℕ) < (γ.edges ++ L.edges).length by simp; omega),
      List.getElem_append_left hγne]

theorem lollipop_holonomy {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (γ : GraphPath Γ) (L : GraphLoop Γ)
    (hγne : 0 < γ.edges.length)
    (hjoin : Γ.tgt (γ.edges[γ.edges.length - 1]'(by omega)) =
             Γ.src (L.edges[0]'L.nonempty)) :
    holonomy conn (lollipopLoop γ L hγne hjoin).toGraphPath =
    hol conn γ.edges * hol conn L.edges * (hol conn γ.edges)⁻¹ := by
  show hol conn (lollipopLoop γ L hγne hjoin).edges = _
  simp only [lollipopLoop]
  exact lollipop_hol conn γ.edges L.edges

/-! ## Ambrose-Singer: converse direction (FULLY PROVED) -/

theorem basedCurvature_is_holonomy
    {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (v₀ : Γ.Vertex) (γ : GraphPath Γ) (plaq : Plaquette Γ)
    (hγne : 0 < γ.edges.length)
    (hstart : Γ.src (γ.edges[0]'hγne) = v₀)
    (hjoin : Γ.tgt (γ.edges[γ.edges.length - 1]'(by omega)) =
             Γ.src (plaq.edges[0]'plaq.nonempty)) :
    hol conn γ.edges * hol conn plaq.edges * (hol conn γ.edges)⁻¹ ∈
    holonomySet conn v₀ := by
  refine ⟨lollipopLoop γ plaq hγne hjoin, ?_, ?_⟩
  · rw [lollipop_base]; exact hstart
  · exact lollipop_holonomy conn γ plaq hγne hjoin

theorem discrete_ambrose_singer_converse
    {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (v₀ : Γ.Vertex) :
    Subgroup.closure (basedCurvatureSet conn v₀) ≤ holonomySubgroup conn v₀ := by
  apply (Subgroup.closure_le _).2
  intro h ⟨γ, plaq, hγne, hstart, hjoin, heq⟩
  rw [heq]
  exact Subgroup.subset_closure
    (basedCurvature_is_holonomy conn v₀ γ plaq hγne hstart hjoin)

/-! ## Ambrose-Singer: forward direction (discrete Stokes — PROVED) -/

theorem discrete_stokes
    {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (v₀ : Γ.Vertex) :
    holonomySet conn v₀ ⊆ Subgroup.closure (basedCurvatureSet conn v₀) := by
  intro h ⟨loop, hstart, hhol⟩
  rw [← hhol]
  -- Strategy: use the round-trip path γ = [e₀, rev(e₀)] from v₀,
  -- with the loop itself as the plaquette. Then hol(γ) = 1 so
  -- the based curvature = hol(loop).
  set e₀ := loop.edges[0]'loop.nonempty
  -- Build γ as a GraphPath with edges [e₀, rev(e₀)]
  have γ_composable : ∀ i : Fin ([e₀, HasReversal.rev e₀].length - 1),
      Γ.tgt ([e₀, HasReversal.rev e₀][i.val]'(by omega)) =
      Γ.src ([e₀, HasReversal.rev e₀][i.val + 1]'(by omega)) := by
    intro ⟨i, hi⟩
    simp at hi
    have : i = 0 := by omega
    subst this
    simp [HasReversal.rev_src]
  set γ : GraphPath Γ := ⟨[e₀, HasReversal.rev e₀], γ_composable⟩
  have hγne : 0 < γ.edges.length := by simp [γ]
  have hγ_start : Γ.src (γ.edges[0]'hγne) = v₀ := by
    simp [γ]; exact hstart
  have hγ_end : Γ.tgt (γ.edges[γ.edges.length - 1]'(by omega)) =
      Γ.src (loop.edges[0]'loop.nonempty) := by
    simp only [γ, e₀, List.length_cons, List.length_nil, Nat.add_sub_cancel,
      List.getElem_cons_succ, List.getElem_cons_zero, HasReversal.rev_tgt]
  -- The holonomy of γ is 1
  have hγ_hol : hol conn γ.edges = 1 := by
    simp only [γ, hol, List.foldl, one_mul]
    rw [ReversibleConnection.transport_rev (conn := conn)]
    exact mul_inv_cancel _
  -- The element is in basedCurvatureSet
  apply Subgroup.subset_closure
  show holonomy conn loop.toGraphPath ∈ basedCurvatureSet conn v₀
  refine ⟨γ, loop, hγne, hγ_start, hγ_end, ?_⟩
  rw [← hol_eq_holonomy, hγ_hol, one_mul, inv_one, mul_one]

theorem discrete_ambrose_singer_forward
    {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (v₀ : Γ.Vertex) :
    holonomySubgroup conn v₀ ≤ Subgroup.closure (basedCurvatureSet conn v₀) :=
  (Subgroup.closure_le _).2 (discrete_stokes conn v₀)

/-! ## The full theorem -/

theorem discrete_ambrose_singer_eq
    {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn]
    (v₀ : Γ.Vertex) :
    holonomySubgroup conn v₀ = Subgroup.closure (basedCurvatureSet conn v₀) :=
  le_antisymm
    (discrete_ambrose_singer_forward conn v₀)
    (discrete_ambrose_singer_converse conn v₀)

theorem holonomy_minimal
    {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (v₀ : Γ.Vertex)
    (K : Subgroup G) (hK : holonomySet conn v₀ ⊆ K) :
    holonomySubgroup conn v₀ ≤ K :=
  (Subgroup.closure_le _).2 hK

/-! ## Path operations -/

def pathConcat {Γ : DirectedGraph}
    (p₁ p₂ : GraphPath Γ)
    (h₁ : 0 < p₁.edges.length) (h₂ : 0 < p₂.edges.length)
    (hjoin : Γ.tgt (p₁.edges[p₁.edges.length - 1]'(by omega)) =
             Γ.src (p₂.edges[0]'h₂)) :
    GraphPath Γ where
  edges := p₁.edges ++ p₂.edges
  composable := append_composable p₁.edges p₂.edges p₁.composable p₂.composable h₁ h₂ hjoin

theorem holonomy_concat {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (p₁ p₂ : GraphPath Γ)
    (h₁ : 0 < p₁.edges.length) (h₂ : 0 < p₂.edges.length)
    (hjoin : Γ.tgt (p₁.edges[p₁.edges.length - 1]'(by omega)) =
             Γ.src (p₂.edges[0]'h₂)) :
    holonomy conn (pathConcat p₁ p₂ h₁ h₂ hjoin) =
    holonomy conn p₁ * holonomy conn p₂ := by
  show hol conn (p₁.edges ++ p₂.edges) = hol conn p₁.edges * hol conn p₂.edges
  exact hol_append conn p₁.edges p₂.edges

def pathReverse {Γ : DirectedGraph} [HasReversal Γ]
    (p : GraphPath Γ) : GraphPath Γ where
  edges := revEdges p.edges
  composable := revEdges_composable p.edges p.composable

theorem holonomy_reverse {Γ : DirectedGraph} {G : Type*} [Group G]
    [HasReversal Γ] (conn : DiscreteConnection Γ G)
    [ReversibleConnection Γ G conn] (p : GraphPath Γ) :
    holonomy conn (pathReverse p) = (holonomy conn p)⁻¹ := by
  show hol conn (revEdges p.edges) = (hol conn p.edges)⁻¹
  exact hol_reverse_eq_inv conn p.edges

/-! ## Gauge invariance of loop holonomy -/

/-- Gauge-transformed holonomy of a singleton list. -/
private theorem hol_gaugeTransform_singleton
    {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (g : GaugeTransformation Γ G)
    (e : Γ.Edge) :
    hol (gaugeTransform conn g) [e] =
    (g (Γ.src e))⁻¹ * conn.transport e * g (Γ.tgt e) := by
  simp [hol, List.foldl, one_mul, gaugeTransform]

/-- The holonomy of a gauge-transformed connection telescopes:
    hol(gaugeTransform conn g, l) = g(src l[0])⁻¹ · hol(conn, l) · g(tgt l[last]). -/
theorem hol_gaugeTransform_telescope
    {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (g : GaugeTransformation Γ G)
    (l : List Γ.Edge) (hne : 0 < l.length)
    (hcomp : ∀ i : Fin (l.length - 1),
      Γ.tgt (l[i.val]'(by omega)) = Γ.src (l[i.val + 1]'(by omega))) :
    hol (gaugeTransform conn g) l =
    (g (Γ.src (l[0]'hne)))⁻¹ *
    hol conn l *
    g (Γ.tgt (l[l.length - 1]'(by omega))) := by
  match l, hne, hcomp with
  | [e], _, _ =>
    simp only [List.length_singleton, Nat.sub_self, List.getElem_cons_zero]
    rw [hol_gaugeTransform_singleton, hol_singleton]
  | e :: e' :: es', _, hcomp =>
    have hne' : 0 < (e' :: es').length := by simp
    have hcomp' : ∀ i : Fin ((e' :: es').length - 1),
        Γ.tgt ((e' :: es')[i.val]'(by omega)) =
        Γ.src ((e' :: es')[i.val + 1]'(by omega)) := by
      intro ⟨i, hi⟩
      exact hcomp ⟨i + 1, by simp at hi ⊢; omega⟩
    have hjoin : Γ.tgt e = Γ.src e' := by
      have := hcomp ⟨0, by simp [List.length_cons]⟩
      simpa using this
    have ih' := hol_gaugeTransform_telescope conn g (e' :: es') hne' hcomp'
    -- Rewrite: hol gauge (e :: e' :: es') = hol gauge [e] * hol gauge (e' :: es')
    have step1 : hol (gaugeTransform conn g) (e :: e' :: es') =
        hol (gaugeTransform conn g) [e] * hol (gaugeTransform conn g) (e' :: es') := by
      rw [show (e :: e' :: es') = [e] ++ (e' :: es') from rfl, hol_append]
    -- Rewrite: hol conn (e :: e' :: es') = hol conn [e] * hol conn (e' :: es')
    have step2 : hol conn (e :: e' :: es') =
        hol conn [e] * hol conn (e' :: es') := by
      rw [show (e :: e' :: es') = [e] ++ (e' :: es') from rfl, hol_append]
    rw [step1, hol_gaugeTransform_singleton, ih']
    -- LHS: g(src e)⁻¹ * t(e) * g(tgt e) * (g(src e')⁻¹ * hol(es') * g(tgt last(es')))
    -- RHS: g(src (e::e'::es')[0])⁻¹ * hol(e::e'::es') * g(tgt (e::e'::es')[last])
    simp only [List.getElem_cons_zero, List.length_cons, List.getElem_cons_succ]
    rw [step2, hol_singleton, hjoin]
    -- Remaining: g(tgt (e' :: es')[1 + es'.length - 1]) vs g(tgt (e :: e' :: es')[2 + es'.length - 1])
    -- Both refer to the last element; show the list elements are equal
    -- Both sides are the same modulo index normalization
    -- Try: normalize the Nat arithmetic then simplify list access
    simp (config := { decide := false }) only [Nat.add_sub_cancel, List.getElem_cons_succ]
    group

/-- **Gauge invariance**: gauge transformation conjugates loop holonomy.
    hol'(loop) = g(v₀)⁻¹ · hol(loop) · g(v₀).

    The proof telescopes: consecutive g(tgt eᵢ) · g(src eᵢ₊₁)⁻¹ cancel
    by composability. -/
theorem gauge_conjugates_loop_holonomy
    {Γ : DirectedGraph} {G : Type*} [Group G]
    (conn : DiscreteConnection Γ G) (g : GaugeTransformation Γ G)
    (loop : GraphLoop Γ) :
    holonomy (gaugeTransform conn g) loop.toGraphPath =
    (g (Γ.src (loop.edges[0]'loop.nonempty)))⁻¹ *
    holonomy conn loop.toGraphPath *
    g (Γ.src (loop.edges[0]'loop.nonempty)) := by
  show hol (gaugeTransform conn g) loop.edges = _
  rw [hol_gaugeTransform_telescope conn g loop.edges loop.nonempty loop.composable]
  congr 1
  congr 1
  exact loop.closed

end UnifiedTheory.LayerA.DiscreteAmbroseSinger
