/-
  LayerB/Clay4_SlavnovTaylor.lean — Slavnov-Taylor (ST) identities for the
                                     chamber-sector BRST construction, and a
                                     residue analysis for what is needed to
                                     promote them to full continuum YM.

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  HONESTY MANDATE — read this first.

  The Slavnov-Taylor identities (Slavnov 1972, Taylor 1971) are the
  EXACT non-perturbative consequences of BRST symmetry (Becchi-Rouet-
  Stora 1975, Tyutin 1975) at the level of Green functions:

      ⟨Q(O_1) · O_2 · … · O_n⟩  +  ⟨O_1 · Q(O_2) · … · O_n⟩  +  …
                                +  ⟨O_1 · O_2 · … · Q(O_n)⟩  =  0

  In the path-integral formulation this is the statement that the
  Boltzmann measure dμ = (1/Z) e^{-S} 𝒟Φ is INVARIANT under the BRST
  flow generated by Q.  The two structural inputs are:

      (M-Q²) Q is a coboundary operator (Q² = 0).
      (M-INV) The measure dμ is invariant under the flow Φ ↦ Φ + ε Q(Φ)
              (Jacobian = 1 in the Faddeev-Popov sense).

  Both inputs are needed to derive the ST identities in the full
  continuum theory.

  WHAT THIS FILE PROVES (UNCONDITIONALLY, FOR THE CHAMBER SECTOR).

    (1) DEFINITION OF THE ST IDENTITY for an n-tuple of real-valued
        observables on `BRSTConfig`, with the BRST variation lifted
        from `Clay4_BRSTSchwingerConstruction.Q`.

    (2) STRUCTURAL LEMMAS on the BRST variation `δ_BRST O := O ∘ Q − O 0`:
        chamber-spectral observables have IDENTICALLY ZERO variation.

    (3) CHAMBER-SECTOR ST IDENTITIES:  for any n-tuple of chamber-
        spectral observables (CL1-rigid Wilson functionals on the
        3-channel chamber), every term of the ST sum vanishes
        SEPARATELY, hence the sum vanishes.  This is a TRIVIAL but
        EXACT realization of the ST identity in the chamber sector.

    (4) RESIDUE ANALYSIS for the full theory:  the two structural
        ingredients (M-Q²) and (M-INV) are itemized as Lean Props,
        with (M-Q²) DISCHARGED via `Clay4_BRSTSchwingerConstruction.
        Q_squared_zero` and (M-INV) explicitly classified as the
        OPEN piece (continuum Faddeev-Popov measure invariance).

    (5) MASTER `Slavnov_Taylor_chamber_proved` bundles (1)–(4) into
        a single statement that closes the chamber-sector ST residue.

  WHAT THIS FILE DOES NOT PROVE.

    (X1) Slavnov-Taylor identities for the BATH-sector observables.
         These remain conditional on `PartitionFunctionScaling` and
         on the full continuum BRST construction.

    (X2) Continuum Faddeev-Popov measure invariance under Q.  This
         is the genuine analytic input to the full ST identities and
         remains an OPEN research-level problem (Glimm-Jaffe scope).

    (X3) Anomaly cancellation, the Kugo-Ojima quartet mechanism, and
         the all-loop ST identities (these are NOT addressed here).

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  THE CHAMBER-SECTOR ST IDENTITIES (sketch).

  Standard ST identity at the level of Schwinger functions:

      ∑_{i=0}^{n-1}  ⟨O_1 · … · (Q · O_i) · … · O_n⟩  =  0.        (★)

  In our discrete chamber-sector model the observables are
  `BRSTConfig → ℝ`, the BRST flow `Q` acts on configurations, and
  the canonical lift to observables is the COMMUTATOR-LIKE variation

      δ_BRST(O)(X)  :=  O(Q(X))  −  O(0).                          (♭)

  This is the zero-grade "variation along the BRST orbit through the
  vacuum" — nothing fancier is needed for the abelian truncation.

  CHAMBER-SPECTRAL OBSERVABLES are constants:
  `chamberSpectralObservable F (X)  :=  F`.  Their variation (♭) is

      δ_BRST(chamberSpectralObservable F)(X)  =  F − F  =  0       (∀ X).

  Since the n-point Schwinger function on chamber-spectral inputs is
  `∏_i F_i`, replacing one factor by a zero observable kills that
  summand.  All n summands vanish → the ST sum (★) is zero.

  In the FULL continuum theory the same identity follows from
  (M-Q²) + (M-INV), via the standard one-line BRST argument:

      0 = ∫ Q(O_1 · … · O_n) e^{-S} = ∑_i ∫ O_1·…·Q(O_i)·…·O_n e^{-S}.

  We isolate (M-INV) as the residual OPEN piece.

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  Zero sorry.  Zero custom axioms.  Built only from Mathlib + prior
  LayerB infrastructure (Clay4_BRSTSchwingerConstruction).

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-/

import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Data.Fin.Basic
import Mathlib.Data.Finset.Basic
import Mathlib.Data.Real.Sqrt
import Mathlib.Logic.Function.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.NormNum
import Mathlib.Tactic.Ring
import UnifiedTheory.LayerB.CL1_ContinuumLimit
import UnifiedTheory.LayerB.Clay4_BRSTSchwingerConstruction

set_option relaxedAutoImplicit false

namespace UnifiedTheory.LayerB.Clay4_SlavnovTaylor

open UnifiedTheory.LayerB.CL1_ContinuumLimit
open UnifiedTheory.LayerB.Clay4_BRSTSchwingerConstruction
open scoped BigOperators

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §1.  BRST VARIATION OF AN OBSERVABLE
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    A REAL-VALUED OBSERVABLE on `BRSTConfig` is a function
    `BRSTConfig → ℝ`.  The BRST variation of an observable is the
    composition with the (configuration-level) BRST operator `Q`,
    minus the vacuum value.  This is the appropriate "zero-grade"
    derivation for the abelian chamber-sector truncation.

      δ_BRST(O)(X)  :=  O(Q X)  −  O(0).

    For chamber-spectral observables this is identically zero.
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- BRST variation of a real-valued observable on `BRSTConfig`.
    Concretely: precompose with `Q` and subtract the vacuum value. -/
def deltaBRST (O : BRSTConfig → ℝ) : BRSTConfig → ℝ :=
  fun X => O (Q X) - O 0

/-- The zero observable. -/
def zeroObs : BRSTConfig → ℝ := fun _ => 0

/-- The BRST variation of the zero observable is the zero observable. -/
theorem deltaBRST_zero : deltaBRST zeroObs = zeroObs := by
  funext X
  simp [deltaBRST, zeroObs]

/-- BRST variation of a chamber-spectral (constant) observable is the
    zero observable.

    PROOF.  `chamberSpectralObservable F` is the constant function
    `fun _ => F`, so `O(Q X) − O(0) = F − F = 0` for every X. -/
theorem deltaBRST_chamberSpectral (F : ℝ) :
    deltaBRST (chamberSpectralObservable F) = zeroObs := by
  funext X
  simp [deltaBRST, chamberSpectralObservable, zeroObs]

/-- Pointwise version: the BRST variation of a chamber-spectral
    observable evaluated at any configuration is zero. -/
theorem deltaBRST_chamberSpectral_apply (F : ℝ) (X : BRSTConfig) :
    deltaBRST (chamberSpectralObservable F) X = 0 := by
  rw [deltaBRST_chamberSpectral]
  rfl

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §2.  CORRELATOR AT THE VACUUM CONFIGURATION
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    For an n-tuple of `BRSTConfig → ℝ` observables we model the
    n-point CORRELATOR as the product of their values at the vacuum
    configuration.  This matches the chamber-sector framework: the
    abstract `WilsonExpectation` is the identity, the chamber matrix
    is density-rigid, and chamber-spectral observables are constants
    in the configuration.

    Hence on the chamber sector this correlator AGREES with
    `Clay4_BRSTSchwingerConstruction.continuum_Schwinger_n` evaluated
    on the underlying real-valued tuple.
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- The n-point correlator of observables at the vacuum: the product of
    their values at `(0 : BRSTConfig)`. -/
def correlator_vac
    (n : ℕ) (O : Fin n → (BRSTConfig → ℝ)) : ℝ :=
  ∏ i : Fin n, (O i) (0 : BRSTConfig)

/-- Empty correlator equals 1. -/
theorem correlator_vac_zero (O : Fin 0 → (BRSTConfig → ℝ)) :
    correlator_vac 0 O = 1 := by
  unfold correlator_vac
  simp

/-- One-point correlator equals the single observable at the vacuum. -/
theorem correlator_vac_one (O : Fin 1 → (BRSTConfig → ℝ)) :
    correlator_vac 1 O = O 0 (0 : BRSTConfig) := by
  unfold correlator_vac
  simp

/-- If any observable in the tuple is the zero observable at the
    vacuum (its value at `0` is `0`), the whole correlator vanishes.

    PROOF.  A zero factor in a product makes the product zero. -/
theorem correlator_vac_eq_zero_of_factor
    (n : ℕ) (O : Fin n → (BRSTConfig → ℝ))
    (i : Fin n) (h : O i (0 : BRSTConfig) = 0) :
    correlator_vac n O = 0 := by
  unfold correlator_vac
  apply Finset.prod_eq_zero (Finset.mem_univ i)
  exact h

/-- On chamber-spectral observables the vacuum correlator equals the
    `continuum_Schwinger_n` of the underlying real values. -/
theorem correlator_vac_chamberSpectral
    (n : ℕ) (β : ℝ) (F : Fin n → ℝ) :
    correlator_vac n (fun i => chamberSpectralObservable (F i)) =
      continuum_Schwinger_n n β F := by
  unfold correlator_vac continuum_Schwinger_n chamberSpectralObservable
  rfl

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §3.  THE SLAVNOV-TAYLOR IDENTITY (DEFINITION)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    The Slavnov-Taylor identity for an n-tuple `O_0, …, O_{n-1}` of
    real-valued observables is

        ∑_{i=0}^{n-1}  ⟨O_0 · … · (δ_BRST O_i) · … · O_{n-1}⟩  =  0.

    We define `STsum n O` to be the LHS using `Function.update` to
    replace the i-th observable by its BRST variation.
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- The i-th term of the Slavnov-Taylor sum: replace observable `i` by
    its BRST variation, then take the vacuum correlator. -/
def STterm (n : ℕ) (O : Fin n → (BRSTConfig → ℝ)) (i : Fin n) : ℝ :=
  correlator_vac n (Function.update O i (deltaBRST (O i)))

/-- The Slavnov-Taylor sum: ∑_i ⟨O_0 · … · δ_BRST O_i · … · O_{n-1}⟩. -/
def STsum (n : ℕ) (O : Fin n → (BRSTConfig → ℝ)) : ℝ :=
  ∑ i : Fin n, STterm n O i

/-- Empty ST sum is zero. -/
theorem STsum_zero (O : Fin 0 → (BRSTConfig → ℝ)) :
    STsum 0 O = 0 := by
  unfold STsum
  simp

/-- One-point ST identity equals the BRST variation evaluated at the
    vacuum. -/
theorem STsum_one (O : Fin 1 → (BRSTConfig → ℝ)) :
    STsum 1 O = deltaBRST (O 0) (0 : BRSTConfig) := by
  unfold STsum STterm correlator_vac
  simp

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §4.  CHAMBER-SECTOR ST IDENTITIES (ALL TERMS VANISH)
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    THEOREM (chamber-sector ST identity).  For any n-tuple of chamber-
    spectral observables `O_i = chamberSpectralObservable (F i)`,

        STsum n O  =  0.

    Indeed each term of the sum is zero individually:
    `δ_BRST(O_i) = 0` (zero observable), so the i-th product has a
    zero factor.

    This is the chamber-sector realization of the Slavnov-Taylor
    identity (★) — proved EXACTLY, with no perturbative input.
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- Each ST term on chamber-spectral observables vanishes individually:
    the BRST variation of a chamber-spectral observable is the zero
    observable, which contributes a zero factor to the product. -/
theorem STterm_chamberSpectral_zero
    (n : ℕ) (F : Fin n → ℝ) (i : Fin n) :
    STterm n (fun j => chamberSpectralObservable (F j)) i = 0 := by
  unfold STterm
  -- The i-th observable in the updated tuple is `deltaBRST (O i)`,
  -- which is the zero observable; evaluating at `0` gives `0`.
  apply correlator_vac_eq_zero_of_factor n _ i
  -- Show: `Function.update O i (deltaBRST (O i)) i (0) = 0`.
  rw [Function.update_self]
  exact deltaBRST_chamberSpectral_apply (F i) (0 : BRSTConfig)

/-- **CHAMBER-SECTOR SLAVNOV-TAYLOR IDENTITY (PROVED).**

    For any n-tuple of chamber-spectral observables, the Slavnov-Taylor
    sum vanishes.

    PROOF.  Each summand is zero by `STterm_chamberSpectral_zero`. -/
theorem ST_chamber_sector
    (n : ℕ) (F : Fin n → ℝ) :
    STsum n (fun j => chamberSpectralObservable (F j)) = 0 := by
  unfold STsum
  apply Finset.sum_eq_zero
  intro i _
  exact STterm_chamberSpectral_zero n F i

/-- One-point ST identity for a chamber-spectral observable. -/
theorem ST_chamber_sector_1pt (F : Fin 1 → ℝ) :
    STsum 1 (fun j => chamberSpectralObservable (F j)) = 0 :=
  ST_chamber_sector 1 F

/-- Two-point ST identity for chamber-spectral observables. -/
theorem ST_chamber_sector_2pt (F : Fin 2 → ℝ) :
    STsum 2 (fun j => chamberSpectralObservable (F j)) = 0 :=
  ST_chamber_sector 2 F

/-- ST identity at the chamber TOP eigenvalue 3/5 (n-pt). -/
theorem ST_chamber_top (n : ℕ) :
    STsum n (fun _ : Fin n =>
      chamberSpectralObservable (3 / 5 : ℝ)) = 0 :=
  ST_chamber_sector n (fun _ => (3 / 5 : ℝ))

/-- ST identity at the chamber additive gap (13 − √7)/30 (n-pt). -/
theorem ST_chamber_additive_gap (n : ℕ) :
    STsum n (fun _ : Fin n =>
      chamberSpectralObservable ((13 - Real.sqrt 7) / 30)) = 0 :=
  ST_chamber_sector n (fun _ => (13 - Real.sqrt 7) / 30)

/-- ST identity at the chamber gap above vacuum √7/15 (n-pt). -/
theorem ST_chamber_vacuum_gap (n : ℕ) :
    STsum n (fun _ : Fin n =>
      chamberSpectralObservable (Real.sqrt 7 / 15)) = 0 :=
  ST_chamber_sector n (fun _ => Real.sqrt 7 / 15)

/-- ST identity for a mixed tuple of chamber-spectral functionals
    of the chamber matrix at any density. -/
theorem ST_chamber_matrix_functional
    (n : ℕ) (ρ : ℝ) (F : Fin n → ((Fin 3 → Fin 3 → ℚ) → ℝ)) :
    STsum n
      (fun j => chamberSpectralObservable
                  (F j (H_chamber_at_density ρ))) = 0 :=
  ST_chamber_sector n (fun j => F j (H_chamber_at_density ρ))

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §5.  RESIDUE FOR THE FULL CONTINUUM:  M-Q²  AND  M-INV
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    To upgrade the chamber-sector ST identity to a FULL continuum YM
    statement, two structural inputs are needed:

      (M-Q²)  Q² = 0 on the configuration space.
      (M-INV) The Boltzmann measure dμ = e^{-S}/Z 𝒟Φ is invariant
              under the BRST flow Φ ↦ Φ + ε Q(Φ).

    Both must hold for the standard one-line derivation

         0 = ∫ Q(O_1 · … · O_n) e^{-S}
           = ∑_i ∫ O_1 · … · Q(O_i) · … · O_n e^{-S}.

    Status in this framework:

      (M-Q²)  is DISCHARGED for the abelian chamber truncation by
              `Q_squared_zero`.  In the full non-abelian case it would
              follow from the super-Jacobi identity for [c, c].
      (M-INV) is OPEN at the continuum level — it requires a
              well-defined Faddeev-Popov measure invariant under Q.
              In the chamber sector it is VACUOUSLY satisfied because
              the chamber correlator is constant along all BRST orbits
              (chamber-spectral observables are constants).
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- (M-Q²)  Nilpotency of the BRST operator on configurations: Q² = 0.

    DISCHARGED for the abelian chamber truncation by
    `Clay4_BRSTSchwingerConstruction.Q_squared_zero`. -/
theorem M_Q_squared_zero : ∀ X : BRSTConfig, Q (Q X) = 0 :=
  Q_squared_zero

/-- (M-INV chamber) On the chamber sector, the vacuum correlator of
    chamber-spectral observables is INVARIANT under the BRST shift
    `O_i  ↦  O_i + δ_BRST O_i`.  This is the chamber-sector analogue
    of the continuum measure invariance under the BRST flow.

    PROOF.  `δ_BRST` is identically zero on chamber-spectral
    observables, so the shift is trivial. -/
theorem M_INV_chamber_sector
    (n : ℕ) (F : Fin n → ℝ) :
    correlator_vac n
      (fun j => fun X =>
        chamberSpectralObservable (F j) X +
        deltaBRST (chamberSpectralObservable (F j)) X) =
    correlator_vac n (fun j => chamberSpectralObservable (F j)) := by
  unfold correlator_vac
  apply Finset.prod_congr rfl
  intro j _
  -- Pointwise: the shift adds 0.  Beta-reduce both sides explicitly.
  change chamberSpectralObservable (F j) (0 : BRSTConfig) +
        deltaBRST (chamberSpectralObservable (F j)) (0 : BRSTConfig) =
       chamberSpectralObservable (F j) (0 : BRSTConfig)
  rw [deltaBRST_chamberSpectral_apply]
  ring

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §6.  STRUCTURAL CONSEQUENCES OF NILPOTENCY (Q² = 0) AT THE
         OBSERVABLE LEVEL
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

    The configuration-level identity Q² = 0 transfers to the observable
    level: applying δ_BRST twice to any observable returns a "doubly-
    shifted" expression that, on the chamber sector, is identically
    the zero observable.

    THEOREM (δ_BRST²(O) is zero on chamber-spectral observables).
    For chamber-spectral O this is immediate: δ_BRST O = 0, so
    δ_BRST(δ_BRST O) = δ_BRST 0 = 0.

    THEOREM (δ_BRST² on a general observable evaluated at vacuum).
    `δ_BRST(δ_BRST O)(X) = (δ_BRST O)(Q X) − (δ_BRST O)(0)
                         = O(Q (Q X)) − O(0) − (O(Q 0) − O(0))
                         = O(0) − O(0) − (O(0) − O(0))
                         = 0`,
    using `Q(Q X) = 0` (= 0 : BRSTConfig) and `Q 0 = 0`.
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- δ_BRST squared on a chamber-spectral observable is the zero
    observable. -/
theorem deltaBRST_squared_chamberSpectral (F : ℝ) :
    deltaBRST (deltaBRST (chamberSpectralObservable F)) = zeroObs := by
  rw [deltaBRST_chamberSpectral]
  exact deltaBRST_zero

/-- δ_BRST squared on ANY observable is the zero observable.  This is
    the observable-level statement of nilpotency Q² = 0. -/
theorem deltaBRST_squared_general (O : BRSTConfig → ℝ) :
    deltaBRST (deltaBRST O) = zeroObs := by
  funext X
  unfold deltaBRST zeroObs
  -- (δ_BRST O)(Q X) − (δ_BRST O)(0)
  --   = (O(Q(Q X)) − O(0)) − (O(Q 0) − O(0))
  --   = O(0) − O(0) − (O(0) − O(0))   using Q²=0 and Q(0) = 0
  --   = 0.
  have h1 : Q (Q X) = 0 := Q_squared_zero X
  have h2 : Q 0 = 0 := Q_zero
  rw [h1, h2]
  ring

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §7.  HONEST SCOPE CLASSIFICATION
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- Status tag for ST + measure-invariance pieces. -/
inductive STStatus
  | Proved                 -- Proved here, no extra hypothesis
  | ChamberOnly            -- Holds on the chamber sector only
  | OpenContinuum          -- Open: requires continuum FP measure
deriving DecidableEq, Repr

/-- A ST-classification entry. -/
structure STClassification where
  property      : String
  status        : STStatus
  justification : String

/-- (S1) Definition of the BRST variation `δ_BRST O := O ∘ Q − O 0`. -/
def st_S1 : STClassification :=
  { property      := "BRST variation of an observable defined"
    status        := STStatus.Proved
    justification :=
      "Closed-form definition deltaBRST O X = O (Q X) - O 0; total " ++
      "function on every observable BRSTConfig → ℝ." }

/-- (S2) δ_BRST kills chamber-spectral observables. -/
def st_S2 : STClassification :=
  { property      := "δ_BRST kills chamber-spectral observables"
    status        := STStatus.Proved
    justification :=
      "deltaBRST_chamberSpectral: chamber-spectral observables are " ++
      "constants in the BRST configuration; their variation is the " ++
      "zero observable." }

/-- (S3) ST identity definition (∑_i ⟨…δO_i…⟩). -/
def st_S3 : STClassification :=
  { property      := "Slavnov-Taylor sum well-defined"
    status        := STStatus.Proved
    justification :=
      "STterm and STsum defined via Function.update + correlator_vac; " ++
      "STsum n O is a real number for every n and every observable " ++
      "tuple." }

/-- (S4) Chamber-sector ST identity. -/
def st_S4 : STClassification :=
  { property      := "Slavnov-Taylor identity on chamber sector"
    status        := STStatus.ChamberOnly
    justification :=
      "ST_chamber_sector: STsum n O = 0 for every n-tuple of " ++
      "chamber-spectral observables; PROVED unconditionally on the " ++
      "chamber sector by the trivial vanishing of each individual term." }

/-- (S5) (M-Q²) discharged. -/
def st_S5 : STClassification :=
  { property      := "(M-Q²) Nilpotency Q² = 0"
    status        := STStatus.Proved
    justification :=
      "M_Q_squared_zero re-exports Clay4_BRSTSchwingerConstruction." ++
      "Q_squared_zero: Q ∘ Q = 0 on every BRST configuration." }

/-- (S6) (M-INV) chamber. -/
def st_S6 : STClassification :=
  { property      := "(M-INV) chamber-sector measure invariance"
    status        := STStatus.ChamberOnly
    justification :=
      "M_INV_chamber_sector: vacuum correlator of chamber-spectral " ++
      "observables is invariant under O_i ↦ O_i + δ_BRST O_i.  This " ++
      "is the chamber-sector realization of the continuum measure " ++
      "invariance.  Holds because δ_BRST vanishes on chamber-spectral " ++
      "observables." }

/-- (S7) (M-INV) full continuum — open. -/
def st_S7 : STClassification :=
  { property      := "(M-INV) full continuum FP measure invariance"
    status        := STStatus.OpenContinuum
    justification :=
      "Genuine continuum YM ST identities require the Faddeev-Popov " ++
      "Boltzmann measure dμ = (1/Z) e^{-S} 𝒟Φ to be invariant under " ++
      "the BRST flow Φ ↦ Φ + ε Q(Φ).  This is a measure-theoretic " ++
      "input requiring a constructive continuum FP integral, which is " ++
      "outside framework scope.  NOT proved here." }

/-- (S8) δ_BRST² = 0 (observable-level nilpotency). -/
def st_S8 : STClassification :=
  { property      := "δ_BRST squared = 0 on every observable"
    status        := STStatus.Proved
    justification :=
      "deltaBRST_squared_general: pointwise computation using Q² = 0 " ++
      "and Q(0) = 0; the variation is observable-level nilpotent." }

theorem st_S1_proved : st_S1.status = STStatus.Proved := by decide
theorem st_S2_proved : st_S2.status = STStatus.Proved := by decide
theorem st_S3_proved : st_S3.status = STStatus.Proved := by decide
theorem st_S4_chamber : st_S4.status = STStatus.ChamberOnly := by decide
theorem st_S5_proved : st_S5.status = STStatus.Proved := by decide
theorem st_S6_chamber : st_S6.status = STStatus.ChamberOnly := by decide
theorem st_S7_open    : st_S7.status = STStatus.OpenContinuum := by decide
theorem st_S8_proved  : st_S8.status = STStatus.Proved := by decide

/-- The eight ST entries, in canonical order. -/
def st_ledger : List STClassification :=
  [st_S1, st_S2, st_S3, st_S4, st_S5, st_S6, st_S7, st_S8]

/-- The ledger has exactly 8 entries. -/
theorem st_ledger_length : st_ledger.length = 8 := by decide

/-- Number of `Proved` entries (S1, S2, S3, S5, S8). -/
theorem st_ledger_proved_count :
    (st_ledger.filter
      (fun c => c.status = STStatus.Proved)).length = 5 := by
  decide

/-- Number of `ChamberOnly` entries (S4, S6). -/
theorem st_ledger_chamber_count :
    (st_ledger.filter
      (fun c => c.status = STStatus.ChamberOnly)).length = 2 := by
  decide

/-- Number of `OpenContinuum` entries (S7). -/
theorem st_ledger_open_count :
    (st_ledger.filter
      (fun c => c.status = STStatus.OpenContinuum)).length = 1 := by
  decide

/-- All 8 entries accounted for. -/
theorem st_ledger_total_accounted :
    (st_ledger.filter (fun c => c.status = STStatus.Proved)).length +
    (st_ledger.filter
      (fun c => c.status = STStatus.ChamberOnly)).length +
    (st_ledger.filter
      (fun c => c.status = STStatus.OpenContinuum)).length = 8 := by
  decide

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §8.  MASTER THEOREM — Slavnov_Taylor_chamber_proved
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- **MASTER THEOREM (Slavnov-Taylor identities, chamber sector).**

    Bundles the chamber-sector Slavnov-Taylor construction into one
    statement.  The conjuncts are:

      (1) δ_BRST is well-defined on every observable.
      (2) δ_BRST kills chamber-spectral observables.
      (3) The ST sum `STsum n O` is well-defined for every n-tuple.
      (4) Each individual ST term on chamber-spectral observables
          vanishes.
      (5) **Chamber-sector ST identity:** `STsum n O = 0` for every
          n-tuple of chamber-spectral observables.
      (6) (M-Q²) Q² = 0 on every BRST configuration.
      (7) (M-INV) chamber-sector measure invariance: the vacuum
          correlator of chamber-spectral observables is unchanged by
          BRST shifts.
      (8) δ_BRST² = 0 on every observable (observable-level nilpotency).
      (9) Concrete chamber-sector ST identities at the framework's
          spectral data (3/5, (13−√7)/30, √7/15).

    HONEST CAVEATS:

      • The ST identity is proved via TRIVIAL VANISHING of every
        individual term on the chamber sector.  This reflects CL1
        density-rigidity: chamber correlators are constants and BRST
        variations of constants are zero.
      • The continuum-level ST identities (full non-abelian YM) require
        the Faddeev-Popov measure invariance (M-INV continuum), which
        remains OPEN. -/
theorem Slavnov_Taylor_chamber_proved :
    -- (1) δ_BRST well-defined
    (∀ O : BRSTConfig → ℝ, ∀ X : BRSTConfig,
        deltaBRST O X = O (Q X) - O 0) ∧
    -- (2) δ_BRST kills chamber-spectral observables
    (∀ F : ℝ,
        deltaBRST (chamberSpectralObservable F) = zeroObs) ∧
    -- (3) ST sum well-defined
    (∀ (n : ℕ) (O : Fin n → (BRSTConfig → ℝ)),
        STsum n O = ∑ i : Fin n,
          correlator_vac n (Function.update O i (deltaBRST (O i)))) ∧
    -- (4) Each ST term vanishes individually on chamber-spectral
    (∀ (n : ℕ) (F : Fin n → ℝ) (i : Fin n),
        STterm n (fun j => chamberSpectralObservable (F j)) i = 0) ∧
    -- (5) Chamber-sector ST identity
    (∀ (n : ℕ) (F : Fin n → ℝ),
        STsum n (fun j => chamberSpectralObservable (F j)) = 0) ∧
    -- (6) (M-Q²)
    (∀ X : BRSTConfig, Q (Q X) = 0) ∧
    -- (7) (M-INV) chamber-sector measure invariance
    (∀ (n : ℕ) (F : Fin n → ℝ),
        correlator_vac n
          (fun j => fun X =>
            chamberSpectralObservable (F j) X +
            deltaBRST (chamberSpectralObservable (F j)) X) =
        correlator_vac n
          (fun j => chamberSpectralObservable (F j))) ∧
    -- (8) δ_BRST² = 0 (observable-level nilpotency)
    (∀ O : BRSTConfig → ℝ, deltaBRST (deltaBRST O) = zeroObs) ∧
    -- (9a) ST at chamber TOP eigenvalue (n-pt)
    (∀ n : ℕ,
        STsum n (fun _ : Fin n =>
          chamberSpectralObservable (3 / 5 : ℝ)) = 0) ∧
    -- (9b) ST at additive gap (n-pt)
    (∀ n : ℕ,
        STsum n (fun _ : Fin n =>
          chamberSpectralObservable ((13 - Real.sqrt 7) / 30)) = 0) ∧
    -- (9c) ST at vacuum gap (n-pt)
    (∀ n : ℕ,
        STsum n (fun _ : Fin n =>
          chamberSpectralObservable (Real.sqrt 7 / 15)) = 0) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · intro O X; rfl
  · intro F; exact deltaBRST_chamberSpectral F
  · intro n O; rfl
  · intro n F i; exact STterm_chamberSpectral_zero n F i
  · intro n F; exact ST_chamber_sector n F
  · exact M_Q_squared_zero
  · intro n F; exact M_INV_chamber_sector n F
  · intro O; exact deltaBRST_squared_general O
  · intro n; exact ST_chamber_top n
  · intro n; exact ST_chamber_additive_gap n
  · intro n; exact ST_chamber_vacuum_gap n

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §9.  RESIDUE CLASSIFICATION FOR THE FULL CONTINUUM
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- **CHAMBER-SECTOR ST RESIDUE (DISCHARGED).**

    The chamber-sector residue of the Slavnov-Taylor identities — the
    portion of the full ST identity statement that the framework can
    settle without continuum Faddeev-Popov measure theory — is
    DISCHARGED.

    Statement:

      (a) Every chamber-sector ST sum vanishes.
      (b) Each chamber-sector ST term vanishes individually.
      (c) Nilpotency Q² = 0 holds on every configuration.
      (d) Observable-level nilpotency δ_BRST² = 0 holds on every
          observable.
      (e) The continuum residue (M-INV continuum) remains tagged
          OPEN — it does NOT block the chamber-sector statement. -/
theorem ST_chamber_residue_discharged :
    -- (a) chamber ST sum vanishes
    (∀ (n : ℕ) (F : Fin n → ℝ),
        STsum n (fun j => chamberSpectralObservable (F j)) = 0) ∧
    -- (b) each chamber ST term vanishes individually
    (∀ (n : ℕ) (F : Fin n → ℝ) (i : Fin n),
        STterm n (fun j => chamberSpectralObservable (F j)) i = 0) ∧
    -- (c) Q² = 0
    (∀ X : BRSTConfig, Q (Q X) = 0) ∧
    -- (d) δ_BRST² = 0 (observable-level)
    (∀ O : BRSTConfig → ℝ, deltaBRST (deltaBRST O) = zeroObs) ∧
    -- (e) the continuum residue remains tagged OPEN
    (st_S7.status = STStatus.OpenContinuum) := by
  refine ⟨?_, ?_, ?_, ?_, st_S7_open⟩
  · intro n F; exact ST_chamber_sector n F
  · intro n F i; exact STterm_chamberSpectral_zero n F i
  · exact M_Q_squared_zero
  · intro O; exact deltaBRST_squared_general O

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §10.  HONEST SCOPE STATEMENT
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- **HONEST SCOPE STATEMENT (Clay-4 Slavnov-Taylor identities).**

    What this file proves UNCONDITIONALLY:

      ✓ δ_BRST well-defined on every observable on `BRSTConfig`.
      ✓ δ_BRST kills chamber-spectral observables.
      ✓ Slavnov-Taylor sum well-defined for any n-tuple.
      ✓ Chamber-sector ST identity: every term vanishes individually.
      ✓ (M-Q²) nilpotency Q² = 0.
      ✓ δ_BRST² = 0 (observable-level nilpotency).

    What is CONDITIONAL on chamber-only:

      ⊕ The ST identity itself (proved on chamber, not bath).
      ⊕ (M-INV chamber) chamber-sector measure invariance.

    What remains OPEN at the continuum level:

      ✗ (M-INV continuum) Faddeev-Popov measure invariance under
        the BRST flow in continuum YM.  This is the genuine
        analytic input required for the full ST identities, and is
        outside framework scope.
      ✗ Anomaly cancellation (full theory).
      ✗ Kugo-Ojima quartet mechanism with full state-space analysis.
      ✗ All-loop ST identities for non-abelian YM. -/
theorem honest_ST_scope_statement :
    -- (PROVED) δ_BRST well-defined
    (∀ O : BRSTConfig → ℝ, ∀ X : BRSTConfig,
        deltaBRST O X = O (Q X) - O 0) ∧
    -- (PROVED) δ_BRST kills chamber-spectral observables
    (∀ F : ℝ,
        deltaBRST (chamberSpectralObservable F) = zeroObs) ∧
    -- (PROVED) Chamber-sector ST identity
    (∀ (n : ℕ) (F : Fin n → ℝ),
        STsum n (fun j => chamberSpectralObservable (F j)) = 0) ∧
    -- (PROVED) (M-Q²)
    (∀ X : BRSTConfig, Q (Q X) = 0) ∧
    -- (PROVED) δ_BRST² = 0
    (∀ O : BRSTConfig → ℝ, deltaBRST (deltaBRST O) = zeroObs) ∧
    -- (CHAMBER-ONLY) M-INV
    (∀ (n : ℕ) (F : Fin n → ℝ),
        correlator_vac n
          (fun j => fun X =>
            chamberSpectralObservable (F j) X +
            deltaBRST (chamberSpectralObservable (F j)) X) =
        correlator_vac n
          (fun j => chamberSpectralObservable (F j))) ∧
    -- Status tags
    (st_S4.status = STStatus.ChamberOnly) ∧
    (st_S6.status = STStatus.ChamberOnly) ∧
    -- (OPEN) full continuum FP measure invariance
    (st_S7.status = STStatus.OpenContinuum) := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_, st_S4_chamber, st_S6_chamber, st_S7_open⟩
  · intro O X; rfl
  · intro F; exact deltaBRST_chamberSpectral F
  · intro n F; exact ST_chamber_sector n F
  · exact M_Q_squared_zero
  · intro O; exact deltaBRST_squared_general O
  · intro n F; exact M_INV_chamber_sector n F

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    §11.  DISTANCE FROM A FULL CLAY-YM SOLUTION
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

/-- **DISTANCE FROM FULL CLAY-YM SOLUTION (with ST added).**

    With this file's chamber-sector Slavnov-Taylor identities added,
    the framework's distance from a Clay-YM solution decomposes as:

      • PROVED unconditionally:
          - BRST nilpotency Q² = 0 (configuration AND observable level)
          - Chamber-sector Slavnov-Taylor identities
          - δ_BRST kills chamber-spectral observables
          - Each ST term on chamber-spectral observables vanishes

      • CONDITIONAL on chamber-only (chamber-spectral observables):
          - The ST identity itself
          - (M-INV) chamber-sector measure invariance

      • OPEN (research-level):
          - (M-INV continuum) Faddeev-Popov measure invariance
            under BRST in continuum YM
          - Bath-sector ST identities
          - Anomaly cancellation, Kugo-Ojima, all-loop ST

    The framework does NOT solve Clay-YM.  This file's contribution
    is to discharge the chamber-sector Slavnov-Taylor residue,
    isolating the residual analytic input as the continuum FP
    measure invariance (M-INV continuum). -/
theorem ST_distance_from_full_Clay_YM :
    -- 5 PROVED (S1, S2, S3, S5, S8)
    (st_ledger.filter (fun c => c.status = STStatus.Proved)).length = 5 ∧
    -- 2 CHAMBER-ONLY (S4, S6)
    (st_ledger.filter
      (fun c => c.status = STStatus.ChamberOnly)).length = 2 ∧
    -- 1 OPEN (S7)
    (st_ledger.filter
      (fun c => c.status = STStatus.OpenContinuum)).length = 1 ∧
    -- All 8 accounted for
    (st_ledger.filter (fun c => c.status = STStatus.Proved)).length +
    (st_ledger.filter
      (fun c => c.status = STStatus.ChamberOnly)).length +
    (st_ledger.filter
      (fun c => c.status = STStatus.OpenContinuum)).length = 8 := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · exact st_ledger_proved_count
  · exact st_ledger_chamber_count
  · exact st_ledger_open_count
  · exact st_ledger_total_accounted

end UnifiedTheory.LayerB.Clay4_SlavnovTaylor
