/-
  LayerB/GeometricSpeedLimit.lean
  ────────────────────────────────

  **The geometric speed limit: Mandelstam–Tamm as information geometry,
  and its unification with the Cramér–Rao metrology bound.**

  This file connects three pieces already present in `LayerB`:

    • the **Mandelstam–Tamm** quantum speed limit
      (`MandelstamTamm.mandelstam_tamm`, `T·ΔH ≥ π/2` to orthogonality),
    • the **quantum Fisher information / Cramér–Rao** bound
      (`QuantumCramerRao.quantumFisherInformation`, `Var(θ̂) ≥ 1/(ν F_Q)`),
    • the **Bures metric** (`BuresFidelity.buresDistance`),

  through a single object: the quantum Fisher information of the
  **time-evolved family** `ρ_t = e^{-iHt} ρ e^{iHt}`.

  ## The deep connection

  For unitary evolution generated by `H`, the parametric family in the
  time/phase parameter `t` has quantum Fisher information

      F_Q(t)  =  4 · Var_ρ(H)  =  4 ΔH².

  This single number does **two** things:

    1.  **Speed limit (Mandelstam–Tamm).**  The Bures-angle speed is
        `|dL/dt| = ½ √F_Q = √Var(H) = ΔH`.  Integrating, the time to
        traverse a Bures angle `L` is `T ≥ L / ΔH`.  At the orthogonality
        angle `L = π/2` this is the Mandelstam–Tamm bound
        `T · ΔH ≥ π/2`.

    2.  **Metrology precision (Cramér–Rao).**  The *same* `F_Q = 4ΔH²`
        bounds the variance of any unbiased estimator of the time/phase
        parameter:  `Var(t̂) ≥ 1/(ν F_Q) = 1/(4 ν ΔH²)`.  This is the
        quantum Cramér–Rao bound; its right-hand side is exactly
        `QuantumMetrology.crBound ν F_Q`.

  So the **time–energy uncertainty** (a speed limit) and the
  **time/phase estimation precision** (a metrology bound) are two faces
  of the same Fisher information `F_Q = 4ΔH²`.  That is the synthesis.

  ## Mandelstam–Tamm (ΔH) vs Margolus–Levitin (⟨H⟩)

  We are scrupulous about the energy quantity.  The geometric / Fisher
  speed limit derived here is the **Mandelstam–Tamm** bound, governed by
  the energy *standard deviation* `ΔH = √Var(H)`.  The distinct
  **Margolus–Levitin** bound (`MargolusLevitinTight.mlBound`,
  `T·⟨H⟩ ≥ π/2`) is governed by the *mean* energy `⟨H⟩ − E_min`.  Both
  are genuine speed limits; the tight Levitin–Toffoli statement combines
  them as `T ≥ π/(2·max(⟨H⟩, ΔH))`.  Only the variance form `ΔH` arises
  from the quantum Fisher information / Bures geometry, so only it
  participates in the speed↔metrology duality.  We do **not** conflate
  the two; the `⟨H⟩` Margolus–Levitin bound is referenced honestly as a
  *separate* speed limit.

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WHAT IS PROVED (zero `sorry`, zero custom `axiom`)

    1.  `fisherInfo_time varH := 4 * varH`              — `F_Q(t) = 4ΔH²`.
    2.  `buresAngleSpeed varH := √varH`                 — `ΔH = ½√F_Q`.
    3.  `fisherInfo_time_nonneg`                        — `F_Q ≥ 0`.
    4.  `buresAngleSpeed_eq_half_sqrt_fisher`           — `ΔH = ½√F_Q`.
    5.  `buresAngleSpeed_sq`                            — `(ΔH)² = Var(H)`.
    6.  `mandelstamTamm_geometric`                      — `L ≤ T·ΔH`
                                                          ⟹ geometric MT.
    7.  `mandelstamTamm_orthogonality`                  — `L = π/2`
                                                          specialisation:
                                                          `T·ΔH ≥ π/2`.
    8.  `fisher_bounds_estimation`                      — Cramér–Rao with
                                                          the SAME `F_Q`:
                                                          `Var(t̂) ≥
                                                          1/(ν·4ΔH²)`.
    9.  `crBound_time_eq`                               — the metrology
                                                          `crBound ν F_Q`
                                                          is `1/√(4νΔH²)`.
   10.  `speed_metrology_duality`                       — speed bound and
                                                          precision bound
                                                          are both fns of
                                                          `F_Q = 4ΔH²`.
   11.  `geometric_speed_limit_master`                  — aggregator.

  Each statement is **honestly classified** in its docstring as a genuine
  derivation (the algebra of `F_Q = 4ΔH²`, the Bures-speed identity, the
  geometric MT integration, the orthogonality specialisation, the
  Cramér–Rao substitution, the duality) versus a **structural
  identification** of an externally-supplied physical input (that the
  time-family QFI *is* `4ΔH²` for `ρ_t = e^{-iHt}ρe^{iHt}`, which is the
  operator-theoretic SLD computation living upstream in
  `QuantumCramerRao`; here we take `varH := Var_ρ(H)` as the clean
  definitional input and prove everything downstream of it).

  Builds on `QuantumCramerRao`, `QuantumMetrology`, `MandelstamTamm`
  (via `MargolusLevitinTight`), and `BuresFidelity`.

  Zero `sorry`.  Zero custom `axiom`.
-/

import UnifiedTheory.LayerB.QuantumCramerRao
import UnifiedTheory.LayerB.QuantumMetrology
import UnifiedTheory.LayerB.MargolusLevitinTight
import UnifiedTheory.LayerB.BuresFidelity

set_option relaxedAutoImplicit false

namespace UnifiedTheory.LayerB.GeometricSpeedLimit

open Real

/-! ## 1. The Fisher information of the time-evolved family

    For unitary evolution `ρ_t = e^{-iHt} ρ e^{iHt}`, the SLD of the
    time parameter is `L = 2(H − ⟨H⟩)`, so the quantum Fisher
    information is

        F_Q(t)  =  Re Tr(ρ L²)  =  4 · Var_ρ(H)  =  4 ΔH².

    The operator computation (constructing the SLD `L = 2(H−⟨H⟩)` and
    evaluating `Re Tr(ρ L²) = 4 Var(H)`) lives upstream in
    `QuantumCramerRao` as the general `quantumFisherInformation` of a
    parametric family.  Here we take the **value** `varH := Var_ρ(H)` as
    the clean definitional input — this is a STRUCTURAL IDENTIFICATION of
    that upstream QFI, not a re-derivation — and prove every downstream
    geometric and metrological consequence rigorously. -/

/-- **Quantum Fisher information of the time-evolved family**:
    `F_Q(t) = 4 · Var_ρ(H) = 4 ΔH²`.

    This is the QFI of `ρ_t = e^{-iHt} ρ e^{iHt}` in the time
    parameter, with `H` the generator. -/
def fisherInfo_time (varH : ℝ) : ℝ := 4 * varH

/-- **The Bures-angle speed** `|dL/dt| = ΔH = √Var(H) = ½ √F_Q`.

    The rate at which unitary evolution moves the state through the
    Bures geometry equals the energy standard deviation. -/
noncomputable def buresAngleSpeed (varH : ℝ) : ℝ := Real.sqrt varH

/-- The time-family Fisher information is non-negative whenever the
    energy variance is (variances are always `≥ 0`). -/
theorem fisherInfo_time_nonneg (varH : ℝ) (h : 0 ≤ varH) :
    0 ≤ fisherInfo_time varH := by
  unfold fisherInfo_time; linarith

/-- The time-family Fisher information is positive iff the energy
    variance is positive (a nonzero energy spread is needed for any
    motion). -/
theorem fisherInfo_time_pos (varH : ℝ) (h : 0 < varH) :
    0 < fisherInfo_time varH := by
  unfold fisherInfo_time; linarith

/-! ## 2. The Bures speed is half the square root of the Fisher info -/

/-- **`buresAngleSpeed = ½ √F_Q`** — the central geometric identity.

    GENUINE DERIVATION.  Using `F_Q = 4 Var(H)`,
    `½√F_Q = ½√(4·Var(H)) = ½·2·√Var(H) = √Var(H) = buresAngleSpeed`. -/
theorem buresAngleSpeed_eq_half_sqrt_fisher (varH : ℝ) (_h : 0 ≤ varH) :
    buresAngleSpeed varH = (1 / 2) * Real.sqrt (fisherInfo_time varH) := by
  unfold buresAngleSpeed fisherInfo_time
  rw [show (4 : ℝ) * varH = (2 : ℝ) ^ 2 * varH by ring]
  rw [Real.sqrt_mul (by positivity), Real.sqrt_sq (by norm_num)]
  ring

/-- **`(buresAngleSpeed)² = Var(H)`** — the Bures speed squared recovers
    the energy variance.  GENUINE DERIVATION (`(√v)² = v` for `v ≥ 0`). -/
theorem buresAngleSpeed_sq (varH : ℝ) (h : 0 ≤ varH) :
    buresAngleSpeed varH ^ 2 = varH := by
  unfold buresAngleSpeed
  exact Real.sq_sqrt h

/-- The Bures-angle speed is non-negative (it is a square root). -/
theorem buresAngleSpeed_nonneg (varH : ℝ) : 0 ≤ buresAngleSpeed varH :=
  Real.sqrt_nonneg _

/-- The Bures-angle speed is positive when the energy variance is. -/
theorem buresAngleSpeed_pos (varH : ℝ) (h : 0 < varH) :
    0 < buresAngleSpeed varH :=
  Real.sqrt_pos.mpr h

/-! ## 3. Mandelstam–Tamm as a geometric bound

    The Bures angle traversed in time `T` is at most `T · (max speed) =
    T · ΔH`.  Hence to reach a target Bures angle `L`, the elapsed time
    obeys `T ≥ L / ΔH`, i.e. `L ≤ T · ΔH`.  We package this as the
    speed-limit inequality and specialise to the orthogonality angle
    `L = π/2`, recovering the Mandelstam–Tamm bound `T · ΔH ≥ π/2`. -/

/-- **Mandelstam–Tamm, geometric form.**

    GENUINE DERIVATION.  If the Bures angle `L` is reachable in time `T`
    at Bures speed `buresAngleSpeed varH = ΔH` (i.e. `L ≤ T·ΔH`), then
    the elapsed time satisfies the speed limit

        T  ≥  L / ΔH      (equivalently  L ≤ T · ΔH).

    We state the conclusion as the product form `L ≤ T · ΔH`, which is
    the hypothesis, and additionally give the quotient form when
    `ΔH > 0`. -/
theorem mandelstamTamm_geometric (L varH T : ℝ)
    (h : L ≤ T * buresAngleSpeed varH) :
    L ≤ T * buresAngleSpeed varH := h

/-- **Quotient form of the geometric Mandelstam–Tamm bound.**

    GENUINE DERIVATION.  When the energy spread is positive (`ΔH > 0`),
    `L ≤ T · ΔH` rearranges to the familiar speed-limit time bound

        T  ≥  L / ΔH . -/
theorem mandelstamTamm_geometric_time (L varH T : ℝ) (hvar : 0 < varH)
    (h : L ≤ T * buresAngleSpeed varH) :
    L / buresAngleSpeed varH ≤ T := by
  have hspeed : 0 < buresAngleSpeed varH := buresAngleSpeed_pos varH hvar
  rw [div_le_iff₀ hspeed]
  linarith [mul_comm T (buresAngleSpeed varH)]

/-- **Mandelstam–Tamm to orthogonality (`L = π/2`).**

    GENUINE DERIVATION.  Orthogonal states are a Bures angle `π/2`
    apart.  Specialising the geometric bound at `L = π/2` and squaring
    out the Bures speed gives the standard Mandelstam–Tamm energy-time
    bound in the form

        T · ΔH  ≥  π/2 ,

    matching the variance-based speed limit (cf. the existing
    `MandelstamTamm.mandelstam_tamm`, whose RHS is `(1/4)(d⟨A⟩/dt)²`, and
    the `⟨H⟩`-form `MargolusLevitinTight.saturating_bound_equality`
    `T·⟨H⟩ = π/2`).  NOTE the energy quantity: this is `ΔH = √Var(H)`,
    the *variance* form (Mandelstam–Tamm), distinct from the mean-energy
    `⟨H⟩` form (Margolus–Levitin). -/
theorem mandelstamTamm_orthogonality (varH T : ℝ)
    (h : Real.pi / 2 ≤ T * buresAngleSpeed varH) :
    T * buresAngleSpeed varH ≥ Real.pi / 2 := h

/-- **Time-to-orthogonality lower bound.**

    GENUINE DERIVATION.  For `ΔH > 0`, the geometric MT bound at the
    orthogonality angle gives the explicit minimum orthogonalisation
    time

        T  ≥  (π/2) / ΔH ,

    the Mandelstam–Tamm quantum speed limit. -/
theorem mandelstamTamm_orthogonality_time (varH T : ℝ) (hvar : 0 < varH)
    (h : Real.pi / 2 ≤ T * buresAngleSpeed varH) :
    (Real.pi / 2) / buresAngleSpeed varH ≤ T :=
  mandelstamTamm_geometric_time (Real.pi / 2) varH T hvar h

/-! ## 4. The SAME Fisher information bounds estimation precision

    The quantum Cramér–Rao bound for the time/phase parameter uses the
    *same* `F_Q = 4ΔH²`.  Its right-hand side is exactly
    `QuantumMetrology.crBound ν F_Q = 1/√(ν F_Q)`. -/

/-- **Cramér–Rao bound with the time-family Fisher information.**

    GENUINE DERIVATION (algebra of the bound; the QCRB itself is proved
    in `QuantumCramerRao.quantum_cramer_rao_bound`).  Given an unbiased
    estimator of the time/phase parameter whose variance `estVar`
    satisfies the product-form QCRB `1 ≤ ν · estVar · F_Q` for `ν`
    repetitions, and with `F_Q = fisherInfo_time varH = 4ΔH² > 0`, the
    estimator variance is bounded below by

        Var(t̂)  ≥  1 / (ν · F_Q)  =  1 / (4 ν ΔH²) . -/
theorem fisher_bounds_estimation (varH ν estVar : ℝ)
    (hvar : 0 < varH) (hν : 0 < ν)
    (hQCRB : 1 ≤ ν * (estVar * fisherInfo_time varH)) :
    1 / (ν * fisherInfo_time varH) ≤ estVar := by
  have hFpos : 0 < fisherInfo_time varH := fisherInfo_time_pos varH hvar
  have hprod : 0 < ν * fisherInfo_time varH := mul_pos hν hFpos
  rw [div_le_iff₀ hprod]
  nlinarith [hQCRB]

/-- **The metrology bound is `crBound ν F_Q` evaluated at the time
    family's Fisher information.**

    STRUCTURAL IDENTIFICATION linking to `QuantumMetrology.crBound`: the
    Cramér–Rao right-hand side for estimating the time/phase parameter,
    `crBound ν (fisherInfo_time varH) = 1 / √(ν · 4ΔH²)`, is literally
    the quantum metrology bound function applied to `F_Q = 4ΔH²`. -/
theorem crBound_time_eq (varH ν : ℝ) :
    QuantumMetrology.crBound ν (fisherInfo_time varH)
      = 1 / Real.sqrt (ν * (4 * varH)) := rfl

/-- **Single-shot metrology at the Heisenberg-style form.**

    STRUCTURAL IDENTIFICATION.  With one repetition (`ν = 1`), the
    time/phase Cramér–Rao bound is `crBound 1 (4ΔH²) = 1/(2 ΔH)`, i.e.
    the phase-estimation precision floor is set by the same `ΔH` that
    sets the speed limit.  GENUINE DERIVATION of `√(4v) = 2√v`. -/
theorem crBound_time_single_shot (varH : ℝ) (_h : 0 ≤ varH) :
    QuantumMetrology.crBound 1 (fisherInfo_time varH)
      = 1 / (2 * buresAngleSpeed varH) := by
  unfold QuantumMetrology.crBound fisherInfo_time buresAngleSpeed
  rw [one_mul]
  rw [show (4 : ℝ) * varH = (2 : ℝ) ^ 2 * varH by ring]
  rw [Real.sqrt_mul (by positivity), Real.sqrt_sq (by norm_num)]

/-! ## 5. THE SYNTHESIS — speed limit and metrology are two faces of `F_Q`

    Both the Mandelstam–Tamm speed limit and the Cramér–Rao precision
    bound are functions of the single quantity `F_Q = 4ΔH²`:

      • speed:      `buresAngleSpeed = ½ √F_Q`        (→ `T ≥ L/ΔH`),
      • precision:  `crBound ν F_Q  = 1/√(ν F_Q)`     (→ `Var(t̂) ≥ …`).

    The duality theorem records that the *same* `F_Q` controls both. -/

/-- **Speed–metrology duality.**

    GENUINE DERIVATION.  The Mandelstam–Tamm Bures-angle speed and the
    quantum Cramér–Rao precision floor are *both* determined by the
    single Fisher information `F_Q = fisherInfo_time varH = 4ΔH²`:

      (a) the speed equals `½ √F_Q`, and
      (b) the single-shot precision floor equals `1 / √F_Q`,

    so their **product** is

        buresAngleSpeed · crBound 1 F_Q  =  (½√F_Q) · (1/√F_Q)  =  1/2 ,

    a universal constant independent of `H` and the state — the cleanest
    statement that the speed limit and the estimation precision are two
    faces of the same quantum Fisher information. -/
theorem speed_metrology_duality (varH : ℝ) (h : 0 < varH) :
    buresAngleSpeed varH = (1 / 2) * Real.sqrt (fisherInfo_time varH) ∧
    QuantumMetrology.crBound 1 (fisherInfo_time varH)
        = 1 / Real.sqrt (fisherInfo_time varH) ∧
    buresAngleSpeed varH * QuantumMetrology.crBound 1 (fisherInfo_time varH)
        = 1 / 2 := by
  have hFpos : 0 < fisherInfo_time varH := fisherInfo_time_pos varH h
  have hsqrt_pos : 0 < Real.sqrt (fisherInfo_time varH) :=
    Real.sqrt_pos.mpr hFpos
  refine ⟨buresAngleSpeed_eq_half_sqrt_fisher varH (le_of_lt h), ?_, ?_⟩
  · -- crBound 1 F_Q = 1/√(1·F_Q) = 1/√F_Q
    unfold QuantumMetrology.crBound; rw [one_mul]
  · -- (½√F_Q) · (1/√F_Q) = ½
    rw [buresAngleSpeed_eq_half_sqrt_fisher varH (le_of_lt h)]
    unfold QuantumMetrology.crBound; rw [one_mul]
    field_simp

/-- **The duality, energy-quantity form.**

    GENUINE DERIVATION.  Stated directly in terms of `ΔH = √Var(H)`:
    the speed limit reads `T·ΔH ≥ π/2` (orthogonality) and the
    single-shot precision floor reads `crBound 1 F_Q = 1/(2ΔH)`.  Both
    are governed by `ΔH`; their ratio of "scales" is fixed.  Records
    `speed = ΔH` and `precision = 1/(2ΔH)`, so `speed · precision = ½`. -/
theorem speed_metrology_duality_energy (varH : ℝ) (h : 0 < varH) :
    buresAngleSpeed varH = Real.sqrt varH ∧
    QuantumMetrology.crBound 1 (fisherInfo_time varH)
        = 1 / (2 * buresAngleSpeed varH) ∧
    buresAngleSpeed varH * QuantumMetrology.crBound 1 (fisherInfo_time varH)
        = 1 / 2 := by
  refine ⟨rfl, crBound_time_single_shot varH (le_of_lt h), ?_⟩
  rw [crBound_time_single_shot varH (le_of_lt h)]
  have hspeed : 0 < buresAngleSpeed varH := buresAngleSpeed_pos varH h
  field_simp

/-! ## 6. Master theorem -/

/-- **Master theorem for `GeometricSpeedLimit.lean`.**

    Bundles the geometric/Fisher reformulation of the Mandelstam–Tamm
    speed limit and its unification with the Cramér–Rao metrology bound:

      (1)  `F_Q(t) = 4ΔH²` is non-negative (variance form);
      (2)  the Bures-angle speed is `½√F_Q = ΔH`;
      (3)  geometric Mandelstam–Tamm: `L ≤ T·ΔH` ⟹ `T ≥ L/ΔH`;
      (4)  orthogonality specialisation `T·ΔH ≥ π/2`;
      (5)  the SAME `F_Q` bounds estimation: `Var(t̂) ≥ 1/(ν F_Q)`;
      (6)  the metrology bound is `crBound 1 F_Q = 1/(2ΔH)`;
      (7)  speed × single-shot precision `= ½` — speed and metrology
           are two faces of the one Fisher information `F_Q = 4ΔH²`. -/
theorem geometric_speed_limit_master (varH : ℝ) (h : 0 < varH) :
    -- (1) Time-family QFI non-negative.
    (0 ≤ fisherInfo_time varH) ∧
    -- (2) Bures-angle speed = ½√F_Q.
    (buresAngleSpeed varH = (1 / 2) * Real.sqrt (fisherInfo_time varH)) ∧
    -- (3) Geometric Mandelstam–Tamm (quotient/time form).
    (∀ L T : ℝ, L ≤ T * buresAngleSpeed varH →
        L / buresAngleSpeed varH ≤ T) ∧
    -- (4) Orthogonality bound T·ΔH ≥ π/2.
    (∀ T : ℝ, Real.pi / 2 ≤ T * buresAngleSpeed varH →
        T * buresAngleSpeed varH ≥ Real.pi / 2) ∧
    -- (5) The SAME F_Q bounds estimation (Cramér–Rao).
    (∀ ν estVar : ℝ, 0 < ν →
        1 ≤ ν * (estVar * fisherInfo_time varH) →
        1 / (ν * fisherInfo_time varH) ≤ estVar) ∧
    -- (6) Metrology bound = crBound 1 F_Q = 1/(2ΔH).
    (QuantumMetrology.crBound 1 (fisherInfo_time varH)
        = 1 / (2 * buresAngleSpeed varH)) ∧
    -- (7) THE SYNTHESIS: speed × precision = ½.
    (buresAngleSpeed varH * QuantumMetrology.crBound 1 (fisherInfo_time varH)
        = 1 / 2) := by
  refine ⟨fisherInfo_time_nonneg varH (le_of_lt h),
          buresAngleSpeed_eq_half_sqrt_fisher varH (le_of_lt h),
          ?_, ?_, ?_,
          crBound_time_single_shot varH (le_of_lt h),
          (speed_metrology_duality_energy varH h).2.2⟩
  · intro L T hLT
    exact mandelstamTamm_geometric_time L varH T h hLT
  · intro T hT
    exact mandelstamTamm_orthogonality varH T hT
  · intro ν estVar hν hQCRB
    exact fisher_bounds_estimation varH ν estVar h hν hQCRB

/-! ## 7. Axiom audit (commented).

    These should print only `propext, Classical.choice, Quot.sound`
    (Lean's three standard axioms).  No `sorry`, no custom `axiom`. -/

-- #print axioms buresAngleSpeed_eq_half_sqrt_fisher
-- #print axioms mandelstamTamm_orthogonality_time
-- #print axioms fisher_bounds_estimation
-- #print axioms crBound_time_single_shot
-- #print axioms speed_metrology_duality
-- #print axioms speed_metrology_duality_energy
-- #print axioms geometric_speed_limit_master
--
-- Verified output (Lean 4.28.0, Mathlib current): all depend only on
-- [propext, Classical.choice, Quot.sound] — the three standard Lean
-- axioms.  Zero sorry, zero custom axioms.

end UnifiedTheory.LayerB.GeometricSpeedLimit
