/-
  LayerB/OctonionsAlternative.lean — 𝕆 is an alternative algebra.

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  PURPOSE

  The octonions `𝕆` (constructed in `Octonions.lean`) are non-associative,
  but they satisfy the weaker ALTERNATIVE laws: any subalgebra generated by
  two elements is associative. Concretely,

      left :       x · (x · y) = (x · x) · y
      right :      (y · x) · x = y · (x · x)
      flexible :   (x · y) · x = x · (y · x).

  Alternativity is the precise algebraic strength of the octonions — it is
  what Artin's theorem characterizes, what makes inverses/division behave,
  and (with the composition norm) what places 𝕆 among the four normed
  division algebras ℝ, ℂ, ℍ, 𝕆. The next Cayley–Dickson double, the
  sedenions, loses even this.

  Each law is a polynomial identity in the 16 real components of x and y,
  so — exactly as for `onormSq_omul` — it is verified by expanding the
  Cayley–Dickson product into components and calling `ring`.

  WHAT IS PROVED (zero sorry, zero custom axioms)
   • `omul_left_alt`, `omul_right_alt`, `omul_flexible`.
   • `octonion_alternative` — the three laws bundled.

  Zero sorry. Zero custom axioms.
-/
import UnifiedTheory.LayerB.Octonions

set_option relaxedAutoImplicit false
set_option maxHeartbeats 1000000

namespace UnifiedTheory.LayerB.OctonionsAlternative

open UnifiedTheory.LayerB.Octonions

/-- **Left alternative law:** x·(x·y) = (x·x)·y. -/
theorem omul_left_alt (x y : Octonion) :
    omul x (omul x y) = omul (omul x x) y := by
  obtain ⟨a, b⟩ := x
  obtain ⟨c, d⟩ := y
  simp only [omul]
  ext <;>
    simp only [Quaternion.re_mul, Quaternion.imI_mul, Quaternion.imJ_mul,
               Quaternion.imK_mul, Quaternion.re_sub, Quaternion.imI_sub,
               Quaternion.imJ_sub, Quaternion.imK_sub, Quaternion.re_add,
               Quaternion.imI_add, Quaternion.imJ_add, Quaternion.imK_add,
               Quaternion.re_star, Quaternion.imI_star, Quaternion.imJ_star,
               Quaternion.imK_star] <;>
    ring

/-- **Right alternative law:** (y·x)·x = y·(x·x). -/
theorem omul_right_alt (x y : Octonion) :
    omul (omul y x) x = omul y (omul x x) := by
  obtain ⟨a, b⟩ := x
  obtain ⟨c, d⟩ := y
  simp only [omul]
  ext <;>
    simp only [Quaternion.re_mul, Quaternion.imI_mul, Quaternion.imJ_mul,
               Quaternion.imK_mul, Quaternion.re_sub, Quaternion.imI_sub,
               Quaternion.imJ_sub, Quaternion.imK_sub, Quaternion.re_add,
               Quaternion.imI_add, Quaternion.imJ_add, Quaternion.imK_add,
               Quaternion.re_star, Quaternion.imI_star, Quaternion.imJ_star,
               Quaternion.imK_star] <;>
    ring

/-- **Flexible law:** (x·y)·x = x·(y·x). -/
theorem omul_flexible (x y : Octonion) :
    omul (omul x y) x = omul x (omul y x) := by
  obtain ⟨a, b⟩ := x
  obtain ⟨c, d⟩ := y
  simp only [omul]
  ext <;>
    simp only [Quaternion.re_mul, Quaternion.imI_mul, Quaternion.imJ_mul,
               Quaternion.imK_mul, Quaternion.re_sub, Quaternion.imI_sub,
               Quaternion.imJ_sub, Quaternion.imK_sub, Quaternion.re_add,
               Quaternion.imI_add, Quaternion.imJ_add, Quaternion.imK_add,
               Quaternion.re_star, Quaternion.imI_star, Quaternion.imJ_star,
               Quaternion.imK_star] <;>
    ring

/-- **𝕆 IS AN ALTERNATIVE ALGEBRA.** The three alternative laws hold,
    completing the classical algebraic characterization of the constructed
    octonions: an 8-dimensional, non-commutative, non-associative,
    ALTERNATIVE composition/division algebra — the largest of the four
    normed division algebras over ℝ.

    Zero sorry. Zero custom axioms. -/
theorem octonion_alternative :
    (∀ x y : Octonion, omul x (omul x y) = omul (omul x x) y)
    ∧ (∀ x y : Octonion, omul (omul y x) x = omul y (omul x x))
    ∧ (∀ x y : Octonion, omul (omul x y) x = omul x (omul y x)) :=
  ⟨omul_left_alt, omul_right_alt, omul_flexible⟩

end UnifiedTheory.LayerB.OctonionsAlternative
