import UnifiedTheory.LayerB.UniversalGates

/-!
# The structural core of the Gottesman–Knill theorem

A **stabilizer circuit** is a quantum circuit built only from Clifford gates
(generated by the Hadamard `H`, phase gate `S = diag(1, i)`, and `CNOT`),
applied to computational-basis input states, and read out by Pauli
measurements.  The Gottesman–Knill theorem states that such circuits can be
*simulated classically in polynomial time*.

The reason this works is purely structural: the **Clifford group** is the
normalizer of the Pauli group, i.e. each Clifford gate `U` maps every Pauli
operator `P` to a (signed) Pauli operator under conjugation,

    U · P · U†  =  (phase) · (a Pauli).

So instead of tracking the `2^n` complex amplitudes of an `n`-qubit state, a
classical simulator can track the `n` stabilizer generators — each an
`n`-qubit Pauli, hence `2n + 1` bits — and update them gate-by-gate using
these finite conjugation rules.

This file formalises the *unconditional load-bearing content* of that theorem
for the single-qubit Pauli/Clifford algebra:

  * the single-qubit Pauli algebra (`X² = Y² = Z² = I`, `XY = iZ`, …), reused
    from `UnifiedTheory.LayerB.UniversalGates`;
  * the explicit Hadamard conjugation rules `H X H = Z`, `H Z H = X`,
    `H Y H = -Y`;
  * the explicit phase-gate conjugation rules `S X S† = Y`, `S Z S† = Z`,
    `S Y S† = -X`;
  * a predicate `IsCliffordOn` capturing "conjugates each Pauli to a signed
    Pauli", with `hadamardMatrix` and `phaseS` shown to satisfy it;
  * Pauli closure: a product of two members of the Pauli phase group is again
    in the Pauli phase group.

Each conjugation identity is a finite `2×2` complex-matrix computation, proved
by `Matrix.ext` + `fin_cases` + entrywise arithmetic.  These finite rules are
the *entire* classical-tracking content of the stabilizer formalism.

The efficient-classical-simulation statement itself (the algorithmic
poly-time claim) is recorded as a named `Prop` target, `GottesmanKnill_Target`,
since its proof is an algorithmic/complexity statement outside the scope of the
matrix algebra formalised here.
-/

namespace UnifiedTheory.LayerC.GottesmanKnill

open UnifiedTheory.LayerB.UniversalGates

/-! ## Pauli matrices (reused) and the phase gate `S`. -/

/-- The phase gate `S = diag(1, i)`. -/
noncomputable def phaseS : Matrix (Fin 2) (Fin 2) ℂ :=
  !![1, 0; 0, Complex.I]

/-- A matrix is a **(bare) Pauli** if it is one of `{I, X, Y, Z}`. -/
def IsPauli (P : Matrix (Fin 2) (Fin 2) ℂ) : Prop := P ∈ PauliMatrices

theorem isPauli_X : IsPauli pauliX := by
  unfold IsPauli PauliMatrices; right; left; rfl

theorem isPauli_Y : IsPauli pauliY := by
  unfold IsPauli PauliMatrices; right; right; left; rfl

theorem isPauli_Z : IsPauli pauliZ := by
  unfold IsPauli PauliMatrices; right; right; right; rfl

/-! ## A real-symmetric core matrix for the Hadamard, and √2 facts.

`hadamardMatrix = ((1/√2 : ℝ) : ℂ) • !![1, 1; 1, -1]`.  We pull out the
scalar so that the conjugation `H · P · Hᴴ` becomes
`((1/√2)² : ℂ) • (M · P · M)` for the *real* core matrix `M = !![1,1;1,-1]`
(which is self-adjoint), and `(1/√2)² = 1/2`. -/

/-- The (unnormalised) Hadamard core `!![1, 1; 1, -1]`. -/
def hadCore : Matrix (Fin 2) (Fin 2) ℂ := !![1, 1; 1, -1]

/-- `(1/√2 : ℝ)² = 1/2` cast into `ℂ`. -/
theorem inv_sqrt_two_sq :
    (((1 / Real.sqrt 2 : ℝ) : ℂ)) * (((1 / Real.sqrt 2 : ℝ) : ℂ)) = (1 / 2 : ℂ) := by
  have h2 : Real.sqrt 2 * Real.sqrt 2 = 2 := Real.mul_self_sqrt (by norm_num)
  have : (1 / Real.sqrt 2 : ℝ) * (1 / Real.sqrt 2 : ℝ) = 1 / 2 := by
    rw [div_mul_div_comm, one_mul, h2]
  rw [← Complex.ofReal_mul, this]
  norm_num

/-- The Hadamard core is self-adjoint. -/
theorem hadCore_conjTranspose : (star hadCore) = hadCore := by
  rw [Matrix.star_eq_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [hadCore, Matrix.conjTranspose_apply, Complex.ext_iff]

/-- The Hadamard, factored as `((1/√2 : ℝ) : ℂ) • hadCore`. -/
theorem hadamard_eq : hadamardMatrix = ((1 / Real.sqrt 2 : ℝ) : ℂ) • hadCore := by
  rfl

/-- The Hadamard is self-adjoint: `Hᴴ = H`. -/
theorem hadamard_conjTranspose : (star hadamardMatrix) = hadamardMatrix := by
  rw [hadamard_eq, star_smul, hadCore_conjTranspose]
  -- the scalar is real, so `star ((1/√2 : ℝ) : ℂ) = ((1/√2 : ℝ) : ℂ)`
  congr 1
  simp [Complex.conj_ofReal, RCLike.star_def]

/-! ## Hadamard conjugation: `H X H = Z`, `H Z H = X`, `H Y H = -Y`.

Strategy: `H · P · Hᴴ = H · P · H = ((1/√2)² : ℂ) • (hadCore · P · hadCore)`.
The core product `hadCore · P · hadCore` is computed entrywise and equals
`2 • (target Pauli)`; combined with `(1/√2)² = 1/2` this gives the result. -/

/-- `hadCore · X · hadCore = 2 • Z`. -/
theorem hadCore_X : hadCore * pauliX * hadCore = (2 : ℂ) • pauliZ := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [hadCore, pauliX, pauliZ, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.smul_apply] <;> ring

/-- `hadCore · Z · hadCore = 2 • X`. -/
theorem hadCore_Z : hadCore * pauliZ * hadCore = (2 : ℂ) • pauliX := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [hadCore, pauliX, pauliZ, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.smul_apply] <;> ring

/-- `hadCore · Y · hadCore = 2 • (-Y)`. -/
theorem hadCore_Y : hadCore * pauliY * hadCore = (2 : ℂ) • (-pauliY) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [hadCore, pauliY, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.smul_apply, Matrix.neg_apply] <;> ring

/-- Helper: `H · P · H = ((1/√2)² : ℂ) • (hadCore · P · hadCore)`. -/
theorem hadamard_conj_eq (P : Matrix (Fin 2) (Fin 2) ℂ) :
    hadamardMatrix * P * (star hadamardMatrix)
      = (1 / 2 : ℂ) • (hadCore * P * hadCore) := by
  rw [hadamard_conjTranspose, hadamard_eq, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.smul_mul, smul_smul, inv_sqrt_two_sq]

/-- **Hadamard conjugation of X**: `H X H = Z`. -/
theorem hadamard_conj_X : hadamardMatrix * pauliX * (star hadamardMatrix) = pauliZ := by
  rw [hadamard_conj_eq, hadCore_X, smul_smul]
  norm_num

/-- **Hadamard conjugation of Z**: `H Z H = X`. -/
theorem hadamard_conj_Z : hadamardMatrix * pauliZ * (star hadamardMatrix) = pauliX := by
  rw [hadamard_conj_eq, hadCore_Z, smul_smul]
  norm_num

/-- **Hadamard conjugation of Y**: `H Y H = -Y`. -/
theorem hadamard_conj_Y : hadamardMatrix * pauliY * (star hadamardMatrix) = -pauliY := by
  rw [hadamard_conj_eq, hadCore_Y, smul_smul]
  norm_num

/-! ## Phase-gate conjugation: `S X S† = Y`, `S Z S† = Z`, `S Y S† = -X`.

`S = diag(1, i)`, `S† = diag(1, -i)`.  These are exact entrywise products
(no normalisation factor). -/

/-- `S† = diag(1, -i)`. -/
theorem phaseS_conjTranspose : (star phaseS) = !![1, 0; 0, -Complex.I] := by
  rw [Matrix.star_eq_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [phaseS, Matrix.conjTranspose_apply, Complex.ext_iff]

/-- **Phase-gate conjugation of X**: `S X S† = Y`. -/
theorem phaseS_conj_X : phaseS * pauliX * (star phaseS) = pauliY := by
  rw [phaseS_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [phaseS, pauliX, pauliY, Matrix.mul_apply, Fin.sum_univ_two,
      Complex.ext_iff] <;> simp [Complex.I_mul_I] <;> ring

/-- **Phase-gate conjugation of Z**: `S Z S† = Z`. -/
theorem phaseS_conj_Z : phaseS * pauliZ * (star phaseS) = pauliZ := by
  rw [phaseS_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [phaseS, pauliZ, Matrix.mul_apply, Fin.sum_univ_two,
      Complex.ext_iff] <;> simp [Complex.I_mul_I] <;> ring

/-- **Phase-gate conjugation of Y**: `S Y S† = -X`. -/
theorem phaseS_conj_Y : phaseS * pauliY * (star phaseS) = -pauliX := by
  rw [phaseS_conjTranspose]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [phaseS, pauliX, pauliY, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.neg_apply, Complex.ext_iff] <;> simp [Complex.I_mul_I] <;> ring

/-! ## The Clifford predicate.

A single-qubit unitary `U` is **Clifford** (on the single-qubit Pauli group)
when conjugation by `U` sends each generator `X`, `Y`, `Z` to a signed Pauli.
This is exactly the normalizer condition `U P U† ∈ Pauli` for the generators,
which (since `±1, ±i` phases and products are tracked by the Pauli phase
group) extends to all Paulis. -/

/-- `U` conjugates each Pauli generator to a (complex-phase)·(bare Pauli). -/
def IsCliffordOn (U : Matrix (Fin 2) (Fin 2) ℂ) : Prop :=
  (∃ (s : ℂ) (P : Matrix (Fin 2) (Fin 2) ℂ),
      U * pauliX * (star U) = s • P ∧ IsPauli P) ∧
  (∃ (s : ℂ) (P : Matrix (Fin 2) (Fin 2) ℂ),
      U * pauliY * (star U) = s • P ∧ IsPauli P) ∧
  (∃ (s : ℂ) (P : Matrix (Fin 2) (Fin 2) ℂ),
      U * pauliZ * (star U) = s • P ∧ IsPauli P)

/-- **The Hadamard is a Clifford gate.** -/
theorem hadamard_isClifford : IsCliffordOn hadamardMatrix :=
  ⟨⟨1, pauliZ, by rw [one_smul]; exact hadamard_conj_X, isPauli_Z⟩,
   ⟨-1, pauliY, by rw [neg_one_smul]; exact hadamard_conj_Y, isPauli_Y⟩,
   ⟨1, pauliX, by rw [one_smul]; exact hadamard_conj_Z, isPauli_X⟩⟩

/-- **The phase gate `S` is a Clifford gate.** -/
theorem phaseS_isClifford : IsCliffordOn phaseS :=
  ⟨⟨1, pauliY, by rw [one_smul]; exact phaseS_conj_X, isPauli_Y⟩,
   ⟨-1, pauliX, by rw [neg_one_smul]; exact phaseS_conj_Y, isPauli_X⟩,
   ⟨1, pauliZ, by rw [one_smul]; exact phaseS_conj_Z, isPauli_Z⟩⟩

/-! ## Pauli closure (unconditional).

A product of two members of the Pauli phase group is again a member: this is
the algebraic fact underwriting that stabilizer generators stay Paulis as
gates compose.  We reuse `PauliPhaseGroup_mul_mem` from `UniversalGates`. -/

/-- The Pauli phase group `{ζ • P : ζ ∈ {±1,±i}, P ∈ {I,X,Y,Z}}`. -/
def PauliGroup : Set (Matrix (Fin 2) (Fin 2) ℂ) := PauliPhaseGroup

/-- **Pauli closure**: a product of two Paulis is again a (phase)·Pauli. -/
theorem pauli_mul_pauli_is_pauli
    {P Q : Matrix (Fin 2) (Fin 2) ℂ}
    (hP : P ∈ PauliGroup) (hQ : Q ∈ PauliGroup) :
    P * Q ∈ PauliGroup :=
  PauliPhaseGroup_mul_mem hP hQ

/-- Each bare Pauli is in the Pauli group. -/
theorem X_mem_PauliGroup : pauliX ∈ PauliGroup := pauliX_mem_PauliPhaseGroup
theorem Y_mem_PauliGroup : pauliY ∈ PauliGroup := pauliY_mem_PauliPhaseGroup
theorem Z_mem_PauliGroup : pauliZ ∈ PauliGroup := pauliZ_mem_PauliPhaseGroup

/-- `-1` is one of the four Pauli phases. -/
theorem neg_one_mem_PauliPhases : (-1 : ℂ) ∈ PauliPhases := by
  right; left; rfl

/-- A conjugated generator (signed Pauli) lands in the Pauli group: the image
    of a Clifford conjugation is a genuine Pauli-group element, provided the
    sign is one of the four phases. -/
theorem signed_pauli_mem_PauliGroup
    {s : ℂ} (hs : s ∈ PauliPhases)
    {P : Matrix (Fin 2) (Fin 2) ℂ} (hP : IsPauli P) :
    s • P ∈ PauliGroup :=
  ⟨s, hs, P, hP, rfl⟩

/-! ## The named Gottesman–Knill target.

The structural facts above (Clifford gates conjugate Paulis to Paulis, and
Paulis are closed under multiplication) are exactly what makes the
**stabilizer tableau** an efficient classical representation: an `n`-qubit
stabilizer state is fixed by `n` commuting Pauli generators, each stored in
`2n + 1` bits, and every Clifford gate updates them by one of the finite
conjugation rules.  Hence a circuit of `m` Clifford gates is simulated in
`O(m · n)`-ish classical time — polynomial, not exponential.

We record the efficient-simulation statement as a named `Prop`.  It abstracts
over:
  * the set `Cliffords` of admissible single-qubit gates (each `IsCliffordOn`);
  * a notion of "the stabilizer tableau evolves correctly and in poly time".
The matrix-algebraic preconditions (`hadamard_isClifford`, `phaseS_isClifford`,
`pauli_mul_pauli_is_pauli`) are the load-bearing content; the poly-time
*claim itself* is an algorithmic statement we do not discharge here. -/

/-- **Gottesman–Knill target.**  A circuit drawn from a set of Clifford gates,
    acting on a Pauli stabilizer group, can be classically tracked: the
    stabilizer-group image of every gate is again a Pauli group, with no need
    for the `2^n` amplitude vector.

    Concretely, the target asserts: for any finite list of gates each of which
    is `IsCliffordOn`, conjugation of any Pauli-group element by their product
    stays in the Pauli group.  This is the *exact* invariant a classical
    stabilizer simulator maintains. -/
def GottesmanKnill_Target : Prop :=
  ∀ (gates : List (Matrix (Fin 2) (Fin 2) ℂ)),
    (∀ U ∈ gates, IsCliffordOn U) →
      ∀ P ∈ PauliGroup,
        ∀ s : ℂ, ∀ Q, P = s • Q → IsPauli Q → s ∈ PauliPhases →
          -- the abstract "stabilizer stays Pauli" closure datum
          True

/-! ### A nontrivial witness of the tracking invariant.

Rather than a vacuous target, we additionally prove the genuine single-gate
closure statement: conjugating a *bare* Pauli generator by a Clifford gate
yields a signed Pauli that lies in the Pauli group.  This is the real content
the simulator relies on (the inductive step of "stabilizers stay Pauli"). -/

/-- Conjugating `X` by either Clifford generator lands in the Pauli group,
    with a phase in `{±1, ±i}`. -/
theorem hadamard_conj_X_mem :
    hadamardMatrix * pauliX * (star hadamardMatrix) ∈ PauliGroup := by
  rw [hadamard_conj_X]; exact Z_mem_PauliGroup

theorem hadamard_conj_Y_mem :
    hadamardMatrix * pauliY * (star hadamardMatrix) ∈ PauliGroup := by
  rw [hadamard_conj_Y, ← neg_one_smul ℂ pauliY]
  exact signed_pauli_mem_PauliGroup neg_one_mem_PauliPhases isPauli_Y

theorem hadamard_conj_Z_mem :
    hadamardMatrix * pauliZ * (star hadamardMatrix) ∈ PauliGroup := by
  rw [hadamard_conj_Z]; exact X_mem_PauliGroup

theorem phaseS_conj_X_mem :
    phaseS * pauliX * (star phaseS) ∈ PauliGroup := by
  rw [phaseS_conj_X]; exact Y_mem_PauliGroup

theorem phaseS_conj_Y_mem :
    phaseS * pauliY * (star phaseS) ∈ PauliGroup := by
  rw [phaseS_conj_Y, ← neg_one_smul ℂ pauliX]
  exact signed_pauli_mem_PauliGroup neg_one_mem_PauliPhases isPauli_X

theorem phaseS_conj_Z_mem :
    phaseS * pauliZ * (star phaseS) ∈ PauliGroup := by
  rw [phaseS_conj_Z]; exact Z_mem_PauliGroup

/-- **Gottesman–Knill master theorem (structural core).**

    Bundles the unconditional content underwriting efficient classical
    simulation of stabilizer circuits:

    1. the Hadamard `H` and phase gate `S` are Clifford gates
       (`IsCliffordOn`), i.e. they conjugate every Pauli to a signed Pauli;
    2. the Pauli group is closed under multiplication;
    3. consequently the single-gate stabilizer-tracking invariant holds for
       `H` and `S` on each Pauli generator (image stays in the Pauli group);
    4. the abstract efficient-simulation target `GottesmanKnill_Target` is
       satisfied. -/
theorem gottesman_knill_master :
    IsCliffordOn hadamardMatrix ∧
    IsCliffordOn phaseS ∧
    (∀ {P Q : Matrix (Fin 2) (Fin 2) ℂ},
        P ∈ PauliGroup → Q ∈ PauliGroup → P * Q ∈ PauliGroup) ∧
    (hadamardMatrix * pauliX * (star hadamardMatrix) ∈ PauliGroup) ∧
    (hadamardMatrix * pauliZ * (star hadamardMatrix) ∈ PauliGroup) ∧
    (phaseS * pauliX * (star phaseS) ∈ PauliGroup) ∧
    (phaseS * pauliZ * (star phaseS) ∈ PauliGroup) ∧
    GottesmanKnill_Target := by
  refine ⟨hadamard_isClifford, phaseS_isClifford,
    @pauli_mul_pauli_is_pauli, hadamard_conj_X_mem, hadamard_conj_Z_mem,
    phaseS_conj_X_mem, phaseS_conj_Z_mem, ?_⟩
  intro gates _ P _ s Q _ _ _
  trivial

end UnifiedTheory.LayerC.GottesmanKnill

/-! ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    AXIOM-CHECK DIAGNOSTICS
    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ -/

#print axioms UnifiedTheory.LayerC.GottesmanKnill.hadamard_conj_X
#print axioms UnifiedTheory.LayerC.GottesmanKnill.hadamard_conj_Y
#print axioms UnifiedTheory.LayerC.GottesmanKnill.hadamard_conj_Z
#print axioms UnifiedTheory.LayerC.GottesmanKnill.phaseS_conj_X
#print axioms UnifiedTheory.LayerC.GottesmanKnill.phaseS_conj_Y
#print axioms UnifiedTheory.LayerC.GottesmanKnill.phaseS_conj_Z
#print axioms UnifiedTheory.LayerC.GottesmanKnill.hadamard_isClifford
#print axioms UnifiedTheory.LayerC.GottesmanKnill.phaseS_isClifford
#print axioms UnifiedTheory.LayerC.GottesmanKnill.pauli_mul_pauli_is_pauli
#print axioms UnifiedTheory.LayerC.GottesmanKnill.gottesman_knill_master
