/-
  Audit/KFCausalSetRelationalChiralitySelection.lean

  A RELATIONAL SOURCE FOR THE MICROSCOPIC CHIRAL SIGN

  The complete harmonic causal-growth law still carries a binary chirality
  argument.  This file connects that argument to the independently constructed
  cubic relational pseudoscalar

      Xi = Im Tr(H₁ [H₂,H₃]) / 8.

  For nonzero Xi, the convention

      b(Xi) = -i sign(Xi)

  selects the microscopic quarter turn.  Equivalently, the reflection-odd
  source `h = -Xi` gives the endpoint energy

      E_Xi(y) = Xi y,

  whose unique minimizer on `|y| <= 1/2` is `y = -sign(Xi)/2`.  This agrees
  exactly with the previously derived cubic-chirality projectors.  Reflection
  sends `Xi` to `-Xi`, conjugates the phase, swaps the endpoint kernel, and
  preserves the combined source energy.

  This closes the finite algebraic sign bridge.  It does not prove that a
  preferred nonzero relational triple is generated by the microscopic growth
  dynamics, that the triple is refinement invariant, or that an infinite
  history spontaneously selects one of the reflected sectors.  At `Xi = 0`
  the energy is identically zero and no sign is selected.
-/

import UnifiedTheory.Audit.KFCausalSetMicroscopicSpectatorAction
import UnifiedTheory.Audit.KFOrientationPathQuantum

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFCausalSetRelationalChiralitySelection

noncomputable section

open scoped ComplexConjugate
open UnifiedTheory.Audit.KFOrientationCPChannelTower
open UnifiedTheory.Audit.KFOrientationHistoryRigidity
open UnifiedTheory.Audit.KFOrientationPathQuantum
open UnifiedTheory.Audit.KFOrientationHigherRankDecoherence
open UnifiedTheory.Audit.KFCausalSetBellCausality
open UnifiedTheory.Audit.KFCausalSetChiralDynamics
open UnifiedTheory.Audit.KFCausalSetMicroscopicSpectatorAction
open UnifiedTheory.Audit.KFCausalSetSequentialGrowth
open UnifiedTheory.Audit.KFOrientationGrowthDecoherence
open UnifiedTheory.Audit.KFOrientationInfiniteCylinderDecoherence

/-! ## 1. Relational profile triples and their pseudoscalar -/

/-- Three higher-rank profiles supplying the finite cubic orientation datum. -/
structure RelationalProfileTriple where
  p₁ : ℕ
  q₁ : ℕ
  r₁ : ℕ
  p₂ : ℕ
  q₂ : ℕ
  r₂ : ℕ
  p₃ : ℕ
  q₃ : ℕ
  r₃ : ℕ
  deriving DecidableEq

namespace RelationalProfileTriple

/-- Simultaneous outer reflection of all three profiles. -/
def reflection (data : RelationalProfileTriple) : RelationalProfileTriple where
  p₁ := data.r₁
  q₁ := data.q₁
  r₁ := data.p₁
  p₂ := data.r₂
  q₂ := data.q₂
  r₂ := data.p₂
  p₃ := data.r₃
  q₃ := data.q₃
  r₃ := data.p₃

/-- Real normalized cubic chirality `Im Tr(H₁[H₂,H₃])/8`. -/
def chirality (data : RelationalProfileTriple) : ℝ :=
  normalizedRelationalChirality
    data.p₁ data.q₁ data.r₁ data.p₂ data.q₂ data.r₂
    data.p₃ data.q₃ data.r₃

@[simp]
theorem reflection_reflection (data : RelationalProfileTriple) :
    data.reflection.reflection = data := by
  cases data
  rfl

theorem chirality_reflection (data : RelationalProfileTriple) :
    data.reflection.chirality = -data.chirality := by
  exact normalizedRelationalChirality_reflection
    data.p₁ data.q₁ data.r₁ data.p₂ data.q₂ data.r₂
    data.p₃ data.q₃ data.r₃

end RelationalProfileTriple

/-- The explicit nondegenerate positive cubic witness. -/
def positiveRelationalWitness : RelationalProfileTriple where
  p₁ := 1
  q₁ := 1
  r₁ := 1
  p₂ := 2
  q₂ := 2
  r₂ := 2
  p₃ := 2
  q₃ := 1
  r₃ := 1

/-- Its reflected negative-chirality partner. -/
def negativeRelationalWitness : RelationalProfileTriple :=
  positiveRelationalWitness.reflection

@[simp]
theorem positiveRelationalWitness_chirality :
    positiveRelationalWitness.chirality = 1 := by
  exact normalizedRelationalChirality_witness

@[simp]
theorem negativeRelationalWitness_chirality :
    negativeRelationalWitness.chirality = -1 := by
  rw [negativeRelationalWitness,
    RelationalProfileTriple.chirality_reflection,
    positiveRelationalWitness_chirality]

/-! ## 2. Nonzero chirality fixes the microscopic quarter turn -/

/-- Positive relational chirality selects microscopic sector `1` (`-i`),
while negative or zero chirality uses sector `0` (`+i`).  Only the nonzero
case is interpreted as physical selection below. -/
def relationalChiralitySector (xi : ℝ) : Fin 2 :=
  if 0 < xi then 1 else 0

@[simp]
theorem relationalChiralitySector_one :
    relationalChiralitySector 1 = 1 := by
  simp [relationalChiralitySector]

@[simp]
theorem relationalChiralitySector_neg_one :
    relationalChiralitySector (-1) = 0 := by
  simp [relationalChiralitySector]

/-- Away from the achiral locus, reflection exchanges the two microscopic
chirality sectors. -/
theorem relationalChiralitySector_neg (xi : ℝ) (hxi : xi ≠ 0) :
    relationalChiralitySector (-xi) =
      reflectedMicroscopicChirality (relationalChiralitySector xi) := by
  rcases lt_or_gt_of_ne hxi with hNegative | hPositive
  · have hNotPositive : ¬0 < xi := not_lt_of_ge (le_of_lt hNegative)
    have hReflectedPositive : 0 < -xi := neg_pos.mpr hNegative
    simp [relationalChiralitySector, hNotPositive, hReflectedPositive,
      reflectedMicroscopicChirality]
  · have hReflectedNotPositive : ¬0 < -xi := by linarith
    simp [relationalChiralitySector, hPositive, hReflectedNotPositive,
      reflectedMicroscopicChirality]

/-- Quarter-turn phase selected by a relational pseudoscalar. -/
def relationalChiralityPhase (xi : ℝ) : ℂ :=
  chiralMaximalEventPhase (relationalChiralitySector xi)

theorem relationalChiralityPhase_of_pos {xi : ℝ} (hxi : 0 < xi) :
    relationalChiralityPhase xi = -Complex.I := by
  simp [relationalChiralityPhase, relationalChiralitySector, hxi,
    chiralMaximalEventPhase]

theorem relationalChiralityPhase_of_neg {xi : ℝ} (hxi : xi < 0) :
    relationalChiralityPhase xi = Complex.I := by
  have hNotPositive : ¬0 < xi := not_lt_of_ge (le_of_lt hxi)
  simp [relationalChiralityPhase, relationalChiralitySector, hNotPositive,
    chiralMaximalEventPhase]

/-- Reflection complex-conjugates the selected quarter turn. -/
theorem relationalChiralityPhase_reflection (xi : ℝ) (hxi : xi ≠ 0) :
    relationalChiralityPhase (-xi) = star (relationalChiralityPhase xi) := by
  rcases lt_or_gt_of_ne hxi with hNegative | hPositive
  · rw [relationalChiralityPhase_of_neg hNegative,
      relationalChiralityPhase_of_pos (neg_pos.mpr hNegative)]
    simp
  · rw [relationalChiralityPhase_of_pos hPositive,
      relationalChiralityPhase_of_neg (by linarith)]
    simp

theorem positiveWitness_selectedPhase :
    relationalChiralityPhase positiveRelationalWitness.chirality =
      -Complex.I := by
  rw [positiveRelationalWitness_chirality]
  exact relationalChiralityPhase_of_pos (by norm_num)

theorem negativeWitness_selectedPhase :
    relationalChiralityPhase negativeRelationalWitness.chirality =
      Complex.I := by
  rw [negativeRelationalWitness_chirality]
  exact relationalChiralityPhase_of_neg (by norm_num)

/-! ## 3. The cubic pseudoscalar is exactly the missing odd source -/

/-- Source convention aligning the cubic witness with the previously selected
orientation projector: `h = -Xi`. -/
def relationalChiralitySource (data : RelationalProfileTriple) : ℝ :=
  -data.chirality

theorem relationalChiralitySource_reflection (data : RelationalProfileTriple) :
    relationalChiralitySource data.reflection =
      -relationalChiralitySource data := by
  rw [relationalChiralitySource, relationalChiralitySource,
    RelationalProfileTriple.chirality_reflection]

/-- Source energy induced by the relational cubic invariant. -/
def relationalChiralityEnergy
    (data : RelationalProfileTriple) (y : ℝ) : ℝ :=
  chiralitySourceEnergy (relationalChiralitySource data) y

theorem relationalChiralityEnergy_formula
    (data : RelationalProfileTriple) (y : ℝ) :
    relationalChiralityEnergy data y = data.chirality * y := by
  unfold relationalChiralityEnergy relationalChiralitySource
    chiralitySourceEnergy
  ring

/-- Reflecting both relational geometry and the orientation parameter preserves
the source energy. -/
theorem relationalChiralityEnergy_combined_reflection
    (data : RelationalProfileTriple) (y : ℝ) :
    relationalChiralityEnergy data.reflection (-y) =
      relationalChiralityEnergy data y := by
  rw [relationalChiralityEnergy_formula,
    relationalChiralityEnergy_formula,
    RelationalProfileTriple.chirality_reflection]
  ring

/-- Positive cubic chirality uniquely selects `y=-1/2`. -/
theorem positive_relational_chirality_unique_minimizer
    {data : RelationalProfileTriple} {y : ℝ}
    (hPositive : 0 < data.chirality)
    (hy : IsAdmissibleOrientationParameter y) :
    relationalChiralityEnergy data (-1 / 2) ≤
        relationalChiralityEnergy data y
      ∧ (relationalChiralityEnergy data y =
          relationalChiralityEnergy data (-1 / 2) ↔ y = -1 / 2) := by
  rw [relationalChiralityEnergy_formula,
    relationalChiralityEnergy_formula]
  unfold IsAdmissibleOrientationParameter at hy
  have hLower : -(1 / 2 : ℝ) ≤ y := (abs_le.mp hy).1
  constructor
  · nlinarith
  · constructor
    · intro hEqual
      nlinarith
    · rintro rfl
      rfl

/-- Negative cubic chirality uniquely selects `y=+1/2`. -/
theorem negative_relational_chirality_unique_minimizer
    {data : RelationalProfileTriple} {y : ℝ}
    (hNegative : data.chirality < 0)
    (hy : IsAdmissibleOrientationParameter y) :
    relationalChiralityEnergy data (1 / 2) ≤
        relationalChiralityEnergy data y
      ∧ (relationalChiralityEnergy data y =
          relationalChiralityEnergy data (1 / 2) ↔ y = 1 / 2) := by
  rw [relationalChiralityEnergy_formula,
    relationalChiralityEnergy_formula]
  unfold IsAdmissibleOrientationParameter at hy
  have hUpper : y ≤ (1 / 2 : ℝ) := (abs_le.mp hy).2
  constructor
  · nlinarith
  · constructor
    · intro hEqual
      nlinarith
    · rintro rfl
      rfl

/-- The achiral locus supplies no source and leaves every admissible orientation
energetically degenerate. -/
theorem zero_relational_chirality_no_selection
    {data : RelationalProfileTriple} (hZero : data.chirality = 0) :
    relationalChiralitySource data = 0
      ∧ ∀ y : ℝ, relationalChiralityEnergy data y = 0 := by
  constructor
  · simp [relationalChiralitySource, hZero]
  · intro y
    rw [relationalChiralityEnergy_formula, hZero, zero_mul]

/-! ## 4. Exact endpoint and growth-law bridge -/

/-- Endpoint parameter selected by the sign of the cubic relational datum. -/
def relationallySelectedOrientationParameter
    (data : RelationalProfileTriple) : ℝ :=
  chiralBoundaryOrientationParameter
    (relationalChiralitySector data.chirality)

theorem relationallySelectedOrientationParameter_of_pos
    {data : RelationalProfileTriple} (hPositive : 0 < data.chirality) :
    relationallySelectedOrientationParameter data = -1 / 2 := by
  simp [relationallySelectedOrientationParameter,
    relationalChiralitySector, hPositive,
    chiralBoundaryOrientationParameter, chiralMaximalEventPhase]

theorem relationallySelectedOrientationParameter_of_neg
    {data : RelationalProfileTriple} (hNegative : data.chirality < 0) :
    relationallySelectedOrientationParameter data = 1 / 2 := by
  have hNotPositive : ¬0 < data.chirality :=
    not_lt_of_ge (le_of_lt hNegative)
  simp [relationallySelectedOrientationParameter,
    relationalChiralitySector, hNotPositive,
    chiralBoundaryOrientationParameter, chiralMaximalEventPhase]

/-- Pure endpoint kernel chosen by the relational chirality sign. -/
def relationallySelectedOrientationKernel
    (data : RelationalProfileTriple) : SquareMatrix 2 :=
  balancedHistoryKernel (relationallySelectedOrientationParameter data)

theorem relationallySelectedOrientationKernel_of_pos
    {data : RelationalProfileTriple} (hPositive : 0 < data.chirality) :
    relationallySelectedOrientationKernel data =
      positiveOrientationProjector := by
  rw [relationallySelectedOrientationKernel,
    relationallySelectedOrientationParameter_of_pos hPositive]
  exact balancedHistoryKernel_negativeEndpoint

theorem relationallySelectedOrientationKernel_of_neg
    {data : RelationalProfileTriple} (hNegative : data.chirality < 0) :
    relationallySelectedOrientationKernel data =
      negativeOrientationProjector := by
  rw [relationallySelectedOrientationKernel,
    relationallySelectedOrientationParameter_of_neg hNegative]
  exact balancedHistoryKernel_positiveEndpoint

/-- Reflection swaps the selected endpoint exactly. -/
theorem relationallySelectedOrientationKernel_reflection
    (data : RelationalProfileTriple) (hNonzero : data.chirality ≠ 0) :
    pathHistoryReflection (relationallySelectedOrientationKernel data) =
      relationallySelectedOrientationKernel data.reflection := by
  unfold relationallySelectedOrientationKernel
    relationallySelectedOrientationParameter
  rw [chiralBoundaryOrientationKernel_reflection,
    RelationalProfileTriple.chirality_reflection,
    relationalChiralitySector_neg data.chirality hNonzero]

theorem positiveWitness_kernel_agrees_with_cubic_projector :
    relationallySelectedOrientationKernel positiveRelationalWitness =
      chiralitySelectedProjector 1 1 1 2 2 2 2 1 1 := by
  rw [relationallySelectedOrientationKernel_of_pos (by simp),
    chiralitySelectedProjector_witness]

theorem negativeWitness_kernel_agrees_with_cubic_projector :
    relationallySelectedOrientationKernel negativeRelationalWitness =
      chiralitySelectedProjector 1 1 1 2 2 2 1 1 2 := by
  rw [relationallySelectedOrientationKernel_of_neg (by simp),
    chiralitySelectedProjector_reflected_witness]

/-- The previously complete harmonic law with its chirality argument supplied
by the sign of the relational cubic invariant. -/
def relationallySelectedCausalSetGrowthLaw
    (action : VacuumSpectatorCausalAction)
    (data : RelationalProfileTriple) :
    RankedNormalizedComplexGrowthLaw CausalSetGrowthBranch :=
  microscopicSpectatorCausalSetGrowthLaw action
    (relationalChiralitySector data.chirality)

theorem relationallySelectedGrowth_stronglyPositive
    (action : VacuumSpectatorCausalAction)
    (data : RelationalProfileTriple) :
    IsStronglyPositiveGrowthFunctional
      (infiniteRankedCylinderDecoherence
        (relationallySelectedCausalSetGrowthLaw action data)) := by
  exact (microscopicSpectatorGrowth_projective_stronglyPositive
    action (relationalChiralitySector data.chirality)).2.2.2.1

/-- Capstone: every nonzero cubic relational orientation fixes a quarter turn,
the matching pure endpoint and its unique source-energy minimum, while the
resulting complete infinite-cylinder law remains strongly positive. -/
theorem relational_chirality_supplies_complete_sign_law
    (action : VacuumSpectatorCausalAction)
    (data : RelationalProfileTriple)
    (hNonzero : data.chirality ≠ 0) :
    ((0 < data.chirality
        ∧ relationalChiralityPhase data.chirality = -Complex.I
        ∧ relationallySelectedOrientationParameter data = -1 / 2
        ∧ ∀ y, IsAdmissibleOrientationParameter y →
            relationalChiralityEnergy data (-1 / 2) ≤
                relationalChiralityEnergy data y
              ∧ (relationalChiralityEnergy data y =
                  relationalChiralityEnergy data (-1 / 2) ↔ y = -1 / 2))
      ∨ (data.chirality < 0
        ∧ relationalChiralityPhase data.chirality = Complex.I
        ∧ relationallySelectedOrientationParameter data = 1 / 2
        ∧ ∀ y, IsAdmissibleOrientationParameter y →
            relationalChiralityEnergy data (1 / 2) ≤
                relationalChiralityEnergy data y
              ∧ (relationalChiralityEnergy data y =
                  relationalChiralityEnergy data (1 / 2) ↔ y = 1 / 2)))
      ∧ IsStronglyPositiveGrowthFunctional
          (infiniteRankedCylinderDecoherence
            (relationallySelectedCausalSetGrowthLaw action data))
      ∧ pathHistoryReflection
          (relationallySelectedOrientationKernel data) =
            relationallySelectedOrientationKernel data.reflection := by
  constructor
  · rcases lt_or_gt_of_ne hNonzero with hNegative | hPositive
    · exact Or.inr ⟨hNegative,
        relationalChiralityPhase_of_neg hNegative,
        relationallySelectedOrientationParameter_of_neg hNegative,
        fun _y hy =>
          negative_relational_chirality_unique_minimizer hNegative hy⟩
    · exact Or.inl ⟨hPositive,
        relationalChiralityPhase_of_pos hPositive,
        relationallySelectedOrientationParameter_of_pos hPositive,
        fun _y hy =>
          positive_relational_chirality_unique_minimizer hPositive hy⟩
  · exact ⟨relationallySelectedGrowth_stronglyPositive action data,
      relationallySelectedOrientationKernel_reflection data hNonzero⟩

#print axioms RelationalProfileTriple.chirality_reflection
#print axioms relationalChiralitySector_neg
#print axioms relationalChiralityPhase_reflection
#print axioms relationalChiralityEnergy_combined_reflection
#print axioms positive_relational_chirality_unique_minimizer
#print axioms zero_relational_chirality_no_selection
#print axioms relationallySelectedOrientationKernel_reflection
#print axioms positiveWitness_kernel_agrees_with_cubic_projector
#print axioms relationallySelectedGrowth_stronglyPositive
#print axioms relational_chirality_supplies_complete_sign_law

end

end UnifiedTheory.Audit.KFCausalSetRelationalChiralitySelection
