/-
  Audit/KFCausalNerveHolonomy.lean
  — FLAT COCHAINS ON A DECLARED 2-COMPLEX: HOLONOMY IS A FUNCTION OF HOMOLOGY

  Companion to KFCausalAharonovBohm.lean and scripts/ab_thickened_antichain.py.
  The numerics put an AB cochain on the nerve of a thickened antichain and
  find, in a mesoscale window, that it is flat on every declared triangle and
  winds once around the single H₁ generator.  This file supplies the theorem
  that makes "holonomy of the generator" well defined there.

  Setting: vertices `V`, a set `T` of declared triangles (the 2-cells — e.g.
  triples of nerve vertices with a common shadow element), and an
  antisymmetric 1-cochain `U : V → V → K` valued in an additive commutative
  group `K` (for U(1) take `K = AddCircle`, `Additive Circle`, or `ℝ` for the
  lifted phase).  Integer 1-chains are `V × V →₀ ℤ`.

  * `hol` — holonomy as an additive map on 1-chains.
  * `hol_boundary` — a flat cochain has zero holonomy on the boundary subgroup
    `B` generated by declared triangle boundaries and edge-reversal pairs.
  * `hol_homologous` — **homologous chains have equal holonomy**: `hol`
    factors through chains / B, so on cycles it descends to H₁ of the declared
    complex.  (Flatness is used only on declared triangles: a nerve whose
    triangles all have zero winding gives a well-defined holonomy class map.)
  * `hol_gauge` / `hol_gauge_cycle` — changing `U` by a vertex coboundary
    `g a - g b` changes `hol c` by `⟨g, ∂c⟩`, hence not at all on cycles.
  * `hol_nsmul_generator` — if every cycle is homologous to `k·z` then its
    holonomy is `k • hol z`: with H₁ = ℤ the whole AB content is one number,
    the generator's holonomy (Φ in the numerics, winding ±1).

  Zero sorry.  Zero custom axioms.
-/
import Mathlib

set_option autoImplicit false
set_option linter.unusedSectionVars false

namespace UnifiedTheory.Audit.KFCausalNerveHolonomy

variable {V : Type*} [DecidableEq V] {K : Type*} [AddCommGroup K]

/-- Integer 1-chains on ordered vertex pairs. -/
abbrev Chain (V : Type*) := V × V →₀ ℤ

/-- Holonomy of a cochain, extended additively to chains. -/
noncomputable def hol (U : V → V → K) : Chain V →+ K :=
  Finsupp.liftAddHom fun e => zmultiplesHom K (U e.1 e.2)

@[simp] theorem hol_single (U : V → V → K) (a b : V) (k : ℤ) :
    hol U (Finsupp.single (a, b) k) = k • U a b := by
  simp [hol]

/-- The boundary of the triangle `(a,b,c)`, as the chain `ab + bc + ca`. -/
noncomputable def triBd (a b c : V) : Chain V :=
  Finsupp.single (a, b) 1 + Finsupp.single (b, c) 1 + Finsupp.single (c, a) 1

/-- An edge together with its reversal. -/
noncomputable def revPair (a b : V) : Chain V :=
  Finsupp.single (a, b) 1 + Finsupp.single (b, a) 1

/-- The boundary subgroup of the declared 2-complex. -/
noncomputable def boundaries (T : Set (V × V × V)) : AddSubgroup (Chain V) :=
  AddSubgroup.closure
    ({x | ∃ t ∈ T, x = triBd t.1 t.2.1 t.2.2} ∪ {x | ∃ a b : V, x = revPair a b})

/-- Antisymmetry and flatness on the declared triangles. -/
structure FlatOn (U : V → V → K) (T : Set (V × V × V)) : Prop where
  antisymm : ∀ a b, U b a = -U a b
  flat : ∀ t ∈ T, U t.1 t.2.1 + U t.2.1 t.2.2 = U t.1 t.2.2

theorem hol_boundary (U : V → V → K) (T : Set (V × V × V)) (hU : FlatOn U T) :
    ∀ x ∈ boundaries T, hol U x = 0 := by
  intro x hx
  have : boundaries T ≤ (hol U).ker := by
    apply (AddSubgroup.closure_le _).2
    rintro y (⟨t, ht, rfl⟩ | ⟨a, b, rfl⟩)
    · show hol U (triBd _ _ _) = 0
      simp only [triBd, map_add, hol_single, one_smul]
      rw [hU.antisymm t.1 t.2.2, ← hU.flat t ht]
      abel
    · show hol U (revPair _ _) = 0
      simp only [revPair, map_add, hol_single, one_smul]
      rw [hU.antisymm a b]
      abel
  exact this hx

/-- **Homologous chains have equal holonomy.** -/
theorem hol_homologous (U : V → V → K) (T : Set (V × V × V)) (hU : FlatOn U T)
    (c₁ c₂ : Chain V) (h : c₁ - c₂ ∈ boundaries T) :
    hol U c₁ = hol U c₂ := by
  have := hol_boundary U T hU _ h
  rw [map_sub, sub_eq_zero] at this
  exact this

/-- The vertex boundary `∂(a,b) = a − b`. -/
noncomputable def bd : Chain V →+ (V →₀ ℤ) :=
  Finsupp.liftAddHom fun e =>
    zmultiplesHom (V →₀ ℤ) (Finsupp.single e.1 1 - Finsupp.single e.2 1)

/-- Pairing of a vertex function with a 0-chain. -/
noncomputable def pair (g : V → K) : (V →₀ ℤ) →+ K :=
  Finsupp.liftAddHom fun v => zmultiplesHom K (g v)

@[simp] theorem bd_single (a b : V) (k : ℤ) :
    bd (Finsupp.single (a, b) k) = k • (Finsupp.single a 1 - Finsupp.single b 1) := by
  simp [bd]

@[simp] theorem pair_single (g : V → K) (v : V) (k : ℤ) :
    pair g (Finsupp.single v k) = k • g v := by
  simp [pair]

/-- **Gauge covariance**: a vertex coboundary shifts holonomy by `⟨g, ∂c⟩`. -/
theorem hol_gauge (U : V → V → K) (g : V → K) (c : Chain V) :
    hol (fun a b => U a b + (g a - g b)) c = hol U c + pair g (bd c) := by
  have : hol (fun a b => U a b + (g a - g b)) = hol U + (pair g).comp bd := by
    apply Finsupp.addHom_ext
    rintro ⟨a, b⟩ k
    simp only [AddMonoidHom.add_apply, AddMonoidHom.comp_apply, hol_single, bd_single,
      map_zsmul, map_sub, pair_single, one_smul, smul_add, smul_sub]
  rw [this]
  rfl

/-- On cycles (`∂c = 0`) holonomy is gauge invariant. -/
theorem hol_gauge_cycle (U : V → V → K) (g : V → K) (c : Chain V) (hc : bd c = 0) :
    hol (fun a b => U a b + (g a - g b)) c = hol U c := by
  rw [hol_gauge, hc, map_zero, add_zero]

/-- With H₁ generated by one cycle `z`, every cycle homologous to `k·z` has
holonomy `k • hol z`: the AB content of a flat cochain is the single number
`hol z`. -/
theorem hol_nsmul_generator (U : V → V → K) (T : Set (V × V × V)) (hU : FlatOn U T)
    (z c : Chain V) (k : ℤ) (h : c - k • z ∈ boundaries T) :
    hol U c = k • hol U z := by
  rw [hol_homologous U T hU c (k • z) h, map_zsmul]

end UnifiedTheory.Audit.KFCausalNerveHolonomy
