/-
  Audit/KFCausalDiamondDirectionCover.lean

  CAUSAL DIRECTIONS FROM COMMUTING DIAMONDS

  This file reconstructs a coordinate-free local direction type from a
  partial order. Its points are Hasse cover edges, quotiented by the
  equivalence relation generated by identifying opposite sides of causal
  diamonds. Every order isomorphism induces a direction equivalence, and the
  induced transport preserves identities and composition.

  On the elementary Boolean three-cube the quotient is proved to have exactly
  three classes. Thus the previous three-sheet carrier can be obtained from
  causal diamond geometry without choosing coordinate labels.

  The file deliberately separates two remaining claims:

  * no theorem here proves that every regular causal/CSpec neighborhood has
    exactly three diamond-direction classes;
  * no theorem here produces a nontrivial path-comparison holonomy witness.

  Zero sorry. Zero custom axioms.
-/

import Mathlib.Order.Cover
import Mathlib.Logic.Relation
import UnifiedTheory.Audit.KFCausalProduct3SheetBridge

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFCausalDiamondDirectionCover

noncomputable section

open UnifiedTheory.Audit.KFCausalProduct3SheetBridge

universe u v w

/-! ## 1. Intrinsic Hasse edges and commuting diamonds -/

/-- An oriented edge of the Hasse diagram of a partial order. -/
structure CausalCoverEdge (P : Type u) [PartialOrder P] where
  lower : P
  upper : P
  covBy : lower ⋖ upper

namespace CausalCoverEdge

variable {P : Type u} [PartialOrder P]

@[ext]
theorem ext {first second : CausalCoverEdge P}
    (hLower : first.lower = second.lower)
    (hUpper : first.upper = second.upper) : first = second := by
  cases first
  cases second
  simp_all

/-- Order isomorphisms transport Hasse edges. -/
def map {Q : Type v} [PartialOrder Q] (equiv : P ≃o Q) :
    CausalCoverEdge P → CausalCoverEdge Q :=
  fun edge =>
    { lower := equiv edge.lower
      upper := equiv edge.upper
      covBy := (apply_covBy_apply_iff equiv).2 edge.covBy }

@[simp]
theorem map_refl (edge : CausalCoverEdge P) :
    map (OrderIso.refl P) edge = edge := by
  ext <;> rfl

@[simp]
theorem map_trans {Q : Type v} {R : Type w}
    [PartialOrder Q] [PartialOrder R]
    (first : P ≃o Q) (second : Q ≃o R) (edge : CausalCoverEdge P) :
    map (first.trans second) edge = map second (map first edge) := by
  ext <;> rfl

@[simp]
theorem map_symm_apply {Q : Type v} [PartialOrder Q]
    (equiv : P ≃o Q) (edge : CausalCoverEdge P) :
    map equiv.symm (map equiv edge) = edge := by
  ext <;> simp [map]

end CausalCoverEdge

/-- Two Hasse edges are opposite sides of a commuting causal diamond. The
first edge is the lower-left side and the second the upper-right side; the
equivalence closure below forgets this presentation and makes the relation
symmetric. -/
def OppositeInCausalDiamond {P : Type u} [PartialOrder P]
    (first second : CausalCoverEdge P) : Prop :=
  first.lower ⋖ second.lower
    ∧ first.upper ⋖ second.upper
    ∧ first.upper ≠ second.lower

/-- The equivalence relation generated by opposite-diamond moves. -/
abbrev SameCausalDirection {P : Type u} [PartialOrder P] :=
  Relation.EqvGen (@OppositeInCausalDiamond P _)

/-- Intrinsic causal directions: Hasse edges modulo opposite sides of
commuting diamonds. -/
def LocalCausalDirection (P : Type u) [PartialOrder P] :=
  Quotient (Relation.EqvGen.setoid (@OppositeInCausalDiamond P _))

/-! ## 2. Direction transport is functorial -/

theorem oppositeInCausalDiamond_map {P : Type u} {Q : Type v}
    [PartialOrder P] [PartialOrder Q]
    (equiv : P ≃o Q) {first second : CausalCoverEdge P}
    (hOpposite : OppositeInCausalDiamond first second) :
    OppositeInCausalDiamond
      (CausalCoverEdge.map equiv first)
      (CausalCoverEdge.map equiv second) := by
  rcases hOpposite with ⟨hLower, hUpper, hDistinct⟩
  exact ⟨(apply_covBy_apply_iff equiv).2 hLower,
    (apply_covBy_apply_iff equiv).2 hUpper,
    fun hEqual => hDistinct (equiv.injective hEqual)⟩

theorem sameCausalDirection_map {P : Type u} {Q : Type v}
    [PartialOrder P] [PartialOrder Q]
    (equiv : P ≃o Q) {first second : CausalCoverEdge P}
    (hSame : SameCausalDirection first second) :
    SameCausalDirection
      (CausalCoverEdge.map equiv first)
      (CausalCoverEdge.map equiv second) := by
  induction hSame with
  | rel first second hRel =>
      exact Relation.EqvGen.rel _ _
        (oppositeInCausalDiamond_map equiv hRel)
  | refl edge => exact Relation.EqvGen.refl _
  | symm first second _ ih => exact Relation.EqvGen.symm _ _ ih
  | trans first middle second _ _ hFirst hSecond =>
      exact Relation.EqvGen.trans _ _ _ hFirst hSecond

/-- Every order isomorphism induces an equivalence of intrinsic direction
types. -/
def transportLocalCausalDirection {P : Type u} {Q : Type v}
    [PartialOrder P] [PartialOrder Q] (equiv : P ≃o Q) :
    LocalCausalDirection P ≃ LocalCausalDirection Q where
  toFun := Quotient.map (CausalCoverEdge.map equiv)
    (fun _ _ h => sameCausalDirection_map equiv h)
  invFun := Quotient.map (CausalCoverEdge.map equiv.symm)
    (fun _ _ h => sameCausalDirection_map equiv.symm h)
  left_inv direction := by
    refine Quotient.inductionOn direction ?_
    intro edge
    apply Quotient.sound
    rw [CausalCoverEdge.map_symm_apply]
    exact Relation.EqvGen.refl _
  right_inv direction := by
    refine Quotient.inductionOn direction ?_
    intro edge
    apply Quotient.sound
    have hMap :
        CausalCoverEdge.map equiv
            (CausalCoverEdge.map equiv.symm edge) = edge := by
      ext <;> simp [CausalCoverEdge.map]
    rw [hMap]
    exact Relation.EqvGen.refl _

@[simp]
theorem transportLocalCausalDirection_refl {P : Type u} [PartialOrder P] :
    transportLocalCausalDirection (OrderIso.refl P) =
      Equiv.refl (LocalCausalDirection P) := by
  apply Equiv.ext
  intro direction
  refine Quotient.inductionOn direction ?_
  intro edge
  rfl

@[simp]
theorem transportLocalCausalDirection_trans
    {P : Type u} {Q : Type v} {R : Type w}
    [PartialOrder P] [PartialOrder Q] [PartialOrder R]
    (first : P ≃o Q) (second : Q ≃o R) :
    transportLocalCausalDirection (first.trans second) =
      (transportLocalCausalDirection first).trans
        (transportLocalCausalDirection second) := by
  apply Equiv.ext
  intro direction
  refine Quotient.inductionOn direction ?_
  intro edge
  rfl

/-! ## 3. Exact computation on the elementary Boolean three-cube -/

abbrev Cube3CoverEdge := CausalCoverEdge TangentCube3

/-- The unique coordinate inserted by a Boolean-cube cover edge. -/
def cubeCoverEdgeDirection (edge : Cube3CoverEdge) : Fin 3 :=
  Classical.choose edge.covBy.exists_set_insert

theorem cubeCoverEdgeDirection_not_mem (edge : Cube3CoverEdge) :
    cubeCoverEdgeDirection edge ∉ edge.lower :=
  (Classical.choose_spec edge.covBy.exists_set_insert).1

theorem cubeCoverEdge_insert_direction (edge : Cube3CoverEdge) :
    insert (cubeCoverEdgeDirection edge) edge.lower = edge.upper :=
  (Classical.choose_spec edge.covBy.exists_set_insert).2

/-- Canonical cover edge in a chosen direction above an arbitrary base cell. -/
def cubeEdgeAt (base : TangentCube3) (direction : Fin 3)
    (hDirection : direction ∉ base) : Cube3CoverEdge where
  lower := base
  upper := insert direction base
  covBy := Set.covBy_insert hDirection

/-- The origin edge in a primitive direction. -/
def cubeOriginEdge (direction : Fin 3) : Cube3CoverEdge :=
  cubeEdgeAt ∅ direction (Set.notMem_empty direction)

theorem cubeCoverEdgeDirection_cubeEdgeAt
    (base : TangentCube3) (direction : Fin 3)
    (hDirection : direction ∉ base) :
    cubeCoverEdgeDirection (cubeEdgeAt base direction hDirection) = direction := by
  let chosen := cubeCoverEdgeDirection (cubeEdgeAt base direction hDirection)
  have hChosenNotMem : chosen ∉ base :=
    by simpa [chosen, cubeEdgeAt] using
      cubeCoverEdgeDirection_not_mem
        (cubeEdgeAt base direction hDirection)
  have hInsert : insert chosen base = insert direction base := by
    simpa [cubeEdgeAt] using cubeCoverEdge_insert_direction
      (cubeEdgeAt base direction hDirection)
  by_contra hDifferent
  have hChosenMem : chosen ∈ insert direction base := by
    rw [← hInsert]
    exact Set.mem_insert chosen base
  rcases hChosenMem with hChosenEq | hChosenBase
  · exact hDifferent (by simpa [chosen] using hChosenEq)
  · exact hChosenNotMem hChosenBase

theorem oppositeInCausalDiamond_cube_direction_eq
    {first second : Cube3CoverEdge}
    (hOpposite : OppositeInCausalDiamond first second) :
    cubeCoverEdgeDirection first = cubeCoverEdgeDirection second := by
  rcases hOpposite with ⟨hLower, hUpper, hDistinct⟩
  let direction := cubeCoverEdgeDirection first
  have hDirectionUpper : direction ∈ first.upper := by
    rw [← cubeCoverEdge_insert_direction first]
    exact Set.mem_insert direction first.lower
  have hDirectionTop : direction ∈ second.upper :=
    hUpper.le hDirectionUpper
  have hDirectionNotSecondLower : direction ∉ second.lower := by
    intro hDirectionLower
    have hFirstUpperSubset : first.upper ⊆ second.lower := by
      rw [← cubeCoverEdge_insert_direction first]
      exact Set.insert_subset hDirectionLower hLower.le
    have hFirstUpperEq : first.upper = second.lower := by
      rcases hLower.eq_or_eq first.covBy.le hFirstUpperSubset with hEq | hEq
      · exact False.elim (first.covBy.ne hEq.symm)
      · exact hEq
    exact hDistinct hFirstUpperEq
  have hSecondInsert := cubeCoverEdge_insert_direction second
  rw [← hSecondInsert] at hDirectionTop
  rcases hDirectionTop with hEqual | hInLower
  · exact hEqual
  · exact False.elim (hDirectionNotSecondLower hInLower)

theorem sameCausalDirection_cube_direction_eq
    {first second : Cube3CoverEdge}
    (hSame : SameCausalDirection first second) :
    cubeCoverEdgeDirection first = cubeCoverEdgeDirection second := by
  induction hSame with
  | rel first second hRel =>
      exact oppositeInCausalDiamond_cube_direction_eq hRel
  | refl edge => rfl
  | symm first second _ ih => exact ih.symm
  | trans first middle second _ _ hFirst hSecond =>
      exact hFirst.trans hSecond

/-- Adding a different base coordinate moves an edge across one commuting
diamond without changing its direction. -/
theorem cubeEdgeAt_opposite_insert
    (base : TangentCube3) (direction added : Fin 3)
    (hDirection : direction ∉ base) (hAdded : added ∉ base)
    (hDifferent : added ≠ direction) :
    OppositeInCausalDiamond
      (cubeEdgeAt base direction hDirection)
      (cubeEdgeAt (insert added base) direction (by
        simpa [Set.mem_insert_iff, hDifferent.symm] using hDirection)) := by
  constructor
  · exact Set.covBy_insert hAdded
  constructor
  · change insert direction base ⋖ insert direction (insert added base)
    rw [Set.insert_comm direction added]
    exact Set.covBy_insert (by
      simpa [Set.mem_insert_iff, hDifferent] using hAdded)
  · intro hEqual
    have hDirectionInEdge :
        direction ∈
          (cubeEdgeAt (insert added base) direction (by
            simpa [Set.mem_insert_iff, hDifferent.symm] using hDirection)).lower := by
      rw [← hEqual]
      exact Set.mem_insert direction base
    have hDirectionIn : direction ∈ insert added base := by
      simpa [cubeEdgeAt] using hDirectionInEdge
    rcases hDirectionIn with hEq | hBase
    · exact hDifferent hEq.symm
    · exact hDirection hBase

theorem cubeOrigin_same_direction_cubeEdgeAtFinset
    (base : Finset (Fin 3)) (direction : Fin 3)
    (hDirection : direction ∉ base) :
    SameCausalDirection (cubeOriginEdge direction)
      (cubeEdgeAt (base : Set (Fin 3)) direction (by simpa using hDirection)) := by
  classical
  induction base using Finset.induction_on with
  | empty =>
      simpa [cubeOriginEdge, cubeEdgeAt] using
        (Relation.EqvGen.refl (cubeOriginEdge direction))
  | @insert added base hAdded ih =>
      have hDifferent : added ≠ direction := by
        intro hEqual
        subst added
        exact hDirection (Finset.mem_insert_self direction base)
      have hDirectionBase : direction ∉ base := by
        intro hMem
        exact hDirection (Finset.mem_insert_of_mem hMem)
      have hStep :
          SameCausalDirection
            (cubeEdgeAt (base : Set (Fin 3)) direction (by
              simpa using hDirectionBase))
            (cubeEdgeAt ((insert added base : Finset (Fin 3)) : Set (Fin 3))
              direction (by simpa using hDirection)) := by
        apply Relation.EqvGen.rel
        simpa using cubeEdgeAt_opposite_insert
          (base : Set (Fin 3)) direction added
          (by simpa using hDirectionBase) (by simpa using hAdded) hDifferent
      exact Relation.EqvGen.trans _ _ _ (ih hDirectionBase) hStep

theorem cubeOrigin_same_direction_edge (edge : Cube3CoverEdge) :
    SameCausalDirection
      (cubeOriginEdge (cubeCoverEdgeDirection edge)) edge := by
  classical
  let direction := cubeCoverEdgeDirection edge
  have hDirection : direction ∉ edge.lower :=
    cubeCoverEdgeDirection_not_mem edge
  have hBase := cubeOrigin_same_direction_cubeEdgeAtFinset
    edge.lower.toFinset direction (by simpa using hDirection)
  have hEdgeAt :
      cubeEdgeAt edge.lower direction hDirection = edge := by
    apply CausalCoverEdge.ext
    · rfl
    · exact cubeCoverEdge_insert_direction edge
  simpa [direction, hEdgeAt] using hBase

/-- Direction map out of the diamond quotient. -/
def cubeLocalDirectionToFin3 : LocalCausalDirection TangentCube3 → Fin 3 :=
  Quotient.lift cubeCoverEdgeDirection
    (fun _ _ hSame => sameCausalDirection_cube_direction_eq hSame)

/-- The intrinsic direction quotient of the elementary Boolean cube is
canonically equivalent to its three primitive directions. -/
def cubeLocalDirectionEquivFin3 :
    LocalCausalDirection TangentCube3 ≃ Fin 3 where
  toFun := cubeLocalDirectionToFin3
  invFun direction := Quotient.mk'' (cubeOriginEdge direction)
  left_inv direction := by
    refine Quotient.inductionOn direction ?_
    intro edge
    apply Quotient.sound
    exact cubeOrigin_same_direction_edge edge
  right_inv direction := by
    exact cubeCoverEdgeDirection_cubeEdgeAt ∅ direction
      (Set.notMem_empty direction)

noncomputable instance cubeLocalCausalDirectionFintype :
    Fintype (LocalCausalDirection TangentCube3) :=
  Fintype.ofEquiv (Fin 3) cubeLocalDirectionEquivFin3.symm

/-- **Local existence witness.** Opposite-diamond equivalence reconstructs
exactly three directions on the elementary Boolean tangent cube. -/
theorem cubeLocalCausalDirection_card_eq_three :
    Fintype.card (LocalCausalDirection TangentCube3) = 3 := by
  simpa using Fintype.card_congr cubeLocalDirectionEquivFin3

/-! ## 4. Path comparison and the global-labeling obstruction -/

/-- A directed transition system with a possibly state-dependent direction
fiber and an equivalence transported along every edge. -/
structure DirectionEdgeLaw
    (State : Type u) (Direction : State → Type v)
    (Edge : State → Type w) where
  target : ∀ state, Edge state → State
  transport : ∀ state (edge : Edge state),
    Direction state ≃ Direction (target state edge)

/-- Directed paths in an edge law. Different directed paths may share their
initial and terminal states even though the growth graph has no directed
cycles. -/
inductive DirectionPath
    {State : Type u} {Direction : State → Type v}
    {Edge : State → Type w}
    (law : DirectionEdgeLaw State Direction Edge) : State → State → Type _
  | nil (state : State) : DirectionPath law state state
  | cons {start finish : State} (edge : Edge start)
      (tail : DirectionPath law (law.target start edge) finish) :
      DirectionPath law start finish

/-- Composite direction transport along a directed path. -/
def directionPathTransport
    {State : Type u} {Direction : State → Type v}
    {Edge : State → Type w}
    {law : DirectionEdgeLaw State Direction Edge}
    {start finish : State} :
    DirectionPath law start finish → Direction start ≃ Direction finish
  | .nil _ => Equiv.refl _
  | .cons edge tail =>
      (law.transport _ edge).trans (directionPathTransport tail)

/-- A global direction labeling trivializes every edge transport. -/
structure GlobalDirectionLabeling
    {State : Type u} {Direction : State → Type v}
    {Edge : State → Type w}
    (law : DirectionEdgeLaw State Direction Edge) where
  label : ∀ state, Direction state ≃ Fin 3
  edge_natural : ∀ state (edge : Edge state),
    (law.transport state edge).trans (label (law.target state edge)) =
      label state

theorem directionPathTransport_trans_label_eq
    {State : Type u} {Direction : State → Type v}
    {Edge : State → Type w}
    {law : DirectionEdgeLaw State Direction Edge}
    (labeling : GlobalDirectionLabeling law)
    {start finish : State} (path : DirectionPath law start finish) :
    (directionPathTransport path).trans (labeling.label finish) =
      labeling.label start := by
  induction path with
  | nil state => rfl
  | cons edge tail ih =>
      rw [directionPathTransport, Equiv.trans_assoc, ih]
      exact labeling.edge_natural _ edge

/-- Any global labeling forces equal transport along all pairs of paths with
the same endpoints. -/
theorem globalLabeling_forces_path_independence
    {State : Type u} {Direction : State → Type v}
    {Edge : State → Type w}
    {law : DirectionEdgeLaw State Direction Edge}
    (labeling : GlobalDirectionLabeling law)
    {start finish : State}
    (first second : DirectionPath law start finish) :
    directionPathTransport first = directionPathTransport second := by
  have hFirst := directionPathTransport_trans_label_eq labeling first
  have hSecond := directionPathTransport_trans_label_eq labeling second
  apply Equiv.ext
  intro direction
  apply (labeling.label finish).injective
  have hFirstPoint := congrArg (fun equiv => equiv direction) hFirst
  have hSecondPoint := congrArg (fun equiv => equiv direction) hSecond
  exact hFirstPoint.trans hSecondPoint.symm

/-- A nontrivial path-comparison holonomy is an explicit obstruction to a
global three-direction labeling. -/
theorem nontrivial_path_comparison_forbids_global_labeling
    {State : Type u} {Direction : State → Type v}
    {Edge : State → Type w}
    {law : DirectionEdgeLaw State Direction Edge}
    {start finish : State}
    (first second : DirectionPath law start finish)
    (hDifferent : directionPathTransport first ≠
      directionPathTransport second) :
    ¬ Nonempty (GlobalDirectionLabeling law) := by
  rintro ⟨labeling⟩
  exact hDifferent
    (globalLabeling_forces_path_independence labeling first second)

#print axioms cubeLocalCausalDirection_card_eq_three
#print axioms transportLocalCausalDirection_trans
#print axioms globalLabeling_forces_path_independence
#print axioms nontrivial_path_comparison_forbids_global_labeling

end

end UnifiedTheory.Audit.KFCausalDiamondDirectionCover
