/-
  Audit/KFCausalCSpecHarmonicBornLocalNet.lean

  A FINITE LOCAL STAR-ALGEBRA NET WITH A CAUSAL BORN STATE

  This module removes the independent `localState` input from the finite
  recovered-CSpec/Hilbert interface after one honest piece of coarse-graining
  data has been fixed.  A `HarmonicSingleGenerationReadout` says which finite
  causal-growth rank is read at each recovered site and maps the actual
  finite causal children at every rank into the framework-selected 16
  single-generation outcomes.  It does not assert that this readout is the
  physically correct Standard-Model coarse graining.

  The action-selected harmonic Born law then proves nonnegativity and unit
  mass of the readout weights.  Their positive square roots canonically give
  a real-amplitude `SubstrateState singleGenDim`, hence a positive trace-one
  density matrix and exact Born compatibility.

  On a finite recovered site type, observables are site-indexed 16 by 16
  complex matrices.  The algebra of a finite region is the unital star
  subalgebra generated by observables supported in that region.  Inclusion of
  regions gives isotony.  Evaluation against the causal Born density matrix
  is a normalized positive linear functional, and its computational effects
  recover the original harmonic readout weights exactly.

  This is a finite net, not a continuum AQFT construction.  The physical
  interpretation of the readout, a compatible continuum inductive limit,
  spacelike commutativity, Wightman/OS positivity in that limit,
  spin-statistics, gauge dynamics, and the Standard-Model IR limit remain
  explicit downstream targets.

  Zero sorry. Zero custom axioms.
-/

import Mathlib.Algebra.Star.Subalgebra
import UnifiedTheory.Audit.KFCausalCSpecQFTSMInterface
import UnifiedTheory.Audit.KFCausalBornObservedWeight

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFCausalCSpecHarmonicBornLocalNet

noncomputable section

universe u

open scoped BigOperators ComplexConjugate ComplexOrder
open Matrix
open UnifiedTheory.Audit.KFCausalCSpecQFTSMInterface
open UnifiedTheory.Audit.KFCausalCSpecQFTSMInterface.RecoveredCSpecHilbertFiber
open UnifiedTheory.Audit.KFCausalCSpecBridgeDefectObservable
open UnifiedTheory.Audit.KFCausalCSpecContinuationProfile
open UnifiedTheory.Audit.KFCausalCSpecGlobalization
open UnifiedTheory.Audit.KFCausalSetSequentialGrowth
open UnifiedTheory.Audit.KFCausalBornShellGeneralLaw
open UnifiedTheory.Audit.KFCausalBornNormalizationTransfer
open UnifiedTheory.Audit.KFCausalBornObservedWeight
open UnifiedTheory.LayerC.SMBornRuleGeneralN
open UnifiedTheory.LayerC.SMHilbertInstantiation

/-! ## 1. A typed causal readout and its canonical positive-square-root state -/

/-- The finite coarse graining that is still needed to interpret causal
children as single-generation outcomes.  It is data, not evidence that the
chosen coarse graining is physically correct. -/
structure HarmonicSingleGenerationReadout (site : Type u) where
  parentSchedule :
    (n : ℕ) → RankedGrowthPath CausalSetGrowthBranch n
  observe :
    (n : ℕ) → CausalSetGrowthBranch n → Fin singleGenDim
  rankAt : site → ℕ

/-- The actual action-selected harmonic Born weight seen at one recovered
site after applying the supplied finite readout. -/
noncomputable def harmonicReadoutWeight
    {site : Type u}
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) (k : Fin singleGenDim) : ℝ :=
  harmonicObservedBornWeight chirality R.parentSchedule R.observe (R.rankAt i) k

theorem harmonicReadoutWeight_nonneg
    {site : Type u}
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) (k : Fin singleGenDim) :
    0 ≤ harmonicReadoutWeight chirality R i k := by
  exact harmonicObservedBornWeight_nonneg
    chirality R.parentSchedule R.observe (R.rankAt i) k

theorem harmonicReadoutWeight_sum_one
    {site : Type u}
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) :
    ∑ k, harmonicReadoutWeight chirality R i k = 1 := by
  exact harmonicObservedBornWeight_sum_one
    chirality R.parentSchedule R.observe (R.rankAt i)

/-- The positive-square-root lift of the causal readout PMF.  No local state
is supplied independently: once the chirality and readout are fixed, this is
the canonical real-amplitude representative. -/
noncomputable def harmonicReadoutSubstrateState
    {site : Type u}
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) : SubstrateState singleGenDim where
  amp := fun k => Real.sqrt (harmonicReadoutWeight chirality R i k)
  normalized := by
    calc
      (∑ k,
          Real.sqrt (harmonicReadoutWeight chirality R i k) ^ 2) =
          ∑ k, harmonicReadoutWeight chirality R i k := by
            apply Finset.sum_congr rfl
            intro k _
            exact Real.sq_sqrt
              (harmonicReadoutWeight_nonneg chirality R i k)
      _ = 1 := harmonicReadoutWeight_sum_one chirality R i

@[simp]
theorem harmonicReadoutSubstrateState_amp_sq
    {site : Type u}
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) (k : Fin singleGenDim) :
    (harmonicReadoutSubstrateState chirality R i).amp k ^ 2 =
      harmonicReadoutWeight chirality R i k := by
  exact Real.sq_sqrt (harmonicReadoutWeight_nonneg chirality R i k)

@[simp]
theorem harmonicReadoutSubstrateState_amp_nonneg
    {site : Type u}
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) (k : Fin singleGenDim) :
    0 ≤ (harmonicReadoutSubstrateState chirality R i).amp k :=
  Real.sqrt_nonneg _

/-! ## 2. Removal of the independent local-state input -/

variable {site : Type u} [Fintype site] [Nonempty site]
variable {countWindow curvatureBias spectralLocality : site → ℝ}
variable {scale total : ℝ}
variable {edge : site → E4}
variable {candidate : site → Equiv.Perm Direction}

/-- A recovered CSpec stage plus a finite causal readout canonically supplies
the local `SubstrateState` field of the earlier interface. -/
noncomputable def recoveredHarmonicBornHilbertFiber
    (recovered : PhysicalHauptvermutungRecoveredStage
      countWindow curvatureBias spectralLocality scale total edge candidate)
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site) :
    RecoveredCSpecHilbertFiber
      countWindow curvatureBias spectralLocality scale total edge candidate where
  recovered := recovered
  localState := harmonicReadoutSubstrateState chirality R

theorem recoveredHarmonicBornHilbertFiber_born_weight
    (recovered : PhysicalHauptvermutungRecoveredStage
      countWindow curvatureBias spectralLocality scale total edge candidate)
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) (k : Fin singleGenDim) :
    (((substrateToDensityMatrix singleGenDim
          ((recoveredHarmonicBornHilbertFiber recovered chirality R).localState i)).M *
        computationalProjector singleGenDim k).trace.re) =
      harmonicReadoutWeight chirality R i k := by
  rw [RecoveredCSpecHilbertFiber.born_weight_eq_amp_sq]
  exact harmonicReadoutSubstrateState_amp_sq chirality R i k

theorem recoveredHarmonicBornHilbertFiber_born_normalized
    (recovered : PhysicalHauptvermutungRecoveredStage
      countWindow curvatureBias spectralLocality scale total edge candidate)
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) :
    ∑ k,
        (((substrateToDensityMatrix singleGenDim
            ((recoveredHarmonicBornHilbertFiber recovered chirality R).localState i)).M *
          computationalProjector singleGenDim k).trace.re) = 1 := by
  exact
    (recoveredHarmonicBornHilbertFiber recovered chirality R).born_weights_normalized i

/-! ## 3. A finite unital local star-algebra net -/

/-- One single-generation observable. -/
abbrev SingleGenerationObservable :=
  Matrix (Fin singleGenDim) (Fin singleGenDim) ℂ

/-- The ambient finite field algebra: one matrix at every recovered site. -/
abbrev FiniteFieldObservable (site : Type u) :=
  site → SingleGenerationObservable

/-- Observables whose nonscalar part is supported in the displayed finite
region.  These are used as generators; adjoining the unit makes the local
algebra unital even for the empty region. -/
def regionSupportedObservables (region : Finset site) :
    Set (FiniteFieldObservable site) :=
  {observable | ∀ i, i ∉ region → observable i = 0}

/-- The finite local observable algebra of a region. -/
def finiteLocalObservableAlgebra (region : Finset site) :
    StarSubalgebra ℂ (FiniteFieldObservable site) :=
  StarAlgebra.adjoin ℂ (regionSupportedObservables region)

theorem regionSupportedObservables_mono
    {first second : Finset site}
    (h : first ⊆ second) :
    regionSupportedObservables first ⊆ regionSupportedObservables second := by
  intro observable hObservable i hi
  exact hObservable i (fun hFirst => hi (h hFirst))

/-- Isotony: inclusion of finite recovered regions induces inclusion of their
unital local star algebras. -/
theorem finiteLocalObservableAlgebra_isotony
    {first second : Finset site}
    (h : first ⊆ second) :
    finiteLocalObservableAlgebra first ≤
      finiteLocalObservableAlgebra second :=
  StarAlgebra.adjoin_mono (R := ℂ) (regionSupportedObservables_mono h)

/-- Embed a matrix observable at one recovered site and zero elsewhere. -/
noncomputable def observableAt (i : site) (A : SingleGenerationObservable) :
    FiniteFieldObservable site := by
  classical
  exact fun j => if j = i then A else 0

theorem observableAt_supported
    (i : site) (A : SingleGenerationObservable) :
    observableAt i A ∈ regionSupportedObservables ({i} : Finset site) := by
  intro j hj
  simp only [Finset.mem_singleton] at hj
  simp [observableAt, hj]

/-- Every genuine one-site matrix observable belongs to its singleton local
algebra; the net is not merely the scalar algebra. -/
theorem observableAt_mem_singleton_algebra
    (i : site) (A : SingleGenerationObservable) :
    observableAt i A ∈ finiteLocalObservableAlgebra ({i} : Finset site) :=
  StarAlgebra.subset_adjoin ℂ (regionSupportedObservables ({i} : Finset site))
    (observableAt_supported i A)

/-! ## 4. The normalized positive causal Born state on the finite net -/

/-- The density matrix selected by the causal readout at a recovered site. -/
noncomputable def harmonicReadoutDensity
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) :=
  substrateToDensityMatrix singleGenDim
    (harmonicReadoutSubstrateState chirality R i)

/-- Evaluation of a field observable in the causal Born density at one site,
packaged as a complex-linear functional. -/
noncomputable def harmonicLocalStateFunctional
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) :
    FiniteFieldObservable site →ₗ[ℂ] ℂ where
  toFun := fun observable =>
    Matrix.trace ((harmonicReadoutDensity chirality R i).M * observable i)
  map_add' := by
    intro first second
    simp only [Pi.add_apply, Matrix.mul_add, Matrix.trace_add]
  map_smul' := by
    intro scalar observable
    simp only [Pi.smul_apply, Matrix.mul_smul, Matrix.trace_smul,
      RingHom.id_apply]

@[simp]
theorem harmonicLocalStateFunctional_apply
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) (observable : FiniteFieldObservable site) :
    harmonicLocalStateFunctional chirality R i observable =
      Matrix.trace ((harmonicReadoutDensity chirality R i).M * observable i) :=
  rfl

/-- Normalization of the local functional. -/
theorem harmonicLocalStateFunctional_normalized
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) :
    harmonicLocalStateFunctional chirality R i 1 = 1 := by
  change Matrix.trace ((harmonicReadoutDensity chirality R i).M * 1) = 1
  rw [Matrix.mul_one]
  exact (harmonicReadoutDensity chirality R i).hTrace

/-- Positivity on every pointwise star-square.  This is the finite matrix
positivity required of a state; no extra positivity axiom is assumed. -/
theorem harmonicLocalStateFunctional_positive
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site)
    (observable : FiniteFieldObservable site) :
    0 ≤ (harmonicLocalStateFunctional chirality R i
      (star observable * observable)).re := by
  simpa [harmonicLocalStateFunctional, Matrix.mul_assoc] using
    (harmonicReadoutDensity chirality R i).hTracePSD (observable i)

/-- Restrict the same state to any member of the finite local net. -/
noncomputable def harmonicRegionStateFunctional
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site)
    (region : Finset site) :
    finiteLocalObservableAlgebra region →ₗ[ℂ] ℂ :=
  (harmonicLocalStateFunctional chirality R i).comp
    (finiteLocalObservableAlgebra region).toSubalgebra.toSubmodule.subtype

/-- State restrictions are compatible with isotony inclusions. -/
theorem harmonicRegionStateFunctional_isotony_compatible
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site)
    {first second : Finset site}
    (h : first ⊆ second)
    (observable : finiteLocalObservableAlgebra first) :
    harmonicRegionStateFunctional chirality R i second
        (StarSubalgebra.inclusion
          (finiteLocalObservableAlgebra_isotony h) observable) =
      harmonicRegionStateFunctional chirality R i first observable :=
  by
    change harmonicLocalStateFunctional chirality R i
        (observable : FiniteFieldObservable site) =
      harmonicLocalStateFunctional chirality R i
        (observable : FiniteFieldObservable site)
    rfl

/-- The computational basis effect localized at one recovered site. -/
noncomputable def computationalEffectAt
    (i : site) (k : Fin singleGenDim) : FiniteFieldObservable site :=
  observableAt i (computationalProjector singleGenDim k)

theorem computationalEffectAt_mem_singleton_algebra
    (i : site) (k : Fin singleGenDim) :
    computationalEffectAt i k ∈
      finiteLocalObservableAlgebra ({i} : Finset site) :=
  observableAt_mem_singleton_algebra i (computationalProjector singleGenDim k)

/-- Exact Born compatibility: evaluating a localized computational effect in
the canonical finite state returns the original causal readout weight. -/
theorem harmonicLocalStateFunctional_computationalEffect
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) (k : Fin singleGenDim) :
    (harmonicLocalStateFunctional chirality R i
        (computationalEffectAt i k)).re =
      harmonicReadoutWeight chirality R i k := by
  rw [harmonicLocalStateFunctional_apply]
  simp only [computationalEffectAt, observableAt, ↓reduceIte]
  change (((substrateToDensityMatrix singleGenDim
      (harmonicReadoutSubstrateState chirality R i)).M *
    computationalProjector singleGenDim k).trace.re) = _
  rw [born_rule_general_n]
  exact harmonicReadoutSubstrateState_amp_sq chirality R i k

/-- The localized computational effects form a normalized Born family. -/
theorem harmonicLocalStateFunctional_computationalEffects_normalized
    (chirality : Fin 2)
    (R : HarmonicSingleGenerationReadout site)
    (i : site) :
    ∑ k,
        (harmonicLocalStateFunctional chirality R i
          (computationalEffectAt i k)).re = 1 := by
  simp_rw [harmonicLocalStateFunctional_computationalEffect]
  exact harmonicReadoutWeight_sum_one chirality R i

/-! ## 5. Honest continuum boundary -/

/-- A fixed semantic ledger for the ingredients still required to promote
this finite net to the Gate-5 continuum/QFT/Standard-Model claim.  A physical
model must define these predicates before downstream evidence is meaningful. -/
structure FiniteNetContinuumCompletionClaims where
  continuumHilbertQFTLimit : Prop
  finiteNetEmbedsInContinuum : Prop
  spacelikeCommutativity : Prop
  continuumPositivity : Prop
  spinStatistics : Prop
  gaugeRenormalization : Prop
  standardModelIRLimit : Prop

/-- Evidence for one fixed continuum-completion ledger.  No theorem in this
file manufactures a value of this record. -/
structure FiniteNetContinuumCompletionEvidence
    (claims : FiniteNetContinuumCompletionClaims) : Prop where
  continuumHilbertQFTLimit_closed : claims.continuumHilbertQFTLimit
  finiteNetEmbedsInContinuum_closed : claims.finiteNetEmbedsInContinuum
  spacelikeCommutativity_closed : claims.spacelikeCommutativity
  continuumPositivity_closed : claims.continuumPositivity
  spinStatistics_closed : claims.spinStatistics
  gaugeRenormalization_closed : claims.gaugeRenormalization
  standardModelIRLimit_closed : claims.standardModelIRLimit

/-- A deliberately impossible fixed ledger checks that continuum evidence is
not built into the interface.  Callers remain responsible for choosing
non-vacuous predicates with the intended physical semantics. -/
def FiniteNetContinuumCompletionClaims.impossible :
    FiniteNetContinuumCompletionClaims where
  continuumHilbertQFTLimit := False
  finiteNetEmbedsInContinuum := False
  spacelikeCommutativity := False
  continuumPositivity := False
  spinStatistics := False
  gaugeRenormalization := False
  standardModelIRLimit := False

theorem impossible_continuum_completion_not_satisfied :
    ¬ FiniteNetContinuumCompletionEvidence
      FiniteNetContinuumCompletionClaims.impossible := by
  intro evidence
  exact evidence.continuumHilbertQFTLimit_closed

/-! ## 6. Axiom audit -/

#print axioms harmonicReadoutSubstrateState
#print axioms recoveredHarmonicBornHilbertFiber_born_weight
#print axioms finiteLocalObservableAlgebra_isotony
#print axioms observableAt_mem_singleton_algebra
#print axioms harmonicLocalStateFunctional_normalized
#print axioms harmonicLocalStateFunctional_positive
#print axioms harmonicRegionStateFunctional_isotony_compatible
#print axioms harmonicLocalStateFunctional_computationalEffect
#print axioms harmonicLocalStateFunctional_computationalEffects_normalized

end

end UnifiedTheory.Audit.KFCausalCSpecHarmonicBornLocalNet
