/-
  Audit/KFCausalMayerVietoris.lean
  — THE TWO-SET-COVER (MAYER–VIETORIS) LEMMA BEHIND THE CHAIN-PAIR HOLONOMY

  Companion to KFCausalNerveHolonomy.lean and scripts/ab_chain_pair_holonomy.py.
  In the numerics, a pair p < q splits its chains p < a < q into classes = the
  components of P ∩ Q, where P = J⁺(p) ∩ A and Q = J⁻(q) ∩ A cover the slice
  complex.  The Wilson factor of two classes is the holonomy of a crossing
  loop γ = (path a₁ → a₂ inside P) + (path a₂ → a₁ inside Q).  The observed
  values (0 within one class, ±1 between two classes) are FORCED; this file
  proves why, at the level of integer 1-chains, with no simplicial topology:

  * `same_component_bounds` / `hol_same_component` — if a₁, a₂ are joined
    inside P ∩ Q, and cycles supported in P (resp. Q) bound, the crossing loop
    bounds: holonomy 0.
  * `crossing_independent` — the class of γ does not depend on the paths
    chosen inside P and Q.
  * `crossing_generates` — every cycle that splits as c_P + c_Q with
    ∂c_P = n·∂p_P is homologous to n·γ (the Mayer–Vietoris connecting step).
  * `crossing_is_pm_generator` / `hol_crossing_pm` — if H₁ is generated by z
    of infinite order and γ is a multiple of z, then γ ≡ ±z, so a flat
    cochain has holonomy ±hol(z) on γ.

  "Cycles supported in S bound" is stated directly (`CyclesBound`), which is
  what the argument uses; it is implied by acyclicity of the subcomplex.
  The reduction of a general cycle to one with ∂c_P = n·∂p_P is PROVED
  (`deg0_is_boundary`, `reduce_two_components`): a degree-zero 0-chain on an
  internally joined set is a boundary there.  `hol_crossing_pm_full` is the
  statement with no assumed reduction.

  Zero sorry.  Zero custom axioms.
-/
import Mathlib
import UnifiedTheory.Audit.KFCausalNerveHolonomy

set_option autoImplicit false
set_option linter.unusedSectionVars false

namespace UnifiedTheory.Audit.KFCausalMayerVietoris

open UnifiedTheory.Audit.KFCausalNerveHolonomy

variable {V : Type*} [DecidableEq V]

/-- A chain supported on edges with both endpoints in `S`. -/
def SupportedIn (S : Set V) (c : Chain V) : Prop :=
  ∀ e ∈ c.support, e.1 ∈ S ∧ e.2 ∈ S

theorem supportedIn_zero (S : Set V) : SupportedIn S (0 : Chain V) := by
  intro e he; simp at he

theorem SupportedIn.add {S : Set V} {c d : Chain V} (hc : SupportedIn S c)
    (hd : SupportedIn S d) : SupportedIn S (c + d) := by
  intro e he
  rcases Finset.mem_union.mp (Finsupp.support_add he) with h | h
  · exact hc e h
  · exact hd e h

theorem SupportedIn.neg {S : Set V} {c : Chain V} (hc : SupportedIn S c) :
    SupportedIn S (-c) := by
  intro e he; rw [Finsupp.support_neg] at he; exact hc e he

theorem SupportedIn.sub {S : Set V} {c d : Chain V} (hc : SupportedIn S c)
    (hd : SupportedIn S d) : SupportedIn S (c - d) := by
  rw [sub_eq_add_neg]; exact hc.add hd.neg

theorem SupportedIn.zsmul {S : Set V} {c : Chain V} (hc : SupportedIn S c) (n : ℤ) :
    SupportedIn S (n • c) := by
  intro e he; exact hc e (Finsupp.support_smul he)

theorem SupportedIn.mono {S S' : Set V} (h : S ⊆ S') {c : Chain V} (hc : SupportedIn S c) :
    SupportedIn S' c := fun e he => ⟨h (hc e he).1, h (hc e he).2⟩

/-- Every cycle supported in `S` is a boundary of the declared complex. -/
def CyclesBound (T : Set (V × V × V)) (S : Set V) : Prop :=
  ∀ c : Chain V, SupportedIn S c → bd c = 0 → c ∈ boundaries T

variable {T : Set (V × V × V)} {P Q : Set V}

/-- **Same component ⇒ the crossing loop bounds.**  `r` joins the endpoints
inside `P ∩ Q` (same boundary as `pP`); `pQ` returns inside `Q`. -/
theorem same_component_bounds (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ r : Chain V) (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ)
    (sr : SupportedIn (P ∩ Q) r) (hr : bd r = bd pP) (hloop : bd pQ = -bd pP) :
    pP + pQ ∈ boundaries T := by
  have h1 : pP - r ∈ boundaries T :=
    hP _ (sP.sub (sr.mono Set.inter_subset_left)) (by rw [map_sub, hr, sub_self])
  have h2 : r + pQ ∈ boundaries T :=
    hQ _ ((sr.mono Set.inter_subset_right).add sQ) (by rw [map_add, hr, hloop, add_neg_cancel])
  have := (boundaries T).add_mem h1 h2
  rwa [show pP - r + (r + pQ) = pP + pQ by abel] at this

theorem hol_same_component {K : Type*} [AddCommGroup K] (U : V → V → K) (hU : FlatOn U T)
    (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ r : Chain V) (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ)
    (sr : SupportedIn (P ∩ Q) r) (hr : bd r = bd pP) (hloop : bd pQ = -bd pP) :
    hol U (pP + pQ) = 0 :=
  hol_boundary U T hU _ (same_component_bounds hP hQ pP pQ r sP sQ sr hr hloop)

/-- **Representative independence**: changing the paths inside `P` and `Q`
(same endpoints) does not change the class of the crossing loop. -/
theorem crossing_independent (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pP' pQ pQ' : Chain V) (sP : SupportedIn P pP) (sP' : SupportedIn P pP')
    (sQ : SupportedIn Q pQ) (sQ' : SupportedIn Q pQ')
    (hbP : bd pP' = bd pP) (hbQ : bd pQ' = bd pQ) :
    (pP + pQ) - (pP' + pQ') ∈ boundaries T := by
  have h1 : pP - pP' ∈ boundaries T := hP _ (sP.sub sP') (by rw [map_sub, hbP, sub_self])
  have h2 : pQ - pQ' ∈ boundaries T := hQ _ (sQ.sub sQ') (by rw [map_sub, hbQ, sub_self])
  have := (boundaries T).add_mem h1 h2
  rwa [show pP - pP' + (pQ - pQ') = (pP + pQ) - (pP' + pQ') by abel] at this

/-- **The Mayer–Vietoris connecting step**: a cycle split as `cP + cQ` with
`∂cP = n·∂pP` is homologous to `n` times the crossing loop. -/
theorem crossing_generates (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ cP cQ : Chain V) (n : ℤ)
    (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ)
    (scP : SupportedIn P cP) (scQ : SupportedIn Q cQ)
    (hloop : bd pQ = -bd pP) (hcyc : bd (cP + cQ) = 0) (hn : bd cP = n • bd pP) :
    (cP + cQ) - n • (pP + pQ) ∈ boundaries T := by
  have hcQ : bd cQ = -(n • bd pP) := by
    rw [map_add, hn] at hcyc; exact eq_neg_of_add_eq_zero_right hcyc
  have h1 : cP - n • pP ∈ boundaries T :=
    hP _ (scP.sub (sP.zsmul n)) (by rw [map_sub, map_zsmul, hn, sub_self])
  have h2 : cQ - n • pQ ∈ boundaries T :=
    hQ _ (scQ.sub (sQ.zsmul n)) (by rw [map_sub, map_zsmul, hcQ, hloop, smul_neg, sub_self])
  have := (boundaries T).add_mem h1 h2
  rwa [show cP - n • pP + (cQ - n • pQ) = (cP + cQ) - n • (pP + pQ) by
    rw [smul_add]; abel] at this

/-- **Generator ⇒ ±1.**  If `z` has infinite order modulo boundaries, `z` is
homologous to `n·γ`, and `γ` is homologous to `k·z`, then `γ ≡ z` or
`γ ≡ −z`. -/
theorem crossing_is_pm_generator (z γ : Chain V) (n k : ℤ)
    (hz : ∀ m : ℤ, m • z ∈ boundaries T → m = 0)
    (hzn : z - n • γ ∈ boundaries T) (hγk : γ - k • z ∈ boundaries T) :
    (γ - z ∈ boundaries T) ∨ (γ + z ∈ boundaries T) := by
  have hm : (1 - n * k) • z ∈ boundaries T := by
    have := (boundaries T).add_mem hzn ((boundaries T).zsmul_mem hγk n)
    rwa [show z - n • γ + n • (γ - k • z) = (1 - n * k) • z by
      rw [smul_sub, smul_smul, sub_smul, one_smul]; abel] at this
  have hnk : n * k = 1 := by have := hz _ hm; linarith
  rcases Int.eq_one_or_neg_one_of_mul_eq_one' hnk with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · left; simpa [one_smul] using hγk
  · right
    have : γ - (-1 : ℤ) • z = γ + z := by rw [neg_smul, one_smul, sub_neg_eq_add]
    rwa [this] at hγk

/-- Holonomy of the crossing loop is `± hol z`. -/
theorem hol_crossing_pm {K : Type*} [AddCommGroup K] (U : V → V → K) (hU : FlatOn U T)
    (z γ : Chain V) (n k : ℤ)
    (hz : ∀ m : ℤ, m • z ∈ boundaries T → m = 0)
    (hzn : z - n • γ ∈ boundaries T) (hγk : γ - k • z ∈ boundaries T) :
    hol U γ = hol U z ∨ hol U γ = -hol U z := by
  rcases crossing_is_pm_generator z γ n k hz hzn hγk with h | h
  · left; exact hol_homologous U T hU γ z h
  · right
    have := hol_boundary U T hU _ h
    rw [map_add] at this
    exact eq_neg_of_add_eq_zero_left this

/-! ### The cover hypothesis made explicit -/

/-- Every edge of `c` lies wholly in `P` or wholly in `Q`: the two shadows
cover the complex (on the support of `c`), not just its vertices.  An edge
straddling the shadows is in neither, and without this hypothesis the split
below, hence `crossing_generates`, is unavailable. -/
def EdgeCover (P Q : Set V) (c : Chain V) : Prop :=
  ∀ e ∈ c.support, (e.1 ∈ P ∧ e.2 ∈ P) ∨ (e.1 ∈ Q ∧ e.2 ∈ Q)

open Classical in
/-- Under the edge cover, a chain splits as a `P`-part plus a `Q`-part. -/
theorem split_of_edgeCover (c : Chain V) (hc : EdgeCover P Q c) :
    SupportedIn P (c.filter fun e => e.1 ∈ P ∧ e.2 ∈ P) ∧
    SupportedIn Q (c.filter fun e => ¬ (e.1 ∈ P ∧ e.2 ∈ P)) ∧
    (c.filter fun e => e.1 ∈ P ∧ e.2 ∈ P) + (c.filter fun e => ¬ (e.1 ∈ P ∧ e.2 ∈ P)) = c := by
  refine ⟨?_, ?_, Finsupp.filter_pos_add_filter_neg _ _⟩
  · intro e he
    rw [Finsupp.support_filter, Finset.mem_filter] at he
    exact he.2
  · intro e he
    rw [Finsupp.support_filter, Finset.mem_filter] at he
    exact (hc e he.1).resolve_left he.2

open Classical in
/-- **Combined statement.**  Hypotheses: the shadows cover the generator's
edges (`EdgeCover`), cycles in each shadow bound (`CyclesBound`), the
generator `z` of infinite order has `P`-part with boundary `n·∂pP`
(reduction within components, assumed), and the crossing loop is a multiple
of `z`.  Conclusion: a flat cochain has holonomy `± hol z` on the crossing
loop. -/
theorem hol_crossing_pm_of_cover {K : Type*} [AddCommGroup K] (U : V → V → K)
    (hU : FlatOn U T) (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ z : Chain V) (n k : ℤ)
    (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ) (hloop : bd pQ = -bd pP)
    (hcov : EdgeCover P Q z) (hcyc : bd z = 0)
    (hred : bd (z.filter fun e => e.1 ∈ P ∧ e.2 ∈ P) = n • bd pP)
    (hz : ∀ m : ℤ, m • z ∈ boundaries T → m = 0)
    (hγk : (pP + pQ) - k • z ∈ boundaries T) :
    hol U (pP + pQ) = hol U z ∨ hol U (pP + pQ) = -hol U z := by
  obtain ⟨scP, scQ, hsplit⟩ := split_of_edgeCover z hcov
  have hzn := crossing_generates hP hQ pP pQ _ _ n sP sQ scP scQ hloop
    (by rw [hsplit]; exact hcyc) hred
  rw [hsplit] at hzn
  exact hol_crossing_pm U hU z (pP + pQ) n k hz hzn hγk

/-! ### The reduction step: degree-zero 0-chains on a connected set are boundaries -/

/-- Degree (augmentation) of a 0-chain. -/
noncomputable def degHom : (V →₀ ℤ) →+ ℤ :=
  Finsupp.liftAddHom fun _ : V => AddMonoidHom.id ℤ

@[simp] theorem degHom_single (v : V) (k : ℤ) : degHom (Finsupp.single v k) = k := by
  simp [degHom]

/-- Boundaries have degree zero. -/
theorem degHom_bd (c : Chain V) : degHom (bd c) = 0 := by
  have : degHom.comp (bd (V := V)) = 0 := by
    apply Finsupp.addHom_ext
    rintro ⟨a, b⟩ k
    simp [bd_single, map_zsmul, map_sub]
  exact DFunLike.congr_fun this c

theorem SupportedIn.finset_sum {ι : Type*} {S : Set V} (s : Finset ι) (f : ι → Chain V)
    (h : ∀ i ∈ s, SupportedIn S (f i)) : SupportedIn S (∑ i ∈ s, f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa using supportedIn_zero S
  | insert a s ha ih =>
    rw [Finset.sum_insert ha]
    exact (h a (Finset.mem_insert_self a s)).add
      (ih fun i hi => h i (Finset.mem_insert_of_mem hi))

/-- The vertex boundary of a chain supported in `S` is supported in `S`. -/
theorem bd_supported {S : Set V} {c : Chain V} (hc : SupportedIn S c) :
    ∀ v ∈ (bd c).support, v ∈ S := by
  intro v hv
  have hsum : bd c = c.sum fun e k => k • (Finsupp.single e.1 1 - Finsupp.single e.2 1) := by
    simp only [bd, Finsupp.liftAddHom_apply]
    exact Finsupp.sum_congr fun e _ => zmultiplesHom_apply _ _ _
  rw [hsum] at hv
  obtain ⟨e, he, hve⟩ := Finset.mem_biUnion.mp (Finsupp.support_sum hv)
  have h1 := Finsupp.support_smul hve
  rcases Finset.mem_union.mp (Finsupp.support_sub h1) with h2 | h2
  · rw [Finset.mem_singleton.mp (Finsupp.support_single_subset h2)]; exact (hc e he).1
  · rw [Finset.mem_singleton.mp (Finsupp.support_single_subset h2)]; exact (hc e he).2

/-- Two vertices joined inside `C`: a chain in `C` with boundary `u − v`. -/
def Joined (C : Set V) (u v : V) : Prop :=
  ∃ r : Chain V, SupportedIn C r ∧ bd r = Finsupp.single u 1 - Finsupp.single v 1

open Classical in
/-- **A degree-zero 0-chain supported on a connected set is a boundary there.** -/
theorem deg0_is_boundary (C : Set V) (u₀ : V) (hJ : ∀ v ∈ C, Joined C v u₀)
    (b : V →₀ ℤ) (hb : ∀ v ∈ b.support, v ∈ C) (hdeg : degHom b = 0) :
    ∃ r : Chain V, SupportedIn C r ∧ bd r = b := by
  let rv : V → Chain V := fun v => if h : v ∈ C then Classical.choose (hJ v h) else 0
  have hrv : ∀ v ∈ b.support, SupportedIn C (rv v) ∧
      bd (rv v) = Finsupp.single v 1 - Finsupp.single u₀ 1 := by
    intro v hv
    simp only [rv, dif_pos (hb v hv)]
    exact Classical.choose_spec (hJ v (hb v hv))
  refine ⟨∑ v ∈ b.support, b v • rv v,
    SupportedIn.finset_sum _ _ fun v hv => (hrv v hv).1.zsmul _, ?_⟩
  rw [map_sum]
  have step : ∀ v ∈ b.support, bd (b v • rv v)
      = Finsupp.single v (b v) - b v • Finsupp.single u₀ 1 := by
    intro v hv
    rw [map_zsmul, (hrv v hv).2, smul_sub, Finsupp.smul_single_one]
  rw [Finset.sum_congr rfl step, Finset.sum_sub_distrib, ← Finset.sum_smul]
  have h1 : ∑ v ∈ b.support, Finsupp.single v (b v) = b := Finsupp.sum_single b
  have h2 : ∑ v ∈ b.support, b v = degHom b := by
    simp [degHom, Finsupp.liftAddHom_apply, Finsupp.sum]
  rw [h1, h2, hdeg, zero_smul, sub_zero]

open Classical in
/-- **The reduction**, for two components `C₁ ∋ a₁`, `C₂ ∋ a₂` of `P ∩ Q`:
a `P`-chain `cP` and `Q`-chain `cQ` with `∂cP = −∂cQ` can be modified (by
chains inside `P ∩ Q`) so that the new `P`-part has boundary `n·(a₁ − a₂)`,
with the same total. -/
theorem reduce_two_components (C₁ C₂ : Set V) (a₁ a₂ : V)
    (hC : ∀ v, v ∈ P ∧ v ∈ Q → v ∈ C₁ ∨ v ∈ C₂) (h₁PQ : C₁ ⊆ P ∩ Q) (h₂PQ : C₂ ⊆ P ∩ Q)
    (ha₁ : a₁ ∈ C₁) (ha₂ : a₂ ∈ C₂)
    (hJ₁ : ∀ v ∈ C₁, Joined C₁ v a₁) (hJ₂ : ∀ v ∈ C₂, Joined C₂ v a₂)
    (cP cQ : Chain V) (sP : SupportedIn P cP) (sQ : SupportedIn Q cQ)
    (hcyc : bd (cP + cQ) = 0) :
    ∃ (cP' cQ' : Chain V) (n : ℤ), SupportedIn P cP' ∧ SupportedIn Q cQ' ∧
      cP' + cQ' = cP + cQ ∧
      bd cP' = n • (Finsupp.single a₁ 1 - Finsupp.single a₂ 1) := by
  set b := bd cP with hbdef
  have hbQ : b = -bd cQ := by
    rw [map_add] at hcyc; exact eq_neg_of_add_eq_zero_left hcyc
  -- the boundary lives in P ∩ Q
  have hbPQ : ∀ v ∈ b.support, v ∈ P ∧ v ∈ Q := by
    intro v hv
    refine ⟨bd_supported sP v hv, ?_⟩
    have : v ∈ (bd cQ).support := by rw [hbQ, Finsupp.support_neg] at hv; exact hv
    exact bd_supported sQ v this
  let b₁ := b.filter (· ∈ C₁)
  let b₂ := b.filter (fun v => ¬ v ∈ C₁)
  have hb12 : b₁ + b₂ = b := Finsupp.filter_pos_add_filter_neg _ _
  set n := degHom b₁ with hn
  have hdeg : degHom b₁ + degHom b₂ = 0 := by rw [← map_add, hb12, hbdef, degHom_bd]
  have hs₁ : ∀ v ∈ (b₁ - n • Finsupp.single a₁ 1).support, v ∈ C₁ := by
    intro v hv
    rcases Finset.mem_union.mp (Finsupp.support_sub hv) with h | h
    · rw [Finsupp.support_filter, Finset.mem_filter] at h; exact h.2
    · rw [Finset.mem_singleton.mp (Finsupp.support_single_subset (Finsupp.support_smul h))]; exact ha₁
  have hs₂ : ∀ v ∈ (b₂ + n • Finsupp.single a₂ 1).support, v ∈ C₂ := by
    intro v hv
    rcases Finset.mem_union.mp (Finsupp.support_add hv) with h | h
    · rw [Finsupp.support_filter, Finset.mem_filter] at h
      exact (hC v (hbPQ v h.1)).resolve_left h.2
    · rw [Finset.mem_singleton.mp (Finsupp.support_single_subset (Finsupp.support_smul h))]; exact ha₂
  obtain ⟨r₁, sr₁, hr₁⟩ := deg0_is_boundary C₁ a₁ hJ₁ _ hs₁
    (by rw [map_sub, map_zsmul, degHom_single, smul_eq_mul, mul_one, hn, sub_self])
  obtain ⟨r₂, sr₂, hr₂⟩ := deg0_is_boundary C₂ a₂ hJ₂ _ hs₂
    (by rw [map_add, map_zsmul, degHom_single, smul_eq_mul, mul_one, hn]; linarith)
  refine ⟨cP - r₁ - r₂, cQ + r₁ + r₂, n,
    (sP.sub (sr₁.mono fun v h => (h₁PQ h).1)).sub (sr₂.mono fun v h => (h₂PQ h).1),
    (sQ.add (sr₁.mono fun v h => (h₁PQ h).2)).add (sr₂.mono fun v h => (h₂PQ h).2),
    by abel, ?_⟩
  rw [map_sub, map_sub, hr₁, hr₂, ← hbdef, ← hb12, smul_sub]
  abel

open Classical in
/-- **Full statement, no assumed reduction.**  If `P ∩ Q` consists of two
internally joined components `C₁ ∋ a₁` and `C₂ ∋ a₂`, cycles in each shadow
bound, the shadows cover the generator's edges, the generator `z` has
infinite order, and the crossing loop `γ = pP + pQ` (from `a₁` to `a₂` in `P`,
back in `Q`) is a multiple of `z`, then a flat cochain has holonomy `± hol z`
on `γ`. -/
theorem hol_crossing_pm_full {K : Type*} [AddCommGroup K] (U : V → V → K)
    (hU : FlatOn U T) (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (C₁ C₂ : Set V) (a₁ a₂ : V)
    (hC : ∀ v, v ∈ P ∧ v ∈ Q → v ∈ C₁ ∨ v ∈ C₂) (h₁PQ : C₁ ⊆ P ∩ Q) (h₂PQ : C₂ ⊆ P ∩ Q)
    (ha₁ : a₁ ∈ C₁) (ha₂ : a₂ ∈ C₂)
    (hJ₁ : ∀ v ∈ C₁, Joined C₁ v a₁) (hJ₂ : ∀ v ∈ C₂, Joined C₂ v a₂)
    (pP pQ z : Chain V) (k : ℤ)
    (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ)
    (hpP : bd pP = Finsupp.single a₁ 1 - Finsupp.single a₂ 1) (hloop : bd pQ = -bd pP)
    (hcov : EdgeCover P Q z) (hcyc : bd z = 0)
    (hz : ∀ m : ℤ, m • z ∈ boundaries T → m = 0)
    (hγk : (pP + pQ) - k • z ∈ boundaries T) :
    hol U (pP + pQ) = hol U z ∨ hol U (pP + pQ) = -hol U z := by
  obtain ⟨scP, scQ, hsplit⟩ := split_of_edgeCover z hcov
  obtain ⟨cP', cQ', n, sP', sQ', hsum, hbd⟩ :=
    reduce_two_components C₁ C₂ a₁ a₂ hC h₁PQ h₂PQ ha₁ ha₂ hJ₁ hJ₂ _ _ scP scQ
      (by rw [hsplit]; exact hcyc)
  have hzn := crossing_generates hP hQ pP pQ cP' cQ' n sP sQ sP' sQ' hloop
    (by rw [hsum, hsplit]; exact hcyc) (by rw [hbd, hpP])
  rw [hsum, hsplit] at hzn
  exact hol_crossing_pm U hU z (pP + pQ) n k hz hzn hγk

end UnifiedTheory.Audit.KFCausalMayerVietoris
