/-
  Audit/KFCausalHolonomyBornProjectiveGrowth.lean

  BORN-COMPLETE PROJECTIVE CAUSAL HOLONOMY GROWTH

  This module promotes the finite causal-holonomy interference law to a
  microscopic operator process over arbitrary finite depth.

  Two projectivity laws are proved.  Kraus completeness gives the partial-
  trace law, in which an unobserved next record is summed with the SAME
  outcome on the ket and bra sides:

      sum_e D(e :: h, e :: k) = D(h,k).

  The special causal-holonomy operators also sum coherently to identity.
  Therefore they satisfy the stronger quantum-measure cylinder law obtained
  by independently summing every future ket and bra branch.  The same finite
  law is consequently both Born complete and exhaustively projective.

  Zero sorry. Zero custom axioms.
-/

import UnifiedTheory.Audit.KFCausalHolonomyInterferenceLaw
import UnifiedTheory.LayerB.KrausDephasingSemigroup

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFCausalHolonomyBornProjectiveGrowth

noncomputable section

open scoped BigOperators ComplexConjugate ComplexOrder
open Matrix
open UnifiedTheory.LayerB.Kraus
open UnifiedTheory.Audit.KFCubicSheetIntrinsicCarrier
open UnifiedTheory.Audit.KFCausalHolonomyInterferenceLaw
open UnifiedTheory.Audit.KFOrientationCPChannelTower
open UnifiedTheory.Audit.KFOrientationSpinOne
open UnifiedTheory.Audit.KFOrientationPathQuantum
open UnifiedTheory.Audit.KFOrientationGrowthDecoherence
open UnifiedTheory.Audit.KFOrientationHistoryRigidity
open UnifiedTheory.Audit.KFOrientationHigherRankDecoherence

/-! ## 1. Generic record-path projectivity of every Kraus instrument -/

/-- Operator accumulated along a finite record path.  A newly resolved
outcome acts on the left, so refinement is list cons. -/
def recordPathOperator {m k : ℕ} (instrument : KrausRepresentation m m k) :
    List (Fin k) → Matrix (Fin m) (Fin m) ℂ
  | [] => 1
  | outcome :: history => instrument.K outcome * recordPathOperator instrument history

/-- Cross operator of two recorded histories. -/
def recordCrossOperator {m k : ℕ} (instrument : KrausRepresentation m m k)
    (first second : List (Fin k)) : Matrix (Fin m) (Fin m) ℂ :=
  (recordPathOperator instrument second).conjTranspose *
    recordPathOperator instrument first

/-- **Matched-cylinder operator projectivity.**  Tracing out one future
record preserves every cross operator, not merely the diagonal probabilities.
This is the operator form of cylinder consistency. -/
theorem recordCrossOperator_sum_cons {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (first second : List (Fin k)) :
    (∑ outcome : Fin k,
      recordCrossOperator instrument (outcome :: first) (outcome :: second)) =
      recordCrossOperator instrument first second := by
  unfold recordCrossOperator
  simp_rw [recordPathOperator, Matrix.conjTranspose_mul]
  have hTerm (outcome : Fin k) :
      ((recordPathOperator instrument second)ᴴ * (instrument.K outcome)ᴴ) *
          (instrument.K outcome * recordPathOperator instrument first) =
        (recordPathOperator instrument second)ᴴ *
          ((instrument.K outcome)ᴴ * instrument.K outcome) *
            recordPathOperator instrument first := by
    simp only [Matrix.mul_assoc]
  simp_rw [hTerm]
  rw [← Matrix.sum_mul, ← Matrix.mul_sum]
  rw [instrument.complete, Matrix.mul_one]

/-! ## 2. Gram kernels generated by recorded operator paths -/

/-- Flatten a matrix into the finite coordinate space used by the existing
strong-positivity theorem. -/
def flattenMatrix {m : ℕ} (matrix : Matrix (Fin m) (Fin m) ℂ) :
    Fin m × Fin m → ℂ :=
  fun coordinate => matrix coordinate.1 coordinate.2

/-- Hilbert--Schmidt pairing is the trace pairing. -/
theorem finiteVectorInner_flattenMatrix {m : ℕ}
    (first second : Matrix (Fin m) (Fin m) ℂ) :
    finiteVectorInner (flattenMatrix first) (flattenMatrix second) =
      Matrix.trace (first * secondᴴ) := by
  unfold finiteVectorInner flattenMatrix Matrix.trace
  rw [Fintype.sum_prod_type]
  apply Finset.sum_congr rfl
  intro row _hrow
  simp [Matrix.mul_apply, Matrix.conjTranspose_apply]

/-- A seed operator is propagated down every record path and flattened as a
finite carrier amplitude.  Taking the seed to be a square root of a density
matrix recovers the usual operator-history decoherence functional. -/
def recordOperatorAmplitude {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (seed : Matrix (Fin m) (Fin m) ℂ)
    (history : List (Fin k)) : Fin m × Fin m → ℂ :=
  flattenMatrix (recordPathOperator instrument history * seed)

/-- Operator-history Gram kernel. -/
def recordOperatorKernel {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (seed : Matrix (Fin m) (Fin m) ℂ) :
    GrowthDecoherenceFunctional (List (Fin k)) :=
  vectorAmplitudeKernel (recordOperatorAmplitude instrument seed)

/-- Every finite family of record histories has a positive semidefinite
decoherence matrix. -/
theorem recordOperatorKernel_stronglyPositive {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (seed : Matrix (Fin m) (Fin m) ℂ) :
    IsStronglyPositiveGrowthFunctional (recordOperatorKernel instrument seed) :=
  vectorAmplitudeKernel_stronglyPositive _

/-- Trace form of the operator-history kernel. -/
theorem recordOperatorKernel_eq_trace {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (seed : Matrix (Fin m) (Fin m) ℂ)
    (first second : List (Fin k)) :
    recordOperatorKernel instrument seed first second =
      Matrix.trace
        ((recordPathOperator instrument first * seed) *
          (recordPathOperator instrument second * seed)ᴴ) := by
  exact finiteVectorInner_flattenMatrix _ _

/-- **Born-complete cylinder projectivity.**  Summing over the same
unobserved outcome on both sides is exactly the trace-preserving Kraus map,
so the decoherence kernel is preserved at every history and every depth. -/
theorem recordOperatorKernel_sum_cons {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (seed : Matrix (Fin m) (Fin m) ℂ)
    (first second : List (Fin k)) :
    (∑ outcome : Fin k,
      recordOperatorKernel instrument seed (outcome :: first) (outcome :: second)) =
      recordOperatorKernel instrument seed first second := by
  simp_rw [recordOperatorKernel_eq_trace]
  rw [← Matrix.trace_sum]
  let cross : Matrix (Fin m) (Fin m) ℂ :=
    (recordPathOperator instrument first * seed) *
      (recordPathOperator instrument second * seed)ᴴ
  have hTerm (outcome : Fin k) :
      (recordPathOperator instrument (outcome :: first) * seed) *
          (recordPathOperator instrument (outcome :: second) * seed)ᴴ =
        instrument.K outcome * cross * (instrument.K outcome)ᴴ := by
    unfold cross
    simp only [recordPathOperator, Matrix.conjTranspose_mul, Matrix.mul_assoc]
  simp_rw [hTerm]
  change Matrix.trace (instrument.apply cross) = Matrix.trace cross
  exact instrument.trace_apply cross

/-- If the branch operators themselves sum to identity, their vector
amplitudes are exhaustively projective, not only Born complete. -/
theorem recordOperatorAmplitude_sum_cons_of_sum_eq_one {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (seed : Matrix (Fin m) (Fin m) ℂ)
    (hCoherent : (∑ outcome : Fin k, instrument.K outcome) =
      (1 : Matrix (Fin m) (Fin m) ℂ))
    (history : List (Fin k)) (coordinate : Fin m × Fin m) :
    (∑ outcome : Fin k,
      recordOperatorAmplitude instrument seed (outcome :: history) coordinate) =
      recordOperatorAmplitude instrument seed history coordinate := by
  have hPath :
      (∑ outcome : Fin k,
        recordPathOperator instrument (outcome :: history) * seed) =
        recordPathOperator instrument history * seed := by
    simp_rw [recordPathOperator]
    rw [← Matrix.sum_mul, ← Matrix.sum_mul, hCoherent, Matrix.one_mul]
  change (∑ outcome : Fin k,
      (recordPathOperator instrument (outcome :: history) * seed)
        coordinate.1 coordinate.2) =
    (recordPathOperator instrument history * seed) coordinate.1 coordinate.2
  rw [← Matrix.sum_apply]
  exact congr_fun (congr_fun hPath coordinate.1) coordinate.2

/-- **Exhaustive double-cylinder projectivity.**  When branch operators are
both Born complete and coherently exhaustive, independently refining ket and
bra and summing every pair of children reproduces the parent kernel.  This is
the original quantum-measure cylinder law, not merely matched partial trace. -/
theorem recordOperatorKernel_double_sum_cons_of_sum_eq_one {m k : ℕ}
    (instrument : KrausRepresentation m m k)
    (seed : Matrix (Fin m) (Fin m) ℂ)
    (hCoherent : (∑ outcome : Fin k, instrument.K outcome) =
      (1 : Matrix (Fin m) (Fin m) ℂ))
    (first second : List (Fin k)) :
    (∑ left : Fin k, ∑ right : Fin k,
      recordOperatorKernel instrument seed (left :: first) (right :: second)) =
      recordOperatorKernel instrument seed first second := by
  unfold recordOperatorKernel vectorAmplitudeKernel finiteVectorInner
  let amplitude := recordOperatorAmplitude instrument seed
  change (∑ left : Fin k, ∑ right : Fin k, ∑ coordinate : Fin m × Fin m,
      amplitude (left :: first) coordinate *
        star (amplitude (right :: second) coordinate)) =
    ∑ coordinate : Fin m × Fin m,
      amplitude first coordinate * star (amplitude second coordinate)
  calc
    (∑ left : Fin k, ∑ right : Fin k, ∑ coordinate : Fin m × Fin m,
        amplitude (left :: first) coordinate *
          star (amplitude (right :: second) coordinate)) =
        ∑ coordinate : Fin m × Fin m, ∑ left : Fin k, ∑ right : Fin k,
          amplitude (left :: first) coordinate *
            star (amplitude (right :: second) coordinate) := by
      calc
        _ = ∑ left : Fin k, ∑ coordinate : Fin m × Fin m, ∑ right : Fin k,
            amplitude (left :: first) coordinate *
              star (amplitude (right :: second) coordinate) := by
          apply Finset.sum_congr rfl
          intro left _hLeft
          exact Finset.sum_comm
        _ = _ := Finset.sum_comm
    _ = ∑ coordinate : Fin m × Fin m,
        (∑ left : Fin k, amplitude (left :: first) coordinate) *
          star (∑ right : Fin k, amplitude (right :: second) coordinate) := by
      apply Finset.sum_congr rfl
      intro coordinate _hCoordinate
      rw [star_sum, Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro left _hLeft
      rw [Finset.mul_sum]
    _ = _ := by
      dsimp [amplitude]
      simp_rw [recordOperatorAmplitude_sum_cons_of_sum_eq_one
        instrument seed hCoherent]

/-! ## 3. The exact three-sheet holonomy instrument -/

/-- The native three-cycle on the ambient three-sheet permutation module. -/
def cyclicSheetOperator : SquareMatrix 3 :=
  !![(0 : ℂ), 0, 1;
     1, 0, 0;
     0, 1, 0]

/-- Orthogonal projector from the permutation module onto its trace-zero
rank-two standard carrier. -/
def zeroSumSheetProjector : SquareMatrix 3 :=
  !![(2 / 3 : ℂ), -1 / 3, -1 / 3;
     -1 / 3, 2 / 3, -1 / 3;
     -1 / 3, -1 / 3, 2 / 3]

/-- Canonical square root of the maximally mixed trace-zero carrier state:
`sqrt(ρ_W) = P_W / sqrt(2)`. -/
def zeroSumSheetDensityRoot : SquareMatrix 3 :=
  (1 / (spinOneSqrtTwo : ℂ)) • zeroSumSheetProjector

/-- First coherent branch, `(I - i C)/2`, where `C` is the native
three-cycle. -/
def identityRecordKraus : SquareMatrix 3 :=
  !![(1 / 2 : ℂ), 0, -Complex.I / 2;
     -Complex.I / 2, 1 / 2, 0;
     0, -Complex.I / 2, 1 / 2]

/-- Second coherent branch, `(I + i C)/2`. -/
def threeCycleRecordKraus : SquareMatrix 3 :=
  !![(1 / 2 : ℂ), 0, Complex.I / 2;
     Complex.I / 2, 1 / 2, 0;
     0, Complex.I / 2, 1 / 2]

/-- The two microscopic record alternatives. -/
def causalHolonomyKrausOperator (outcome : Fin 2) : SquareMatrix 3 :=
  if outcome = 0 then identityRecordKraus else threeCycleRecordKraus

/-- The record operators are Born complete. -/
theorem causalHolonomyKrausOperator_complete :
    (∑ outcome : Fin 2,
      (causalHolonomyKrausOperator outcome)ᴴ *
        causalHolonomyKrausOperator outcome) = (1 : SquareMatrix 3) := by
  rw [Fin.sum_univ_two]
  ext row column
  fin_cases row <;> fin_cases column <;>
    simp [causalHolonomyKrausOperator, identityRecordKraus,
      threeCycleRecordKraus, Matrix.mul_apply, Matrix.conjTranspose_apply,
      Fin.sum_univ_three]
  all_goals ring_nf
  all_goals norm_num [Complex.I_mul_I, map_ofNat]

/-- **Coherent exhaustivity.**  The same two branch operators also sum to the
identity.  This is stronger than trace preservation and is possible because
their cross term is purely imaginary. -/
theorem causalHolonomyKrausOperator_sum_eq_one :
    (∑ outcome : Fin 2, causalHolonomyKrausOperator outcome) =
      (1 : SquareMatrix 3) := by
  rw [Fin.sum_univ_two]
  ext row column
  fin_cases row <;> fin_cases column <;>
    simp [causalHolonomyKrausOperator, identityRecordKraus,
      threeCycleRecordKraus]
  all_goals ring

/-- **Microscopic causal-holonomy instrument.**  This is an explicit
trace-preserving two-outcome quantum operation, not a fitted 2x2 kernel. -/
def causalHolonomyInstrument : KrausRepresentation 3 3 2 where
  K := causalHolonomyKrausOperator
  complete := causalHolonomyKrausOperator_complete

/-- The causal-holonomy instrument is completely positive and trace
preserving. -/
theorem causalHolonomyInstrument_isCPTP :
    IsCPTP causalHolonomyInstrument.toLinearMap :=
  kraus_isCPTP causalHolonomyInstrument

/-- Its operator-history decoherence kernel at every finite record depth. -/
def causalHolonomyBornKernel :
    GrowthDecoherenceFunctional (List (Fin 2)) :=
  recordOperatorKernel causalHolonomyInstrument zeroSumSheetDensityRoot

/-- Every finite family of arbitrarily deep histories is strongly positive. -/
theorem causalHolonomyBornKernel_stronglyPositive :
    IsStronglyPositiveGrowthFunctional causalHolonomyBornKernel :=
  recordOperatorKernel_stronglyPositive _ _

/-- **All-depth cylinder consistency.**  Discarding the same next causal
record from ket and bra leaves every pair of cylinder histories unchanged. -/
theorem causalHolonomyBornKernel_projective
    (first second : List (Fin 2)) :
    (∑ outcome : Fin 2,
      causalHolonomyBornKernel (outcome :: first) (outcome :: second)) =
      causalHolonomyBornKernel first second :=
  recordOperatorKernel_sum_cons _ _ _ _

/-- The stronger, independently refined ket/bra cylinder law also holds. -/
theorem causalHolonomyBornKernel_exhaustively_projective
    (first second : List (Fin 2)) :
    (∑ left : Fin 2, ∑ right : Fin 2,
      causalHolonomyBornKernel (left :: first) (right :: second)) =
      causalHolonomyBornKernel first second :=
  recordOperatorKernel_double_sum_cons_of_sum_eq_one _ _
    causalHolonomyKrausOperator_sum_eq_one _ _

/-! ## 4. One-step recovery and arbitrary-depth channel composition -/

/-- Restriction of the operator process to its two one-step histories. -/
def causalHolonomyBornOneStepKernel : SquareMatrix 2 :=
  fun first second => causalHolonomyBornKernel [first] [second]

set_option maxHeartbeats 4000000 in
/-- The microscopic instrument recovers the independently derived finite
holonomy law exactly, entry by entry. -/
theorem causalHolonomyBornOneStepKernel_eq_finiteLaw :
    causalHolonomyBornOneStepKernel = holonomyChiralityPairKernel := by
  ext first second
  fin_cases first <;> fin_cases second
  all_goals
    simp [causalHolonomyBornOneStepKernel, causalHolonomyBornKernel,
      recordOperatorKernel, vectorAmplitudeKernel, finiteVectorInner,
      recordOperatorAmplitude, flattenMatrix, causalHolonomyInstrument,
      causalHolonomyKrausOperator, identityRecordKraus,
      threeCycleRecordKraus, zeroSumSheetDensityRoot,
      zeroSumSheetProjector, recordPathOperator, holonomyChiralityPairKernel,
      equalBornQuadratureWeight, threeCycleHolonomy,
      causalHolonomyVisibilityKernel_eq, relativeHolonomy,
      causalHolonomyVisibility, standardS3Character,
      directionFixedPointCount, Matrix.mul_apply, Fintype.sum_prod_type,
      Fin.sum_univ_three, Equiv.swap_apply_def, Equiv.Perm.mul_apply]
  all_goals
    field_simp [spinOneSqrtTwo_ne_zero]
  all_goals
    ring_nf
  all_goals
    norm_num [← pow_two, spinOneSqrtTwo_sq_complex, Complex.I_mul_I,
      map_ofNat]
  all_goals ring

/-- In particular the one-step operator law is the normalized strict-rank-two
balanced kernel with coherence `i/4`. -/
theorem causalHolonomyBornOneStepKernel_eq_balanced :
    causalHolonomyBornOneStepKernel = balancedHistoryKernel (1 / 4) := by
  rw [causalHolonomyBornOneStepKernel_eq_finiteLaw,
    holonomyChiralityPairKernel_eq_balanced]

/-- The empty-history state is normalized. -/
theorem causalHolonomyBornKernel_root_normalized :
    causalHolonomyBornKernel [] [] = 1 := by
  have hProjective := causalHolonomyBornKernel_exhaustively_projective [] []
  rw [Fin.sum_univ_two, Fin.sum_univ_two, Fin.sum_univ_two] at hProjective
  rw [← hProjective]
  change causalHolonomyBornOneStepKernel 0 0 +
      causalHolonomyBornOneStepKernel 0 1 +
      (causalHolonomyBornOneStepKernel 1 0 +
        causalHolonomyBornOneStepKernel 1 1) = 1
  rw [causalHolonomyBornOneStepKernel_eq_finiteLaw]
  rw [holonomyChiralityPairKernel_eq_balanced]
  norm_num [balancedHistoryKernel]
  ring

/-- N-fold composition of the microscopic instrument. -/
def causalHolonomyInstrumentAtDepth (depth : ℕ) :
    KrausRepresentation 3 3 (2 ^ depth) :=
  nfoldCompose depth causalHolonomyInstrument

/-- Every finite-depth evolution is a completely positive trace-preserving
map. -/
theorem causalHolonomyInstrumentAtDepth_isCPTP (depth : ℕ) :
    IsCPTP (causalHolonomyInstrumentAtDepth depth).toLinearMap :=
  kraus_isCPTP _

/-- The all-depth result: exact finite recovery, strong positivity for every
finite sample, root normalization, matched-cylinder projectivity at every
prefix, and CPTP dynamics at every depth. -/
theorem causalHolonomyBorn_projective_growth_complete :
    causalHolonomyBornOneStepKernel = balancedHistoryKernel (1 / 4)
      ∧ IsStronglyPositiveGrowthFunctional causalHolonomyBornKernel
      ∧ causalHolonomyBornKernel [] [] = 1
      ∧ (∀ first second : List (Fin 2),
          (∑ outcome : Fin 2,
            causalHolonomyBornKernel (outcome :: first) (outcome :: second)) =
            causalHolonomyBornKernel first second)
      ∧ (∀ first second : List (Fin 2),
          (∑ left : Fin 2, ∑ right : Fin 2,
            causalHolonomyBornKernel (left :: first) (right :: second)) =
            causalHolonomyBornKernel first second)
      ∧ (∀ depth : ℕ,
          IsCPTP (causalHolonomyInstrumentAtDepth depth).toLinearMap) := by
  exact ⟨causalHolonomyBornOneStepKernel_eq_balanced,
    causalHolonomyBornKernel_stronglyPositive,
    causalHolonomyBornKernel_root_normalized,
    causalHolonomyBornKernel_projective,
    causalHolonomyBornKernel_exhaustively_projective,
    causalHolonomyInstrumentAtDepth_isCPTP⟩

/-! ## 5. Quadrature rigidity of an unbiased Born-complete split -/

/-- General first branch `(I + phase C)/2` in the symmetric two-branch
three-cycle ansatz. -/
def phaseSplitFirstKraus (phase : ℂ) : SquareMatrix 3 :=
  !![(1 / 2 : ℂ), 0, phase / 2;
     phase / 2, 1 / 2, 0;
     0, phase / 2, 1 / 2]

/-- Complementary branch `(I - phase C)/2`. -/
def phaseSplitSecondKraus (phase : ℂ) : SquareMatrix 3 :=
  !![(1 / 2 : ℂ), 0, -phase / 2;
     -phase / 2, 1 / 2, 0;
     0, -phase / 2, 1 / 2]

/-- Coherent exhaustivity holds for every phase in the symmetric ansatz. -/
theorem phaseSplit_sum_eq_one (phase : ℂ) :
    phaseSplitFirstKraus phase + phaseSplitSecondKraus phase =
      (1 : SquareMatrix 3) := by
  ext row column
  fin_cases row <;> fin_cases column <;>
    simp [phaseSplitFirstKraus, phaseSplitSecondKraus] <;> ring

/-- **Born-completeness classification of the symmetric split.**  Its two
operators form a trace-preserving Kraus family exactly when the relative
phase has unit modulus. -/
theorem phaseSplit_complete_iff_unitNorm (phase : ℂ) :
    (phaseSplitFirstKraus phase)ᴴ * phaseSplitFirstKraus phase +
        (phaseSplitSecondKraus phase)ᴴ * phaseSplitSecondKraus phase =
        (1 : SquareMatrix 3) ↔
      star phase * phase = 1 := by
  constructor
  · intro hComplete
    have h00 := congr_fun (congr_fun hComplete (0 : Fin 3)) (0 : Fin 3)
    simp [phaseSplitFirstKraus, phaseSplitSecondKraus, Matrix.mul_apply,
      Matrix.conjTranspose_apply, Fin.sum_univ_three] at h00
    rw [map_ofNat] at h00
    have hProduct : (starRingEnd ℂ) phase * phase = 1 := by
      linear_combination 2 * h00
    exact hProduct
  · intro hNorm
    change (starRingEnd ℂ) phase * phase = 1 at hNorm
    ext row column
    fin_cases row <;> fin_cases column <;>
      simp [phaseSplitFirstKraus, phaseSplitSecondKraus, Matrix.mul_apply,
        Matrix.conjTranspose_apply, Fin.sum_univ_three]
    all_goals rw [map_ofNat]
    all_goals ring_nf
    all_goals rw [hNorm]
    all_goals norm_num [map_ofNat]

/-- The concrete all-depth law is the negative-quadrature member of the
classified symmetric family. -/
theorem concreteKraus_eq_negativeQuadratureSplit :
    identityRecordKraus = phaseSplitFirstKraus (-Complex.I)
      ∧ threeCycleRecordKraus = phaseSplitSecondKraus (-Complex.I) := by
  constructor <;> ext row column <;> fin_cases row <;> fin_cases column <;>
    simp [identityRecordKraus, threeCycleRecordKraus,
      phaseSplitFirstKraus, phaseSplitSecondKraus]

/-- Raw one-step Gram kernel of a general symmetric phase split on the same
canonical trace-zero carrier state. -/
def phaseSplitBornKernel (phase : ℂ) : SquareMatrix 2 :=
  vectorAmplitudeKernel (fun outcome : Fin 2 =>
    flattenMatrix
      ((if outcome = 0 then phaseSplitFirstKraus phase
        else phaseSplitSecondKraus phase) * zeroSumSheetDensityRoot))

set_option maxHeartbeats 4000000 in
/-- The actual branch-weight imbalance is the Hermitian part of the phase.
This is the operator calculation connecting equal Born weights to zero real
phase bias. -/
theorem phaseSplitBornKernel_diagonal_difference (phase : ℂ) :
    phaseSplitBornKernel phase 0 0 - phaseSplitBornKernel phase 1 1 =
      -(phase + star phase) / 4 := by
  simp [phaseSplitBornKernel, vectorAmplitudeKernel, finiteVectorInner,
    flattenMatrix, phaseSplitFirstKraus, phaseSplitSecondKraus,
    zeroSumSheetDensityRoot, zeroSumSheetProjector, Matrix.mul_apply,
    Fintype.sum_prod_type, Fin.sum_univ_three]
  field_simp [spinOneSqrtTwo_ne_zero]
  ring_nf
  norm_num [← pow_two, spinOneSqrtTwo_sq_complex, map_ofNat]
  ring

/-- Equal probabilities for the two actual one-step branches are exactly the
zero-real-bias condition. -/
theorem phaseSplitBornKernel_balanced_iff (phase : ℂ) :
    phaseSplitBornKernel phase 0 0 = phaseSplitBornKernel phase 1 1 ↔
      phase + star phase = 0 := by
  constructor
  · intro hEqual
    have hDifference := phaseSplitBornKernel_diagonal_difference phase
    rw [hEqual, sub_self] at hDifference
    field_simp at hDifference
    linear_combination hDifference
  · intro hBalance
    apply sub_eq_zero.mp
    rw [phaseSplitBornKernel_diagonal_difference, hBalance]
    ring

/-- Algebraic form of the two microscopic requirements on the relative
phase: unit modulus is the scalar content of Born completeness, while a
vanishing real part is the scalar content of equal one-step Born weights for
the real three-cycle character. -/
def IsBornBalancedPhase (phase : ℂ) : Prop :=
  star phase * phase = 1 ∧ phase + star phase = 0

/-- **Quadrature rigidity.**  A complex phase that is simultaneously
Born-normalized and unbiased is exactly one of the two quadrature characters.
There is no continuous phase freedom left. -/
theorem bornBalancedPhase_iff_quadrature (phase : ℂ) :
    IsBornBalancedPhase phase ↔
      phase = Complex.I ∨ phase = -Complex.I := by
  constructor
  · rintro ⟨hNorm, hBalance⟩
    have hRe : phase.re = 0 := by
      have h := congrArg Complex.re hBalance
      simp at h
      linarith
    have hSq : phase.im ^ 2 = 1 := by
      have h := congrArg Complex.re hNorm
      simp [Complex.mul_re] at h
      nlinarith
    rcases (sq_eq_one_iff).mp hSq with hIm | hIm
    · left
      apply Complex.ext <;> simp [hRe, hIm]
    · right
      apply Complex.ext <;> simp [hRe, hIm]
  · rintro (rfl | rfl) <;>
      constructor <;> norm_num [Complex.I_mul_I]

/-- The two surviving phases are exchanged by complex conjugation. -/
theorem quadrature_phases_conjugate :
    star (Complex.I : ℂ) = -Complex.I
      ∧ star (-Complex.I : ℂ) = Complex.I := by
  norm_num

/-- There are exactly two admissible microscopic phases. -/
theorem bornBalancedPhase_exactly_two :
    {phase : ℂ | IsBornBalancedPhase phase} =
      {Complex.I, -Complex.I} := by
  ext phase
  rw [Set.mem_setOf_eq, Set.mem_insert_iff, Set.mem_singleton_iff,
    bornBalancedPhase_iff_quadrature]

/-- **Microscopic phase-selection law, scoped honestly.**  Within the
symmetric local two-branch three-cycle ansatz, Born completeness supplies the
unit-norm premise.  Adding equal one-step Born weights supplies the vanishing
real-bias premise, and the phase is therefore uniquely quadrature up to the
global conjugation gauge. -/
theorem symmetricHolonomySplit_selects_quadrature
    (phase : ℂ)
    (hComplete :
      (phaseSplitFirstKraus phase)ᴴ * phaseSplitFirstKraus phase +
          (phaseSplitSecondKraus phase)ᴴ * phaseSplitSecondKraus phase =
          (1 : SquareMatrix 3))
    (hUnbiased :
      phaseSplitBornKernel phase 0 0 = phaseSplitBornKernel phase 1 1) :
    phase = Complex.I ∨ phase = -Complex.I := by
  rw [phaseSplit_complete_iff_unitNorm] at hComplete
  rw [phaseSplitBornKernel_balanced_iff] at hUnbiased
  exact (bornBalancedPhase_iff_quadrature phase).1 ⟨hComplete, hUnbiased⟩

/-- Final rigidity package: the concrete process is one classified
quadrature branch, the only alternative is its conjugate, and both arise from
the exact completeness-and-balance conditions rather than a continuous phase
choice. -/
theorem causalHolonomy_quadrature_rigidity_complete :
    (identityRecordKraus = phaseSplitFirstKraus (-Complex.I)
      ∧ threeCycleRecordKraus = phaseSplitSecondKraus (-Complex.I))
      ∧ (∀ phase : ℂ,
        IsBornBalancedPhase phase ↔
          phase = Complex.I ∨ phase = -Complex.I)
      ∧ star (Complex.I : ℂ) = -Complex.I := by
  exact ⟨concreteKraus_eq_negativeQuadratureSplit,
    bornBalancedPhase_iff_quadrature,
    quadrature_phases_conjugate.1⟩

#print axioms recordCrossOperator_sum_cons
#print axioms recordOperatorKernel_stronglyPositive
#print axioms recordOperatorKernel_sum_cons
#print axioms recordOperatorKernel_double_sum_cons_of_sum_eq_one
#print axioms causalHolonomyKrausOperator_complete
#print axioms causalHolonomyKrausOperator_sum_eq_one
#print axioms causalHolonomyBornOneStepKernel_eq_finiteLaw
#print axioms causalHolonomyBorn_projective_growth_complete
#print axioms phaseSplit_complete_iff_unitNorm
#print axioms bornBalancedPhase_iff_quadrature
#print axioms symmetricHolonomySplit_selects_quadrature
#print axioms causalHolonomy_quadrature_rigidity_complete

end

end UnifiedTheory.Audit.KFCausalHolonomyBornProjectiveGrowth
