/-
  Audit/KFCausalMayerVietoris.lean
  — THE TWO-SET-COVER (MAYER–VIETORIS) LEMMA BEHIND THE CHAIN-PAIR HOLONOMY

  Companion to KFCausalNerveHolonomy.lean and scripts/ab_chain_pair_holonomy.py.
  In the numerics, a pair p < q splits its chains p < a < q into classes = the
  components of P ∩ Q, where P = J⁺(p) ∩ A and Q = J⁻(q) ∩ A cover the slice
  complex.  The Wilson factor of two classes is the holonomy of a crossing
  loop γ = (path a₁ → a₂ inside P) + (path a₂ → a₁ inside Q).  The observed
  values (0 within one class, ±1 between two classes) are FORCED; this file
  proves why, at the level of integer 1-chains, with no simplicial topology:

  * `same_component_bounds` / `hol_same_component` — if a₁, a₂ are joined
    inside P ∩ Q, and cycles supported in P (resp. Q) bound, the crossing loop
    bounds: holonomy 0.
  * `crossing_independent` — the class of γ does not depend on the paths
    chosen inside P and Q.
  * `crossing_generates` — every cycle that splits as c_P + c_Q with
    ∂c_P = n·∂p_P is homologous to n·γ (the Mayer–Vietoris connecting step).
  * `crossing_is_pm_generator` / `hol_crossing_pm` — if H₁ is generated by z
    of infinite order and γ is a multiple of z, then γ ≡ ±z, so a flat
    cochain has holonomy ±hol(z) on γ.

  "Cycles supported in S bound" is stated directly (`CyclesBound`), which is
  what the argument uses; it is implied by acyclicity of the subcomplex.  The
  reduction of a general cycle to one with ∂c_P = n·∂p_P (moving boundary
  points within each component of P ∩ Q) is a hypothesis, not proved here.

  Zero sorry.  Zero custom axioms.
-/
import Mathlib
import UnifiedTheory.Audit.KFCausalNerveHolonomy

set_option autoImplicit false
set_option linter.unusedSectionVars false

namespace UnifiedTheory.Audit.KFCausalMayerVietoris

open UnifiedTheory.Audit.KFCausalNerveHolonomy

variable {V : Type*} [DecidableEq V]

/-- A chain supported on edges with both endpoints in `S`. -/
def SupportedIn (S : Set V) (c : Chain V) : Prop :=
  ∀ e ∈ c.support, e.1 ∈ S ∧ e.2 ∈ S

theorem supportedIn_zero (S : Set V) : SupportedIn S (0 : Chain V) := by
  intro e he; simp at he

theorem SupportedIn.add {S : Set V} {c d : Chain V} (hc : SupportedIn S c)
    (hd : SupportedIn S d) : SupportedIn S (c + d) := by
  intro e he
  rcases Finset.mem_union.mp (Finsupp.support_add he) with h | h
  · exact hc e h
  · exact hd e h

theorem SupportedIn.neg {S : Set V} {c : Chain V} (hc : SupportedIn S c) :
    SupportedIn S (-c) := by
  intro e he; rw [Finsupp.support_neg] at he; exact hc e he

theorem SupportedIn.sub {S : Set V} {c d : Chain V} (hc : SupportedIn S c)
    (hd : SupportedIn S d) : SupportedIn S (c - d) := by
  rw [sub_eq_add_neg]; exact hc.add hd.neg

theorem SupportedIn.zsmul {S : Set V} {c : Chain V} (hc : SupportedIn S c) (n : ℤ) :
    SupportedIn S (n • c) := by
  intro e he; exact hc e (Finsupp.support_smul he)

theorem SupportedIn.mono {S S' : Set V} (h : S ⊆ S') {c : Chain V} (hc : SupportedIn S c) :
    SupportedIn S' c := fun e he => ⟨h (hc e he).1, h (hc e he).2⟩

/-- Every cycle supported in `S` is a boundary of the declared complex. -/
def CyclesBound (T : Set (V × V × V)) (S : Set V) : Prop :=
  ∀ c : Chain V, SupportedIn S c → bd c = 0 → c ∈ boundaries T

variable {T : Set (V × V × V)} {P Q : Set V}

/-- **Same component ⇒ the crossing loop bounds.**  `r` joins the endpoints
inside `P ∩ Q` (same boundary as `pP`); `pQ` returns inside `Q`. -/
theorem same_component_bounds (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ r : Chain V) (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ)
    (sr : SupportedIn (P ∩ Q) r) (hr : bd r = bd pP) (hloop : bd pQ = -bd pP) :
    pP + pQ ∈ boundaries T := by
  have h1 : pP - r ∈ boundaries T :=
    hP _ (sP.sub (sr.mono Set.inter_subset_left)) (by rw [map_sub, hr, sub_self])
  have h2 : r + pQ ∈ boundaries T :=
    hQ _ ((sr.mono Set.inter_subset_right).add sQ) (by rw [map_add, hr, hloop, add_neg_cancel])
  have := (boundaries T).add_mem h1 h2
  rwa [show pP - r + (r + pQ) = pP + pQ by abel] at this

theorem hol_same_component {K : Type*} [AddCommGroup K] (U : V → V → K) (hU : FlatOn U T)
    (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ r : Chain V) (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ)
    (sr : SupportedIn (P ∩ Q) r) (hr : bd r = bd pP) (hloop : bd pQ = -bd pP) :
    hol U (pP + pQ) = 0 :=
  hol_boundary U T hU _ (same_component_bounds hP hQ pP pQ r sP sQ sr hr hloop)

/-- **Representative independence**: changing the paths inside `P` and `Q`
(same endpoints) does not change the class of the crossing loop. -/
theorem crossing_independent (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pP' pQ pQ' : Chain V) (sP : SupportedIn P pP) (sP' : SupportedIn P pP')
    (sQ : SupportedIn Q pQ) (sQ' : SupportedIn Q pQ')
    (hbP : bd pP' = bd pP) (hbQ : bd pQ' = bd pQ) :
    (pP + pQ) - (pP' + pQ') ∈ boundaries T := by
  have h1 : pP - pP' ∈ boundaries T := hP _ (sP.sub sP') (by rw [map_sub, hbP, sub_self])
  have h2 : pQ - pQ' ∈ boundaries T := hQ _ (sQ.sub sQ') (by rw [map_sub, hbQ, sub_self])
  have := (boundaries T).add_mem h1 h2
  rwa [show pP - pP' + (pQ - pQ') = (pP + pQ) - (pP' + pQ') by abel] at this

/-- **The Mayer–Vietoris connecting step**: a cycle split as `cP + cQ` with
`∂cP = n·∂pP` is homologous to `n` times the crossing loop. -/
theorem crossing_generates (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ cP cQ : Chain V) (n : ℤ)
    (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ)
    (scP : SupportedIn P cP) (scQ : SupportedIn Q cQ)
    (hloop : bd pQ = -bd pP) (hcyc : bd (cP + cQ) = 0) (hn : bd cP = n • bd pP) :
    (cP + cQ) - n • (pP + pQ) ∈ boundaries T := by
  have hcQ : bd cQ = -(n • bd pP) := by
    rw [map_add, hn] at hcyc; exact eq_neg_of_add_eq_zero_right hcyc
  have h1 : cP - n • pP ∈ boundaries T :=
    hP _ (scP.sub (sP.zsmul n)) (by rw [map_sub, map_zsmul, hn, sub_self])
  have h2 : cQ - n • pQ ∈ boundaries T :=
    hQ _ (scQ.sub (sQ.zsmul n)) (by rw [map_sub, map_zsmul, hcQ, hloop, smul_neg, sub_self])
  have := (boundaries T).add_mem h1 h2
  rwa [show cP - n • pP + (cQ - n • pQ) = (cP + cQ) - n • (pP + pQ) by
    rw [smul_add]; abel] at this

/-- **Generator ⇒ ±1.**  If `z` has infinite order modulo boundaries, `z` is
homologous to `n·γ`, and `γ` is homologous to `k·z`, then `γ ≡ z` or
`γ ≡ −z`. -/
theorem crossing_is_pm_generator (z γ : Chain V) (n k : ℤ)
    (hz : ∀ m : ℤ, m • z ∈ boundaries T → m = 0)
    (hzn : z - n • γ ∈ boundaries T) (hγk : γ - k • z ∈ boundaries T) :
    (γ - z ∈ boundaries T) ∨ (γ + z ∈ boundaries T) := by
  have hm : (1 - n * k) • z ∈ boundaries T := by
    have := (boundaries T).add_mem hzn ((boundaries T).zsmul_mem hγk n)
    rwa [show z - n • γ + n • (γ - k • z) = (1 - n * k) • z by
      rw [smul_sub, smul_smul, sub_smul, one_smul]; abel] at this
  have hnk : n * k = 1 := by have := hz _ hm; linarith
  rcases Int.eq_one_or_neg_one_of_mul_eq_one' hnk with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · left; simpa [one_smul] using hγk
  · right
    have : γ - (-1 : ℤ) • z = γ + z := by rw [neg_smul, one_smul, sub_neg_eq_add]
    rwa [this] at hγk

/-- Holonomy of the crossing loop is `± hol z`. -/
theorem hol_crossing_pm {K : Type*} [AddCommGroup K] (U : V → V → K) (hU : FlatOn U T)
    (z γ : Chain V) (n k : ℤ)
    (hz : ∀ m : ℤ, m • z ∈ boundaries T → m = 0)
    (hzn : z - n • γ ∈ boundaries T) (hγk : γ - k • z ∈ boundaries T) :
    hol U γ = hol U z ∨ hol U γ = -hol U z := by
  rcases crossing_is_pm_generator z γ n k hz hzn hγk with h | h
  · left; exact hol_homologous U T hU γ z h
  · right
    have := hol_boundary U T hU _ h
    rw [map_add] at this
    exact eq_neg_of_add_eq_zero_left this

/-! ### The cover hypothesis made explicit -/

/-- Every edge of `c` lies wholly in `P` or wholly in `Q`: the two shadows
cover the complex (on the support of `c`), not just its vertices.  An edge
straddling the shadows is in neither, and without this hypothesis the split
below, hence `crossing_generates`, is unavailable. -/
def EdgeCover (P Q : Set V) (c : Chain V) : Prop :=
  ∀ e ∈ c.support, (e.1 ∈ P ∧ e.2 ∈ P) ∨ (e.1 ∈ Q ∧ e.2 ∈ Q)

open Classical in
/-- Under the edge cover, a chain splits as a `P`-part plus a `Q`-part. -/
theorem split_of_edgeCover (c : Chain V) (hc : EdgeCover P Q c) :
    SupportedIn P (c.filter fun e => e.1 ∈ P ∧ e.2 ∈ P) ∧
    SupportedIn Q (c.filter fun e => ¬ (e.1 ∈ P ∧ e.2 ∈ P)) ∧
    (c.filter fun e => e.1 ∈ P ∧ e.2 ∈ P) + (c.filter fun e => ¬ (e.1 ∈ P ∧ e.2 ∈ P)) = c := by
  refine ⟨?_, ?_, Finsupp.filter_pos_add_filter_neg _ _⟩
  · intro e he
    rw [Finsupp.support_filter, Finset.mem_filter] at he
    exact he.2
  · intro e he
    rw [Finsupp.support_filter, Finset.mem_filter] at he
    exact (hc e he.1).resolve_left he.2

open Classical in
/-- **Combined statement.**  Hypotheses: the shadows cover the generator's
edges (`EdgeCover`), cycles in each shadow bound (`CyclesBound`), the
generator `z` of infinite order has `P`-part with boundary `n·∂pP`
(reduction within components, assumed), and the crossing loop is a multiple
of `z`.  Conclusion: a flat cochain has holonomy `± hol z` on the crossing
loop. -/
theorem hol_crossing_pm_of_cover {K : Type*} [AddCommGroup K] (U : V → V → K)
    (hU : FlatOn U T) (hP : CyclesBound T P) (hQ : CyclesBound T Q)
    (pP pQ z : Chain V) (n k : ℤ)
    (sP : SupportedIn P pP) (sQ : SupportedIn Q pQ) (hloop : bd pQ = -bd pP)
    (hcov : EdgeCover P Q z) (hcyc : bd z = 0)
    (hred : bd (z.filter fun e => e.1 ∈ P ∧ e.2 ∈ P) = n • bd pP)
    (hz : ∀ m : ℤ, m • z ∈ boundaries T → m = 0)
    (hγk : (pP + pQ) - k • z ∈ boundaries T) :
    hol U (pP + pQ) = hol U z ∨ hol U (pP + pQ) = -hol U z := by
  obtain ⟨scP, scQ, hsplit⟩ := split_of_edgeCover z hcov
  have hzn := crossing_generates hP hQ pP pQ _ _ n sP sQ scP scQ hloop
    (by rw [hsplit]; exact hcyc) hred
  rw [hsplit] at hzn
  exact hol_crossing_pm U hU z (pP + pQ) n k hz hzn hγk

end UnifiedTheory.Audit.KFCausalMayerVietoris
