/-
  Audit/KFCausalSheetGaugeNoGo.lean
  — THE SHEET-SECTOR GAUGE NO-GO (Schur commutant of the monodromy)

  The order sector's committed structure carries the full-S3 monodromy on the
  three-sheet zero-sum carrier — the standard 2-dimensional irreducible
  representation of S3, generated by the two loop holonomies (01) and (12)
  (`exists_global_cspec_fullS3`, `KFCausalSheetConnectionLaplacian`).  A
  continuous gauge group acting on this sector must COMMUTE with the
  monodromy transport.  In the carrier basis e₁ = (1,−1,0), e₂ = (0,1,−1)
  the two holonomy generators act as

      S₁ = [[−1, 1], [0, 1]]   (the (01)-swap),
      S₂ = [[ 1, 0], [1,−1]]   (the (12)-swap),

  and this file proves their commutant is TRIVIAL: any real 2×2 matrix
  commuting with both is a scalar.  (Schur's lemma for this concrete irrep,
  by direct linear algebra.)

  VERDICT: the sheet sector admits at most a one-parameter continuous
  symmetry (an overall scalar/U(1) phase); NO SU(2) doublet structure — and
  hence no derivation of sin²θ_W — can live on the S3 sheet sector as
  committed.  The α(0) = ln(5/3)/70 falsification gate ("derive the adjoint
  representations or the RG claim is falsified") is NOT rescued from this
  sector: the hope is closed, negatively and formally.

  Zero sorry.  Zero custom axioms.
-/
import Mathlib

set_option autoImplicit false

namespace UnifiedTheory.Audit.KFCausalSheetGaugeNoGo

/-- The (01)-holonomy on the zero-sum carrier, basis e₁=(1,−1,0), e₂=(0,1,−1):
`e₁ ↦ −e₁`, `e₂ ↦ e₁ + e₂`. -/
def S1 : Matrix (Fin 2) (Fin 2) ℝ := !![(-1 : ℝ), 1; 0, 1]

/-- The (12)-holonomy on the zero-sum carrier: `e₁ ↦ e₁ + e₂`, `e₂ ↦ −e₂`. -/
def S2 : Matrix (Fin 2) (Fin 2) ℝ := !![(1 : ℝ), 0; 1, -1]

/-- Sanity: the holonomies are involutions (transpositions square to 1). -/
theorem S1_sq : S1 * S1 = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [S1, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply]

theorem S2_sq : S2 * S2 = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [S2, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply]

/-- Sanity: the composite has order three — the generators do produce S3
(a 2-dimensional representation with an order-3 element and order-2
elements is the standard irrep). -/
theorem S1_mul_S2_cube : (S1 * S2) * ((S1 * S2) * (S1 * S2)) = 1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [S1, S2, Matrix.mul_apply, Fin.sum_univ_two, Matrix.one_apply]

/-- **THE GAUGE NO-GO** (Schur commutant).  Any real matrix commuting with
both sheet holonomies is a scalar: the continuous symmetry available on the
sheet sector is at most one-dimensional.  No SU(2) can act there; the
sin²θ_W-from-S3 route is formally closed. -/
theorem sheet_commutant_trivial (M : Matrix (Fin 2) (Fin 2) ℝ)
    (h1 : M * S1 = S1 * M) (h2 : M * S2 = S2 * M) :
    M = M 0 0 • (1 : Matrix (Fin 2) (Fin 2) ℝ) := by
  have h1' := h1
  have h2' := h2
  rw [Matrix.eta_fin_two M] at h1' h2'
  unfold S1 at h1'
  unfold S2 at h2'
  rw [Matrix.mul_fin_two, Matrix.mul_fin_two] at h1'
  rw [Matrix.mul_fin_two, Matrix.mul_fin_two] at h2'
  simp only [← Matrix.ext_iff, Fin.forall_fin_two, Matrix.cons_val',
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
    Matrix.head_fin_const, Matrix.empty_val', Matrix.cons_val_fin_one,
    Matrix.of_apply] at h1' h2'
  obtain ⟨⟨p1, p2⟩, p3, p4⟩ := h1'
  obtain ⟨⟨r1, r2⟩, r3, r4⟩ := h2'
  have hc : M 1 0 = 0 := by linarith [p1, p2, p3, p4]
  have hb : M 0 1 = 0 := by linarith [r1, r2, r3, r4]
  have hd : M 1 1 = M 0 0 := by linarith [p1, p2, p3, p4, hb, hc]
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [Matrix.smul_apply, Matrix.one_apply, hb, hc, hd]

#print axioms S1_sq
#print axioms S2_sq
#print axioms S1_mul_S2_cube
#print axioms sheet_commutant_trivial

end UnifiedTheory.Audit.KFCausalSheetGaugeNoGo
