/-
  Audit/KFCubicMarkedSheetRankTwo.lean

  MARKED CUBIC SHEETS GENERATE A CANONICAL RANK-TWO RECORD CARRIER

  A generic cubic has three locally distinguishable roots.  Treating one root
  as marked gives a three-component sheet amplitude.  Forgetting the mark
  retains the uniform direction `(1,1,1)`; the discarded sheet distinctions
  form the canonical zero-sum plane

      { z : Fin 3 -> C | z 0 + z 1 + z 2 = 0 }.

  This file formalizes the finite algebra required by the scalar chirality
  factorization no-go:

  * averaging plus centering is an exact invariant/standard decomposition;
  * the zero-sum carrier is explicitly equivalent to two complex coordinates;
  * every permutation of the three sheets preserves the carrier and its Gram
    form, so sheet relabeling transports it isometrically;
  * arbitrary history amplitudes valued in this carrier generate a Hermitian,
    strongly positive decoherence kernel;
  * an exact two-history witness has two nonzero decoherent cells and nonzero
    determinant, hence cannot be generated by one scalar amplitude.

  This constructs the canonical higher-rank carrier.  It does not assert that
  causal-set births already supply a cubic, a marked root, or a resultant-one
  gauge slice; that microscopic bridge remains open.

  Zero sorry. Zero custom axioms.
-/

import UnifiedTheory.Audit.KFCausalSetChiralityFactorizationNoGo

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFCubicMarkedSheetRankTwo

noncomputable section

open scoped BigOperators ComplexConjugate ComplexOrder
open Matrix
open UnifiedTheory.Audit.KFOrientationGrowthDecoherence
open UnifiedTheory.Audit.KFOrientationHigherRankDecoherence

universe u

/-! ## 1. Forgetting a marked sheet and retaining its defect -/

/-- Three complex amplitudes attached to the three locally marked roots of a
cubic. -/
abbrev MarkedSheetState := Fin 3 → ℂ

/-- Sum of the three sheet amplitudes. -/
def markedSheetSum (state : MarkedSheetState) : ℂ :=
  ∑ sheet, state sheet

/-- The invariant amplitude retained after forgetting which root was marked. -/
def markedSheetAverage (state : MarkedSheetState) : ℂ :=
  markedSheetSum state / 3

/-- Uniform three-sheet state. -/
def uniformMarkedSheetState (amplitude : ℂ) : MarkedSheetState :=
  fun _sheet => amplitude

/-- Projection onto the sheet-distinguishing zero-sum carrier. -/
def centeredMarkedSheetState (state : MarkedSheetState) : MarkedSheetState :=
  fun sheet => state sheet - markedSheetAverage state

/-- Predicate defining the standard two-dimensional sheet carrier. -/
def IsStandardMarkedSheetState (state : MarkedSheetState) : Prop :=
  markedSheetSum state = 0

theorem markedSheetSum_uniform (amplitude : ℂ) :
    markedSheetSum (uniformMarkedSheetState amplitude) = 3 * amplitude := by
  simp [markedSheetSum, uniformMarkedSheetState]

theorem markedSheetAverage_uniform (amplitude : ℂ) :
    markedSheetAverage (uniformMarkedSheetState amplitude) = amplitude := by
  rw [markedSheetAverage, markedSheetSum_uniform]
  ring

/-- Centering always lands in the zero-sum sheet plane. -/
theorem centeredMarkedSheetState_sum_zero (state : MarkedSheetState) :
    IsStandardMarkedSheetState (centeredMarkedSheetState state) := by
  simp only [IsStandardMarkedSheetState, markedSheetSum,
    centeredMarkedSheetState, Fin.sum_univ_three]
  unfold markedSheetAverage markedSheetSum
  simp only [Fin.sum_univ_three]
  ring

/-- Exact decomposition into forgotten scalar data and retained sheet defect. -/
theorem markedSheet_invariant_standard_decomposition
    (state : MarkedSheetState) :
    state = uniformMarkedSheetState (markedSheetAverage state) +
      centeredMarkedSheetState state := by
  funext sheet
  simp [uniformMarkedSheetState, centeredMarkedSheetState]

theorem centeredMarkedSheetState_uniform (amplitude : ℂ) :
    centeredMarkedSheetState (uniformMarkedSheetState amplitude) = 0 := by
  funext sheet
  simp [centeredMarkedSheetState, markedSheetAverage_uniform,
    uniformMarkedSheetState]

/-- Centering is a genuine projection. -/
theorem centeredMarkedSheetState_idempotent (state : MarkedSheetState) :
    centeredMarkedSheetState (centeredMarkedSheetState state) =
      centeredMarkedSheetState state := by
  have hZero := centeredMarkedSheetState_sum_zero state
  funext sheet
  simp only [centeredMarkedSheetState]
  have hAverage : markedSheetAverage (centeredMarkedSheetState state) = 0 := by
    unfold markedSheetAverage
    rw [hZero]
    norm_num
  rw [hAverage]
  simp

/-- The centering kernel consists exactly of uniform states. -/
theorem centeredMarkedSheetState_eq_zero_iff (state : MarkedSheetState) :
    centeredMarkedSheetState state = 0 ↔
      state = uniformMarkedSheetState (markedSheetAverage state) := by
  constructor
  · intro hZero
    calc
      state = uniformMarkedSheetState (markedSheetAverage state) +
          centeredMarkedSheetState state :=
        markedSheet_invariant_standard_decomposition state
      _ = uniformMarkedSheetState (markedSheetAverage state) := by
        rw [hZero]
        simp
  · intro hUniform
    rw [hUniform, centeredMarkedSheetState_uniform]

/-! ## 2. The standard sheet carrier has exactly two coordinates -/

/-- Two unconstrained coordinates for a zero-sum three-sheet state. -/
abbrev StandardSheetCoordinates := Fin 2 → ℂ

def standardSheetFromCoordinates
    (coordinates : StandardSheetCoordinates) : MarkedSheetState :=
  ![coordinates 0, coordinates 1, -coordinates 0 - coordinates 1]

def standardSheetToCoordinates
    (state : MarkedSheetState) : StandardSheetCoordinates :=
  ![state 0, state 1]

theorem standardSheetFromCoordinates_sum_zero
    (coordinates : StandardSheetCoordinates) :
    IsStandardMarkedSheetState (standardSheetFromCoordinates coordinates) := by
  norm_num [IsStandardMarkedSheetState, markedSheetSum,
    standardSheetFromCoordinates, Fin.sum_univ_three, Fin.ext_iff,
    Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two]

theorem standardSheetToFromCoordinates
    (coordinates : StandardSheetCoordinates) :
    standardSheetToCoordinates (standardSheetFromCoordinates coordinates) =
      coordinates := by
  funext i
  fin_cases i <;>
    simp [standardSheetToCoordinates, standardSheetFromCoordinates]

theorem standardSheetFromToCoordinates
    {state : MarkedSheetState} (hStandard : IsStandardMarkedSheetState state) :
    standardSheetFromCoordinates (standardSheetToCoordinates state) = state := by
  have hSum : state 0 + state 1 + state 2 = 0 := by
    simpa [IsStandardMarkedSheetState, markedSheetSum,
      Fin.sum_univ_three] using hStandard
  funext i
  fin_cases i
  · simp [standardSheetFromCoordinates, standardSheetToCoordinates]
  · simp [standardSheetFromCoordinates, standardSheetToCoordinates]
  · simp [standardSheetFromCoordinates, standardSheetToCoordinates,
      Matrix.cons_val_two]
    linear_combination -hSum

/-- Explicit equivalence between two complex coordinates and the zero-sum
three-sheet carrier. -/
def standardSheetCoordinateEquiv :
    StandardSheetCoordinates ≃
      { state : MarkedSheetState // IsStandardMarkedSheetState state } where
  toFun coordinates :=
    ⟨standardSheetFromCoordinates coordinates,
      standardSheetFromCoordinates_sum_zero coordinates⟩
  invFun state := standardSheetToCoordinates state.1
  left_inv := standardSheetToFromCoordinates
  right_inv state := Subtype.ext
    (standardSheetFromToCoordinates state.2)

/-! ## 3. Sheet permutations transport the standard carrier isometrically -/

/-- Relabel marked roots by a permutation. -/
def relabelMarkedSheetState
    (relabeling : Equiv.Perm (Fin 3))
    (state : MarkedSheetState) : MarkedSheetState :=
  fun sheet => state (relabeling.symm sheet)

theorem markedSheetSum_relabel
    (relabeling : Equiv.Perm (Fin 3)) (state : MarkedSheetState) :
    markedSheetSum (relabelMarkedSheetState relabeling state) =
      markedSheetSum state := by
  unfold markedSheetSum relabelMarkedSheetState
  exact Equiv.sum_comp relabeling.symm state

theorem markedSheetAverage_relabel
    (relabeling : Equiv.Perm (Fin 3)) (state : MarkedSheetState) :
    markedSheetAverage (relabelMarkedSheetState relabeling state) =
      markedSheetAverage state := by
  unfold markedSheetAverage
  rw [markedSheetSum_relabel]

theorem centeredMarkedSheetState_relabel
    (relabeling : Equiv.Perm (Fin 3)) (state : MarkedSheetState) :
    centeredMarkedSheetState (relabelMarkedSheetState relabeling state) =
      relabelMarkedSheetState relabeling (centeredMarkedSheetState state) := by
  funext sheet
  simp [centeredMarkedSheetState, relabelMarkedSheetState,
    markedSheetAverage_relabel]

theorem standardMarkedSheetState_relabel
    (relabeling : Equiv.Perm (Fin 3)) {state : MarkedSheetState}
    (hStandard : IsStandardMarkedSheetState state) :
    IsStandardMarkedSheetState (relabelMarkedSheetState relabeling state) := by
  unfold IsStandardMarkedSheetState at *
  rw [markedSheetSum_relabel, hStandard]

/-- Hermitian Gram pairing on sheet amplitudes. -/
def markedSheetInner (first second : MarkedSheetState) : ℂ :=
  ∑ sheet, first sheet * star (second sheet)

theorem markedSheetInner_relabel
    (relabeling : Equiv.Perm (Fin 3))
    (first second : MarkedSheetState) :
    markedSheetInner (relabelMarkedSheetState relabeling first)
        (relabelMarkedSheetState relabeling second) =
      markedSheetInner first second := by
  unfold markedSheetInner relabelMarkedSheetState
  exact Equiv.sum_comp relabeling.symm
    (fun sheet => first sheet * star (second sheet))

/-! ## 4. The canonical higher-rank history kernel -/

/-- Discard the invariant scalar component and form the Gram kernel of the
remaining marked-sheet distinctions. -/
def markedSheetStandardKernel {History : Type u}
    (amplitude : History → MarkedSheetState) :
    GrowthDecoherenceFunctional History :=
  fun first second =>
    markedSheetInner
      (centeredMarkedSheetState (amplitude first))
      (centeredMarkedSheetState (amplitude second))

theorem markedSheetStandardKernel_hermitian {History : Type u}
    (amplitude : History → MarkedSheetState) :
    IsHermitianGrowthFunctional (markedSheetStandardKernel amplitude) := by
  intro first second
  unfold markedSheetStandardKernel markedSheetInner
  rw [star_sum]
  apply Finset.sum_congr rfl
  intro sheet _hSheet
  simp
  ring

/-- Any history amplitude valued in the standard sheet carrier generates a
strongly positive decoherence functional. -/
theorem markedSheetStandardKernel_stronglyPositive {History : Type u}
    (amplitude : History → MarkedSheetState) :
    IsStronglyPositiveGrowthFunctional
      (markedSheetStandardKernel amplitude) := by
  intro n sample
  let column : Matrix (Fin n) (Fin 3) ℂ := fun i sheet =>
    centeredMarkedSheetState (amplitude (sample i)) sheet
  have hPositive : (column * column.conjTranspose).PosSemidef :=
    Matrix.posSemidef_self_mul_conjTranspose column
  have hKernel :
      (fun i j => markedSheetStandardKernel amplitude
        (sample i) (sample j)) = column * column.conjTranspose := by
    ext i j
    simp [markedSheetStandardKernel, markedSheetInner, column,
      Matrix.mul_apply, Matrix.conjTranspose_apply]
  rw [hKernel]
  exact hPositive

theorem markedSheetStandardKernel_relabel
    {History : Type u} (amplitude : History → MarkedSheetState)
    (relabeling : Equiv.Perm (Fin 3)) :
    markedSheetStandardKernel
        (fun history => relabelMarkedSheetState relabeling (amplitude history)) =
      markedSheetStandardKernel amplitude := by
  funext first second
  unfold markedSheetStandardKernel
  rw [centeredMarkedSheetState_relabel,
    centeredMarkedSheetState_relabel,
    markedSheetInner_relabel]

/-! ## 5. Exact nontrivial record witness -/

/-- Two orthogonal zero-sum sheet profiles. -/
def markedSheetBinaryWitnessAmplitude (history : Fin 2) : MarkedSheetState :=
  if history = 0 then ![(1 : ℂ), -1, 0]
  else ![(1 : ℂ), 1, -2]

theorem markedSheetBinaryWitnessAmplitude_standard (history : Fin 2) :
    IsStandardMarkedSheetState (markedSheetBinaryWitnessAmplitude history) := by
  fin_cases history <;>
    norm_num [markedSheetBinaryWitnessAmplitude,
      IsStandardMarkedSheetState, markedSheetSum,
      Fin.sum_univ_three, Fin.ext_iff,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two]

theorem centered_markedSheetBinaryWitnessAmplitude (history : Fin 2) :
    centeredMarkedSheetState (markedSheetBinaryWitnessAmplitude history) =
      markedSheetBinaryWitnessAmplitude history := by
  have hStandard := markedSheetBinaryWitnessAmplitude_standard history
  funext sheet
  simp only [centeredMarkedSheetState]
  have hAverage : markedSheetAverage
      (markedSheetBinaryWitnessAmplitude history) = 0 := by
    unfold markedSheetAverage
    rw [hStandard]
    norm_num
  rw [hAverage]
  simp

abbrev MarkedSheetBinaryWitnessMatrix := Matrix (Fin 2) (Fin 2) ℂ

def markedSheetBinaryWitnessKernel : MarkedSheetBinaryWitnessMatrix :=
  fun first second => markedSheetStandardKernel
    markedSheetBinaryWitnessAmplitude first second

theorem markedSheetBinaryWitnessKernel_exact :
    markedSheetBinaryWitnessKernel =
      !![(2 : ℂ), 0; 0, 6] := by
  ext first second
  simp only [markedSheetBinaryWitnessKernel, markedSheetStandardKernel]
  rw [show centeredMarkedSheetState (markedSheetBinaryWitnessAmplitude first) =
      markedSheetBinaryWitnessAmplitude first from
    centered_markedSheetBinaryWitnessAmplitude first]
  rw [show centeredMarkedSheetState (markedSheetBinaryWitnessAmplitude second) =
      markedSheetBinaryWitnessAmplitude second from
    centered_markedSheetBinaryWitnessAmplitude second]
  fin_cases first <;> fin_cases second <;>
    norm_num [markedSheetInner,
      markedSheetBinaryWitnessAmplitude,
      Fin.sum_univ_three, Fin.ext_iff,
      Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.cons_val_two,
      star_ofNat]
  rw [map_ofNat]
  norm_num

theorem markedSheetBinaryWitnessKernel_det :
    Matrix.det markedSheetBinaryWitnessKernel = 12 := by
  rw [markedSheetBinaryWitnessKernel_exact, Matrix.det_fin_two]
  norm_num

/-- The sheet carrier evades the scalar no-go: it has two nonzero exactly
decoherent cells and cannot be represented by one scalar history amplitude. -/
theorem markedSheetBinaryWitness_nontrivial_and_not_scalar :
    markedSheetBinaryWitnessKernel 0 0 ≠ 0
      ∧ markedSheetBinaryWitnessKernel 1 1 ≠ 0
      ∧ markedSheetBinaryWitnessKernel 0 1 = 0
      ∧ markedSheetBinaryWitnessKernel 1 0 = 0
      ∧ ¬ IsScalarAmplitudeKernel markedSheetBinaryWitnessKernel := by
  have hExact := markedSheetBinaryWitnessKernel_exact
  constructor
  · rw [hExact]
    norm_num
  constructor
  · rw [hExact]
    norm_num
  constructor
  · rw [hExact]
    norm_num
  constructor
  · rw [hExact]
    norm_num
  · intro hScalar
    have hZero := scalarAmplitudeKernel_det_zero hScalar
    rw [markedSheetBinaryWitnessKernel_det] at hZero
    norm_num at hZero

theorem markedSheetBinaryWitness_stronglyPositive :
    IsStronglyPositiveGrowthFunctional markedSheetBinaryWitnessKernel :=
  markedSheetStandardKernel_stronglyPositive
    markedSheetBinaryWitnessAmplitude

/-! ## 6. Capstone -/

/-- The marked-root construction supplies exactly the algebraic object left
open by the scalar factorization no-go: a canonical two-coordinate carrier,
isometric sheet transport, and a nontrivial strongly positive record kernel.
The assignment of such sheet data to causal births is intentionally not
asserted here. -/
theorem markedCubicSheets_supply_rankTwo_recordCarrier :
    Nonempty (StandardSheetCoordinates ≃
      { state : MarkedSheetState // IsStandardMarkedSheetState state })
      ∧ (∀ (relabeling : Equiv.Perm (Fin 3))
          (first second : MarkedSheetState),
        markedSheetInner (relabelMarkedSheetState relabeling first)
            (relabelMarkedSheetState relabeling second) =
          markedSheetInner first second)
      ∧ IsStronglyPositiveGrowthFunctional markedSheetBinaryWitnessKernel
      ∧ markedSheetBinaryWitnessKernel 0 0 ≠ 0
      ∧ markedSheetBinaryWitnessKernel 1 1 ≠ 0
      ∧ markedSheetBinaryWitnessKernel 0 1 = 0
      ∧ markedSheetBinaryWitnessKernel 1 0 = 0
      ∧ ¬ IsScalarAmplitudeKernel markedSheetBinaryWitnessKernel := by
  exact ⟨⟨standardSheetCoordinateEquiv⟩,
    markedSheetInner_relabel,
    markedSheetBinaryWitness_stronglyPositive,
    markedSheetBinaryWitness_nontrivial_and_not_scalar.1,
    markedSheetBinaryWitness_nontrivial_and_not_scalar.2.1,
    markedSheetBinaryWitness_nontrivial_and_not_scalar.2.2.1,
    markedSheetBinaryWitness_nontrivial_and_not_scalar.2.2.2.1,
    markedSheetBinaryWitness_nontrivial_and_not_scalar.2.2.2.2⟩

#print axioms centeredMarkedSheetState_sum_zero
#print axioms markedSheet_invariant_standard_decomposition
#print axioms centeredMarkedSheetState_eq_zero_iff
#print axioms standardSheetCoordinateEquiv
#print axioms markedSheetInner_relabel
#print axioms markedSheetStandardKernel_stronglyPositive
#print axioms markedSheetStandardKernel_relabel
#print axioms markedSheetBinaryWitnessKernel_exact
#print axioms markedSheetBinaryWitness_nontrivial_and_not_scalar
#print axioms markedCubicSheets_supply_rankTwo_recordCarrier

end

end UnifiedTheory.Audit.KFCubicMarkedSheetRankTwo
