/-
  Audit/KFOrientationSpinOneEvolution.lean

  EXACT RODRIGUES HEISENBERG EVOLUTION

  The cubic closure L^3 = -rho^2 L exponentiates algebraically on the linear
  spin-one observable sector.  The resulting finite Rodrigues formula has an
  exact one-parameter group law, fixes the Hamiltonian direction, and rotates
  every transverse observable in the plane generated by X and L X.

  No infinite matrix series or approximation is used.  This remains a finite
  conditional spin-one model; it does not select a physical causal-set
  Hamiltonian or establish continuum quantum-gravity dynamics.
-/

import UnifiedTheory.Audit.KFOrientationSpinOneHeisenberg

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFOrientationSpinOneEvolution

noncomputable section

open scoped BigOperators Polynomial ComplexConjugate
open Matrix
open UnifiedTheory.Audit.KFOrientationQuantumConsequences
open UnifiedTheory.Audit.KFOrientationQuantumProjectors
open UnifiedTheory.Audit.KFOrientationSpinOne
open UnifiedTheory.Audit.KFOrientationSpinOneRelational
open UnifiedTheory.Audit.KFOrientationSpinOneHeisenberg

/-! ## 1. The finite Rodrigues polynomial -/

def heisenbergSinCoefficient (rho t : ℝ) : ℝ :=
  Real.sin (rho * t) / rho

def heisenbergCosCoefficient (rho t : ℝ) : ℝ :=
  (1 - Real.cos (rho * t)) / rho ^ 2

def heisenbergRodrigues
    (H : SpinOneMatrix) (rho t : ℝ) (X : SpinOneMatrix) : SpinOneMatrix :=
  X +
    (heisenbergSinCoefficient rho t : ℂ) • heisenbergGenerator H X +
    (heisenbergCosCoefficient rho t : ℂ) •
      heisenbergGenerator H (heisenbergGenerator H X)

theorem heisenbergRodrigues_zero
    (H : SpinOneMatrix) (rho : ℝ) (X : SpinOneMatrix) :
    heisenbergRodrigues H rho 0 X = X := by
  simp [heisenbergRodrigues, heisenbergSinCoefficient,
    heisenbergCosCoefficient]

theorem heisenbergRodrigues_add
    (H : SpinOneMatrix) (rho t : ℝ) (X Y : SpinOneMatrix) :
    heisenbergRodrigues H rho t (X + Y) =
      heisenbergRodrigues H rho t X + heisenbergRodrigues H rho t Y := by
  simp only [heisenbergRodrigues, heisenbergGenerator_add_right, smul_add]
  module

theorem heisenbergRodrigues_smul
    (H : SpinOneMatrix) (rho t : ℝ) (z : ℂ) (X : SpinOneMatrix) :
    heisenbergRodrigues H rho t (z • X) =
      z • heisenbergRodrigues H rho t X := by
  simp only [heisenbergRodrigues, heisenbergGenerator_smul_right,
    smul_add, smul_smul]
  module

/-! ## 2. Generator action and exact group law -/

theorem heisenbergRodrigues_generator_of_cubic
    (H : SpinOneMatrix) (rho t : ℝ) (X : SpinOneMatrix)
    (hrho : rho ≠ 0)
    (hcubic :
      heisenbergGenerator H
          (heisenbergGenerator H (heisenbergGenerator H X)) =
        (-(rho ^ 2) : ℂ) • heisenbergGenerator H X) :
    heisenbergGenerator H (heisenbergRodrigues H rho t X) =
      (Real.cos (rho * t) : ℂ) • heisenbergGenerator H X +
        (heisenbergSinCoefficient rho t : ℂ) •
          heisenbergGenerator H (heisenbergGenerator H X) := by
  unfold heisenbergRodrigues
  rw [heisenbergGenerator_add_right, heisenbergGenerator_add_right,
    heisenbergGenerator_smul_right, heisenbergGenerator_smul_right, hcubic]
  have hcoeff :
      (1 : ℂ) -
          (heisenbergCosCoefficient rho t : ℂ) * (rho ^ 2 : ℂ) =
        (Real.cos (rho * t) : ℂ) := by
    have hcoeffR :
        1 - heisenbergCosCoefficient rho t * rho ^ 2 =
          Real.cos (rho * t) := by
      unfold heisenbergCosCoefficient
      field_simp [hrho]
      ring
    exact_mod_cast hcoeffR
  rw [smul_smul]
  rw [← hcoeff]
  module

theorem heisenbergRodrigues_generator_sq_of_cubic
    (H : SpinOneMatrix) (rho t : ℝ) (X : SpinOneMatrix)
    (hrho : rho ≠ 0)
    (hcubic :
      heisenbergGenerator H
          (heisenbergGenerator H (heisenbergGenerator H X)) =
        (-(rho ^ 2) : ℂ) • heisenbergGenerator H X) :
    heisenbergGenerator H
        (heisenbergGenerator H (heisenbergRodrigues H rho t X)) =
      (-(rho ^ 2) * heisenbergSinCoefficient rho t : ℂ) •
          heisenbergGenerator H X +
        (Real.cos (rho * t) : ℂ) •
          heisenbergGenerator H (heisenbergGenerator H X) := by
  rw [heisenbergRodrigues_generator_of_cubic H rho t X hrho hcubic,
    heisenbergGenerator_add_right, heisenbergGenerator_smul_right,
    heisenbergGenerator_smul_right, hcubic, smul_smul]
  module

theorem heisenbergRodrigues_add_time_of_cubic
    (H : SpinOneMatrix) (rho t u : ℝ) (X : SpinOneMatrix)
    (hrho : rho ≠ 0)
    (hcubic :
      heisenbergGenerator H
          (heisenbergGenerator H (heisenbergGenerator H X)) =
        (-(rho ^ 2) : ℂ) • heisenbergGenerator H X) :
    heisenbergRodrigues H rho (t + u) X =
      heisenbergRodrigues H rho t (heisenbergRodrigues H rho u X) := by
  have hsin :
      heisenbergSinCoefficient rho (t + u) =
        heisenbergSinCoefficient rho u +
          heisenbergSinCoefficient rho t * Real.cos (rho * u) -
            heisenbergCosCoefficient rho t *
              heisenbergSinCoefficient rho u * rho ^ 2 := by
    unfold heisenbergSinCoefficient heisenbergCosCoefficient
    rw [mul_add, Real.sin_add]
    field_simp [hrho]
    ring
  have hcos :
      heisenbergCosCoefficient rho (t + u) =
        heisenbergCosCoefficient rho u +
          heisenbergSinCoefficient rho t *
            heisenbergSinCoefficient rho u +
          heisenbergCosCoefficient rho t * Real.cos (rho * u) := by
    unfold heisenbergSinCoefficient heisenbergCosCoefficient
    rw [mul_add, Real.cos_add]
    field_simp [hrho]
    ring
  symm
  calc
    heisenbergRodrigues H rho t (heisenbergRodrigues H rho u X) =
        heisenbergRodrigues H rho u X +
          (heisenbergSinCoefficient rho t : ℂ) •
            heisenbergGenerator H (heisenbergRodrigues H rho u X) +
          (heisenbergCosCoefficient rho t : ℂ) •
            heisenbergGenerator H
              (heisenbergGenerator H (heisenbergRodrigues H rho u X)) := rfl
    _ = heisenbergRodrigues H rho u X +
          (heisenbergSinCoefficient rho t : ℂ) •
            ((Real.cos (rho * u) : ℂ) • heisenbergGenerator H X +
              (heisenbergSinCoefficient rho u : ℂ) •
                heisenbergGenerator H (heisenbergGenerator H X)) +
          (heisenbergCosCoefficient rho t : ℂ) •
            ((-(rho ^ 2) * heisenbergSinCoefficient rho u : ℂ) •
                heisenbergGenerator H X +
              (Real.cos (rho * u) : ℂ) •
                heisenbergGenerator H (heisenbergGenerator H X)) := by
      rw [heisenbergRodrigues_generator_sq_of_cubic H rho u X hrho hcubic,
        heisenbergRodrigues_generator_of_cubic H rho u X hrho hcubic]
    _ = heisenbergRodrigues H rho (t + u) X := by
      simp only [heisenbergRodrigues]
      rw [hsin, hcos]
      push_cast
      module

/-! ## 3. Orientation-sector dynamics -/

def orientationHeisenbergEvolution
    (p q r : ℕ) (t : ℝ) (X : SpinOneMatrix) : SpinOneMatrix :=
  heisenbergRodrigues
    (orientationHamiltonian p q r) (orientationRadius p q r) t X

theorem orientationHeisenbergEvolution_zero
    (p q r : ℕ) (X : SpinOneMatrix) :
    orientationHeisenbergEvolution p q r 0 X = X := by
  exact heisenbergRodrigues_zero _ _ _

theorem orientationHeisenbergEvolution_add
    (p q r : ℕ) (t : ℝ) (X Y : SpinOneMatrix) :
    orientationHeisenbergEvolution p q r t (X + Y) =
      orientationHeisenbergEvolution p q r t X +
        orientationHeisenbergEvolution p q r t Y := by
  exact heisenbergRodrigues_add _ _ _ _ _

theorem orientationHeisenbergEvolution_smul
    (p q r : ℕ) (t : ℝ) (z : ℂ) (X : SpinOneMatrix) :
    orientationHeisenbergEvolution p q r t (z • X) =
      z • orientationHeisenbergEvolution p q r t X := by
  exact heisenbergRodrigues_smul _ _ _ _ _

theorem orientationHeisenbergEvolution_add_time
    (p q r : ℕ) (hp : 0 < p) (hq : 0 < q) (hr : 0 < r)
    (t u x1 x2 x3 : ℝ) :
    orientationHeisenbergEvolution p q r (t + u)
        (spinOneFieldHamiltonian x1 x2 x3) =
      orientationHeisenbergEvolution p q r t
        (orientationHeisenbergEvolution p q r u
          (spinOneFieldHamiltonian x1 x2 x3)) := by
  apply heisenbergRodrigues_add_time_of_cubic
  · exact ne_of_gt (orientationRadius_pos p q r hp hq hr)
  · exact orientation_heisenbergGenerator_cubic p q r x1 x2 x3

theorem orientationHeisenbergEvolution_hamiltonian
    (p q r : ℕ) (t : ℝ) :
    orientationHeisenbergEvolution p q r t
        (orientationHamiltonian p q r) =
      orientationHamiltonian p q r := by
  unfold orientationHeisenbergEvolution heisenbergRodrigues
  simp [heisenbergGenerator, complexMatrixCommutator]

theorem orientationHeisenbergEvolution_transverse
    (p q r : ℕ) (hp : 0 < p) (hq : 0 < q) (hr : 0 < r)
    (t x1 x2 x3 : ℝ)
    (htrans : fieldDot
      (effectiveField1 p q r)
      (effectiveField2 p q r)
      (effectiveField3 p q r) x1 x2 x3 = 0) :
    orientationHeisenbergEvolution p q r t
        (spinOneFieldHamiltonian x1 x2 x3) =
      (Real.cos (orientationRadius p q r * t) : ℂ) •
          spinOneFieldHamiltonian x1 x2 x3 +
        (heisenbergSinCoefficient (orientationRadius p q r) t : ℂ) •
          heisenbergGenerator (orientationHamiltonian p q r)
            (spinOneFieldHamiltonian x1 x2 x3) := by
  have hrho : orientationRadius p q r ≠ 0 :=
    ne_of_gt (orientationRadius_pos p q r hp hq hr)
  unfold orientationHeisenbergEvolution heisenbergRodrigues
  rw [orientation_heisenbergGenerator_sq_of_transverse p q r _ _ _ htrans,
    smul_smul]
  have hcoeff :
      (1 : ℂ) -
          (heisenbergCosCoefficient (orientationRadius p q r) t : ℂ) *
            (orientationRadius p q r ^ 2 : ℂ) =
        (Real.cos (orientationRadius p q r * t) : ℂ) := by
    have hcoeffR :
        1 - heisenbergCosCoefficient (orientationRadius p q r) t *
              orientationRadius p q r ^ 2 =
          Real.cos (orientationRadius p q r * t) := by
      unfold heisenbergCosCoefficient
      field_simp [hrho]
      ring
    exact_mod_cast hcoeffR
  rw [← hcoeff]
  module

theorem orientationHeisenbergEvolution_inverse
    (p q r : ℕ) (hp : 0 < p) (hq : 0 < q) (hr : 0 < r)
    (t x1 x2 x3 : ℝ) :
    orientationHeisenbergEvolution p q r (-t)
        (orientationHeisenbergEvolution p q r t
          (spinOneFieldHamiltonian x1 x2 x3)) =
      spinOneFieldHamiltonian x1 x2 x3 := by
  rw [← orientationHeisenbergEvolution_add_time p q r hp hq hr]
  norm_num
  exact orientationHeisenbergEvolution_zero p q r _

/-! ## 4. Preserved trace geometry -/

theorem trace_heisenbergGenerator_mul
    (H X Y : SpinOneMatrix) :
    Matrix.trace (heisenbergGenerator H X * Y) =
      -Matrix.trace (X * heisenbergGenerator H Y) := by
  unfold heisenbergGenerator complexMatrixCommutator
  simp only [smul_mul_assoc, mul_smul_comm, Matrix.trace_smul,
    Matrix.sub_mul, Matrix.mul_sub, Matrix.trace_sub]
  have hcyclic :
      Matrix.trace ((H * X) * Y) = Matrix.trace ((X * Y) * H) := by
    rw [Matrix.mul_assoc]
    exact Matrix.trace_mul_comm H (X * Y)
  rw [hcyclic]
  simp only [Matrix.mul_assoc]
  module

theorem trace_heisenbergGenerator_sq_mul
    (H X Y : SpinOneMatrix) :
    Matrix.trace
        (heisenbergGenerator H (heisenbergGenerator H X) * Y) =
      Matrix.trace
        (X * heisenbergGenerator H (heisenbergGenerator H Y)) := by
  rw [trace_heisenbergGenerator_mul,
    trace_heisenbergGenerator_mul]
  ring

theorem heisenbergSinCoefficient_neg (rho t : ℝ) :
    heisenbergSinCoefficient rho (-t) =
      -heisenbergSinCoefficient rho t := by
  simp [heisenbergSinCoefficient]
  ring

theorem heisenbergCosCoefficient_neg (rho t : ℝ) :
    heisenbergCosCoefficient rho (-t) =
      heisenbergCosCoefficient rho t := by
  simp [heisenbergCosCoefficient]

/-- The finite Rodrigues action is adjoint to reverse-time evolution for the
trace pairing.  This identity does not require the cubic closure. -/
theorem heisenbergRodrigues_trace_adjoint
    (H : SpinOneMatrix) (rho t : ℝ) (X Y : SpinOneMatrix) :
    Matrix.trace (heisenbergRodrigues H rho t X * Y) =
      Matrix.trace (X * heisenbergRodrigues H rho (-t) Y) := by
  simp only [heisenbergRodrigues, Matrix.add_mul, Matrix.mul_add,
    smul_mul_assoc, mul_smul_comm, Matrix.trace_add, Matrix.trace_smul]
  rw [trace_heisenbergGenerator_mul,
    trace_heisenbergGenerator_sq_mul,
    heisenbergSinCoefficient_neg, heisenbergCosCoefficient_neg]
  push_cast
  module

/-- Simultaneous exact Heisenberg evolution preserves every pairwise trace
overlap in the linear spin-one sector. -/
theorem orientationHeisenbergEvolution_trace_product
    (p q r : ℕ) (hp : 0 < p) (hq : 0 < q) (hr : 0 < r)
    (t x1 x2 x3 y1 y2 y3 : ℝ) :
    Matrix.trace
        (orientationHeisenbergEvolution p q r t
            (spinOneFieldHamiltonian x1 x2 x3) *
          orientationHeisenbergEvolution p q r t
            (spinOneFieldHamiltonian y1 y2 y3)) =
      Matrix.trace
        (spinOneFieldHamiltonian x1 x2 x3 *
          spinOneFieldHamiltonian y1 y2 y3) := by
  change Matrix.trace
      (heisenbergRodrigues
          (orientationHamiltonian p q r) (orientationRadius p q r) t
          (spinOneFieldHamiltonian x1 x2 x3) *
        heisenbergRodrigues
          (orientationHamiltonian p q r) (orientationRadius p q r) t
          (spinOneFieldHamiltonian y1 y2 y3)) = _
  rw [heisenbergRodrigues_trace_adjoint]
  change Matrix.trace
      (spinOneFieldHamiltonian x1 x2 x3 *
        orientationHeisenbergEvolution p q r (-t)
          (orientationHeisenbergEvolution p q r t
            (spinOneFieldHamiltonian y1 y2 y3))) = _
  have hgroup := orientationHeisenbergEvolution_add_time p q r hp hq hr
    (-t) t y1 y2 y3
  norm_num [orientationHeisenbergEvolution_zero] at hgroup
  rw [← hgroup]

/-- In particular, exact Heisenberg evolution preserves the complete pairwise
Gram data of any finite family of linear spin-one observables. -/
theorem orientationHeisenbergEvolution_pairOverlap
    (p q r : ℕ) (hp : 0 < p) (hq : 0 < q) (hr : 0 < r)
    (t x1 x2 x3 y1 y2 y3 : ℝ) :
    Matrix.trace
        (orientationHeisenbergEvolution p q r t
            (spinOneFieldHamiltonian x1 x2 x3) *
          orientationHeisenbergEvolution p q r t
            (spinOneFieldHamiltonian y1 y2 y3)) =
      ((2 * fieldDot x1 x2 x3 y1 y2 y3 : ℝ) : ℂ) := by
  rw [orientationHeisenbergEvolution_trace_product p q r hp hq hr,
    spinOneField_trace_product]

#print axioms heisenbergRodrigues_generator_of_cubic
#print axioms heisenbergRodrigues_add_time_of_cubic
#print axioms orientationHeisenbergEvolution_add_time
#print axioms orientationHeisenbergEvolution_hamiltonian
#print axioms orientationHeisenbergEvolution_transverse
#print axioms orientationHeisenbergEvolution_inverse
#print axioms trace_heisenbergGenerator_mul
#print axioms heisenbergRodrigues_trace_adjoint
#print axioms orientationHeisenbergEvolution_trace_product
#print axioms orientationHeisenbergEvolution_pairOverlap

end

end UnifiedTheory.Audit.KFOrientationSpinOneEvolution
