/-
  Audit/KFOrientationSpinOne.lean

  EXACT SPIN-ONE REPRESENTATION OF THE FINITE ORIENTATION SECTOR

  Three normalized Hermitian generators satisfy the su(2) commutation relations
  and have quadratic Casimir 2I, so the finite three-level orientation sector is
  an exact spin-one matrix representation.  The orientation Hamiltonian is the
  dot product of these generators with an effective field whose squared norm is
  the previously derived spectral radius.

  Outer-fiber reflection flips exactly one effective-field component and preserves
  its norm.  Uniform profiles lie in a fixed field plane.  The conditional
  propagator generated by H is exactly recurrent with period 2*pi/rho.

  These statements identify a finite representation and its matrix dynamics.
  They do not identify a physical particle spin, a graviton, a spacetime rotation
  group, or a quantum-gravity Hamiltonian.
-/

import UnifiedTheory.Audit.KFOrientationQuantumProjectors

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFOrientationSpinOne

noncomputable section

open scoped BigOperators Polynomial ComplexConjugate
open Matrix
open UnifiedTheory.Audit.KFOrientationRankTwoFiberLaw
open UnifiedTheory.Audit.KFOrientationRankTwoConsequences
open UnifiedTheory.Audit.KFOrientationQuantumConsequences
open UnifiedTheory.Audit.KFOrientationQuantumZeroMode
open UnifiedTheory.Audit.KFOrientationQuantumProjectors

abbrev SpinOneMatrix := Matrix (Fin 3) (Fin 3) ℂ

/-! ## 1. Normalized Hermitian spin-one generators -/

def spinOneSqrtTwo : ℝ := Real.sqrt 2

theorem spinOneSqrtTwo_pos : 0 < spinOneSqrtTwo := by
  unfold spinOneSqrtTwo
  positivity

theorem spinOneSqrtTwo_ne_zero : spinOneSqrtTwo ≠ 0 :=
  ne_of_gt spinOneSqrtTwo_pos

theorem spinOneSqrtTwo_sq : spinOneSqrtTwo ^ 2 = 2 := by
  unfold spinOneSqrtTwo
  rw [Real.sq_sqrt]
  norm_num

theorem spinOneSqrtTwo_sq_complex : (spinOneSqrtTwo : ℂ) ^ 2 = 2 := by
  exact_mod_cast spinOneSqrtTwo_sq

def spinOneJ1 : SpinOneMatrix :=
  skewHamiltonian (1 / spinOneSqrtTwo) 0 (1 / spinOneSqrtTwo)

def spinOneJ2 : SpinOneMatrix :=
  skewHamiltonian 0 1 0

def spinOneJ3 : SpinOneMatrix :=
  skewHamiltonian (1 / spinOneSqrtTwo) 0 (-1 / spinOneSqrtTwo)

def complexMatrixCommutator (A B : SpinOneMatrix) : SpinOneMatrix :=
  A * B - B * A

theorem spinOneJ1_isHermitian : spinOneJ1.IsHermitian :=
  skewHamiltonian_isHermitian _ _ _

theorem spinOneJ2_isHermitian : spinOneJ2.IsHermitian :=
  skewHamiltonian_isHermitian _ _ _

theorem spinOneJ3_isHermitian : spinOneJ3.IsHermitian :=
  skewHamiltonian_isHermitian _ _ _

/-! ## 2. Exact su(2) commutators and Casimir -/

theorem spinOne_commutator_J1_J2 :
    complexMatrixCommutator spinOneJ1 spinOneJ2 = Complex.I • spinOneJ3 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [complexMatrixCommutator, spinOneJ1, spinOneJ2, spinOneJ3,
      skewHamiltonian, Matrix.mul_apply, Fin.sum_univ_three, Fin.ext_iff] <;>
    field_simp [spinOneSqrtTwo_ne_zero]

theorem spinOne_commutator_J2_J3 :
    complexMatrixCommutator spinOneJ2 spinOneJ3 = Complex.I • spinOneJ1 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [complexMatrixCommutator, spinOneJ1, spinOneJ2, spinOneJ3,
      skewHamiltonian, Matrix.mul_apply, Fin.sum_univ_three, Fin.ext_iff] <;>
    field_simp [spinOneSqrtTwo_ne_zero]

theorem spinOne_commutator_J3_J1 :
    complexMatrixCommutator spinOneJ3 spinOneJ1 = Complex.I • spinOneJ2 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [complexMatrixCommutator, spinOneJ1, spinOneJ2, spinOneJ3,
      skewHamiltonian, Matrix.mul_apply, Fin.sum_univ_three, Fin.ext_iff] <;>
    field_simp [spinOneSqrtTwo_ne_zero] <;>
    simp [Complex.I_sq, spinOneSqrtTwo_sq_complex] <;> ring

theorem spinOne_casimir :
    spinOneJ1 ^ 2 + spinOneJ2 ^ 2 + spinOneJ3 ^ 2 =
      (2 : ℂ) • (1 : SpinOneMatrix) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [spinOneJ1, spinOneJ2, spinOneJ3, skewHamiltonian,
      pow_two, Matrix.mul_apply, Fin.sum_univ_three, Fin.ext_iff] <;>
    field_simp [spinOneSqrtTwo_ne_zero] <;>
    norm_num [Complex.I_sq, spinOneSqrtTwo_sq_complex]

/-! ## 3. Effective-field coordinates -/

def effectiveField1 (p q r : ℕ) : ℝ :=
  spinOneSqrtTwo * (nativeCoefficient p q r : ℝ)

def effectiveField2 (p q r : ℕ) : ℝ :=
  (longCoefficient p q r : ℝ)

def effectiveField3 (p q r : ℕ) : ℝ :=
  spinOneSqrtTwo * (imbalanceCoefficient p q r : ℝ)

theorem rankTwoCouplings_channelCoordinates (p q r : ℕ) :
    (rankTwoLeftCoupling p q r : ℝ) =
        (nativeCoefficient p q r : ℝ) + (imbalanceCoefficient p q r : ℝ)
    ∧ (rankTwoLongCoupling p q r : ℝ) = (longCoefficient p q r : ℝ)
    ∧ (rankTwoRightCoupling p q r : ℝ) =
        (nativeCoefficient p q r : ℝ) - (imbalanceCoefficient p q r : ℝ) := by
  rw [rankTwoLeftCoupling_formula, rankTwoLongCoupling_formula,
    rankTwoRightCoupling_formula]
  unfold nativeCoefficient longCoefficient imbalanceCoefficient
  push_cast
  constructor
  · ring
  · constructor <;> ring

theorem skewHamiltonian_spinOne_decomposition (a b c : ℝ) :
    skewHamiltonian (a + c) b (a - c) =
      (spinOneSqrtTwo * a : ℂ) • spinOneJ1 +
        (b : ℂ) • spinOneJ2 +
          (spinOneSqrtTwo * c : ℂ) • spinOneJ3 := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [spinOneJ1, spinOneJ2, spinOneJ3, skewHamiltonian,
      Fin.ext_iff] <;>
    field_simp [spinOneSqrtTwo_ne_zero] <;> ring

theorem orientationHamiltonian_spinOne_effectiveField (p q r : ℕ) :
    orientationHamiltonian p q r =
      (effectiveField1 p q r : ℂ) • spinOneJ1 +
        (effectiveField2 p q r : ℂ) • spinOneJ2 +
          (effectiveField3 p q r : ℂ) • spinOneJ3 := by
  rcases rankTwoCouplings_channelCoordinates p q r with ⟨hL, hM, hR⟩
  unfold orientationHamiltonian effectiveField1 effectiveField2 effectiveField3
  rw [hL, hM, hR]
  simpa only [Complex.ofReal_mul] using
    skewHamiltonian_spinOne_decomposition
      (nativeCoefficient p q r : ℝ)
      (longCoefficient p q r : ℝ)
      (imbalanceCoefficient p q r : ℝ)

theorem effectiveField_norm_sq (p q r : ℕ) :
    effectiveField1 p q r ^ 2 +
        effectiveField2 p q r ^ 2 +
          effectiveField3 p q r ^ 2 =
      orientationRadiusSq p q r := by
  rcases rankTwoCouplings_channelCoordinates p q r with ⟨hL, hM, hR⟩
  unfold effectiveField1 effectiveField2 effectiveField3 orientationRadiusSq
  rw [hL, hM, hR]
  nlinarith [spinOneSqrtTwo_sq]

/-! ## 4. Reflection and uniform-profile geometry -/

theorem effectiveField_outer_reflection (p q r : ℕ) :
    effectiveField1 r q p = effectiveField1 p q r
    ∧ effectiveField2 r q p = effectiveField2 p q r
    ∧ effectiveField3 r q p = -effectiveField3 p q r := by
  unfold effectiveField1 effectiveField2 effectiveField3
    nativeCoefficient longCoefficient imbalanceCoefficient
  push_cast
  constructor
  · ring
  · constructor <;> ring

theorem uniformLongCoefficient_eq_profileParameter_mul_native (s : ℕ) :
    (uniformLongCoefficient s : ℝ) =
      uniformProfileParameterReal s * (uniformNativeCoefficient s : ℝ) := by
  unfold uniformLongCoefficient uniformNativeCoefficient
    uniformProfileParameterReal uniformProfileParameter
  push_cast
  have hden : (s : ℝ) + 1 ≠ 0 := by positivity
  field_simp [hden]

theorem uniform_effectiveField (s : ℕ) :
    effectiveField1 s s s =
        spinOneSqrtTwo * (uniformNativeCoefficient s : ℝ)
    ∧ effectiveField2 s s s =
        uniformProfileParameterReal s * (uniformNativeCoefficient s : ℝ)
    ∧ effectiveField3 s s s = 0 := by
  unfold effectiveField1 effectiveField2 effectiveField3
  constructor
  · congr 1
    unfold nativeCoefficient uniformNativeCoefficient
    push_cast
    ring
  · constructor
    · rw [← uniformLongCoefficient_eq_profileParameter_mul_native]
      unfold longCoefficient uniformLongCoefficient
      push_cast
      ring
    · unfold imbalanceCoefficient
      push_cast
      ring

/-! ## 5. Exact recurrence of the conditional propagator -/

theorem orientationPropagator_full_period
    (p q r : ℕ) (hp : 0 < p) (hq : 0 < q) (hr : 0 < r) (t : ℝ) :
    orientationPropagator p q r
        (t + 2 * Real.pi / orientationRadius p q r) =
      orientationPropagator p q r t := by
  rw [orientationPropagator_add p q r hp hq hr]
  have hρ := orientationRadius_pos p q r hp hq hr
  have hphase :
      orientationRadius p q r *
          (2 * Real.pi / orientationRadius p q r) = 2 * Real.pi := by
    field_simp [ne_of_gt hρ]
  have hperiod :
      orientationPropagator p q r
          (2 * Real.pi / orientationRadius p q r) = 1 := by
    unfold orientationPropagator
    rw [hphase, Real.cos_two_pi, Real.sin_two_pi]
    norm_num
    exact orientationKernelProjector_add_rangeProjector p q r
  rw [hperiod, Matrix.mul_one]

#print axioms spinOne_commutator_J1_J2
#print axioms spinOne_commutator_J2_J3
#print axioms spinOne_commutator_J3_J1
#print axioms spinOne_casimir
#print axioms orientationHamiltonian_spinOne_effectiveField
#print axioms effectiveField_norm_sq
#print axioms effectiveField_outer_reflection
#print axioms uniform_effectiveField
#print axioms orientationPropagator_full_period

end

end UnifiedTheory.Audit.KFOrientationSpinOne
