/-
  Audit/KFOrientationCountertermRigidity.lean

  ORIENTATION COUNTERTERM RIGIDITY

  The orientation channel is not an arbitrary skew matrix: together with K_F
  it reconstructs the forward and backward directed zeta determinants exactly.
  This file proves that any additive counterterm preserving both reconstruction
  identities is zero.  Consequently the nonzero long-range term generated by
  diamond blocking cannot be absorbed into the native orientation channel
  without changing that channel's defining observable meaning.
-/

import UnifiedTheory.Audit.KFOrientationPathObstruction

set_option autoImplicit false
set_option relaxedAutoImplicit false

namespace UnifiedTheory.Audit.KFOrientationCountertermRigidity

open UnifiedTheory.LayerB.NoBackgroundSpace
open UnifiedTheory.LayerB.KFFinitePoset
open UnifiedTheory.Audit.OrderSensitiveObservables
open UnifiedTheory.Audit.KFSpectralCoarseGraining
open UnifiedTheory.Audit.KFHigherRank
open UnifiedTheory.Audit.KFMultirankCoarseGraining
open UnifiedTheory.Audit.KFOrientationDefect
open UnifiedTheory.Audit.KFOrientationPathObstruction

/-! ## 1. Reconstruction-preserving counterterms -/

/-- An additive change to the orientation channel is semantically admissible
when the corrected channel still reconstructs both directed zeta determinants
with the unchanged symmetric K_F operator. -/
def PreservesDirectedDeterminantReconstruction
    (P : FinPoset) (r : ℕ)
    (counterterm : Matrix (Chamber P r) (Chamber P r) ℚ) : Prop :=
  ∀ A B,
    (zetaBlock P A B).det =
      (kFAtRank P r A B + (if A = B then 1 else 0) +
        (kFOrientationAtRank P r A B + counterterm A B)) / 2
    ∧ (zetaBlock P B A).det =
      (kFAtRank P r A B + (if A = B then 1 else 0) -
        (kFOrientationAtRank P r A B + counterterm A B)) / 2

theorem zero_preservesDirectedDeterminantReconstruction
    (P : FinPoset) (r : ℕ) :
    PreservesDirectedDeterminantReconstruction P r 0 := by
  intro A B
  constructor
  · simpa using forwardDet_from_symmetric_and_orientation P r A B
  · simpa using backwardDet_from_symmetric_and_orientation P r A B

/-- Exact directed reconstruction fixes the orientation channel uniquely. -/
theorem preservesDirectedDeterminantReconstruction_iff_eq_zero
    (P : FinPoset) (r : ℕ)
    (counterterm : Matrix (Chamber P r) (Chamber P r) ℚ) :
    PreservesDirectedDeterminantReconstruction P r counterterm ↔
      counterterm = 0 := by
  constructor
  · intro h
    ext A B
    have hNative := forwardDet_from_symmetric_and_orientation P r A B
    have hCorrected := (h A B).1
    change counterterm A B = 0
    linarith
  · intro h
    subst counterterm
    exact zero_preservesDirectedDeterminantReconstruction P r

theorem reconstruction_preserving_counterterm_rigid
    (P : FinPoset) (r : ℕ)
    (counterterm : Matrix (Chamber P r) (Chamber P r) ℚ)
    (h : PreservesDirectedDeterminantReconstruction P r counterterm) :
    counterterm = 0 :=
  (preservesDirectedDeterminantReconstruction_iff_eq_zero
    P r counterterm).1 h

/-! ## 2. Event-carrier specialization -/

/-- The event carrier is canonically equivalent to the rank-one chamber
carrier. -/
def singletonChamberEquiv (P : FinPoset) :
    Fin P.n ≃ Chamber P 1 where
  toFun := singletonChamber P
  invFun := fun A => A.1 0
  left_inv := by
    intro i
    rfl
  right_inv := by
    intro A
    apply Subtype.ext
    funext k
    fin_cases k
    rfl

def rankOneCountertermOnChambers (P : FinPoset)
    (counterterm : Matrix (Fin P.n) (Fin P.n) ℚ) :
    Matrix (Chamber P 1) (Chamber P 1) ℚ :=
  Matrix.reindex (singletonChamberEquiv P) (singletonChamberEquiv P)
    counterterm

def PreservesRankOneDirectedReconstruction (P : FinPoset)
    (counterterm : Matrix (Fin P.n) (Fin P.n) ℚ) : Prop :=
  PreservesDirectedDeterminantReconstruction P 1
    (rankOneCountertermOnChambers P counterterm)

theorem preservesRankOneDirectedReconstruction_iff_eq_zero
    (P : FinPoset) (counterterm : Matrix (Fin P.n) (Fin P.n) ℚ) :
    PreservesRankOneDirectedReconstruction P counterterm ↔
      counterterm = 0 := by
  rw [PreservesRankOneDirectedReconstruction,
    preservesDirectedDeterminantReconstruction_iff_eq_zero]
  constructor
  · intro h
    apply (Matrix.reindex (singletonChamberEquiv P)
      (singletonChamberEquiv P)).injective
    simpa [rankOneCountertermOnChambers] using h
  · intro h
    subst counterterm
    rfl

/-! ## 3. The generated diamond operator is not an admissible counterterm -/

/-- Chamber-carrier form of the unit long-range residual generated by diamond
blocking. -/
noncomputable def generatedLongRangeOrientationOnChambers :
    Matrix (Chamber chainThree 2) (Chamber chainThree 2) ℚ :=
  Matrix.reindex rankTwoChamberThreeEquiv rankTwoChamberThreeEquiv
    ((1 / 2 : ℚ) • generatedLongRangeOrientation)

theorem generatedLongRangeOrientationOnChambers_nonzero :
    generatedLongRangeOrientationOnChambers ≠ 0 := by
  intro h
  have hSource : (1 / 2 : ℚ) • generatedLongRangeOrientation = 0 := by
    apply (Matrix.reindex rankTwoChamberThreeEquiv
      rankTwoChamberThreeEquiv).injective
    simpa [generatedLongRangeOrientationOnChambers] using h
  apply diamond_orientationDefect_nonzero
  exact diamond_orientationDefect_exact.trans hSource

theorem generatedLongRange_not_reconstruction_preserving :
    ¬ PreservesDirectedDeterminantReconstruction chainThree 2
      generatedLongRangeOrientationOnChambers := by
  intro h
  apply generatedLongRangeOrientationOnChambers_nonzero
  exact reconstruction_preserving_counterterm_rigid chainThree 2 _ h

/-- The generated residual must be retained as a new effective operator if
the native orientation channel is required to keep reconstructing the same
directed determinants. -/
theorem generated_orientation_requires_independent_operator :
    generatedLongRangeOrientationOnChambers ≠ 0
    ∧ ¬ PreservesDirectedDeterminantReconstruction chainThree 2
      generatedLongRangeOrientationOnChambers :=
  ⟨generatedLongRangeOrientationOnChambers_nonzero,
    generatedLongRange_not_reconstruction_preserving⟩

/-! ## 4. Fixed-UV path consequences -/

theorem chainFourPath13Defect_nonzero : chainFourPath13Defect ≠ 0 := by
  rw [chainFourPath13_defect_exact]
  intro h
  have h01 := congrFun (congrFun h 0) 1
  norm_num [chainTwoOrientationRankOne] at h01

theorem chainFourPath22Defect_nonzero : chainFourPath22Defect ≠ 0 := by
  rw [chainFourPath22_defect_exact]
  intro h
  have h01 := congrFun (congrFun h 0) 1
  norm_num [chainTwoOrientationRankOne] at h01

theorem chainFourPath13_no_reconstruction_preserving_ir_counterterm :
    ¬ ∃ counterterm : Matrix (Fin 2) (Fin 2) ℚ,
      PreservesRankOneDirectedReconstruction chainTwo counterterm
      ∧ infraredCorrectedDefect chainFourPath13 1
        (orientationRankOne chainFour) (orientationRankOne chainTwo)
        counterterm = 0 := by
  rintro ⟨counterterm, hSemantic, hClosed⟩
  have hZero :=
    (preservesRankOneDirectedReconstruction_iff_eq_zero
      chainTwo counterterm).1 hSemantic
  rw [infraredCorrectedDefect_eq, hZero, sub_zero] at hClosed
  exact chainFourPath13Defect_nonzero hClosed

theorem chainFourPath22_no_reconstruction_preserving_ir_counterterm :
    ¬ ∃ counterterm : Matrix (Fin 2) (Fin 2) ℚ,
      PreservesRankOneDirectedReconstruction chainTwo counterterm
      ∧ infraredCorrectedDefect chainFourPath22 1
        (orientationRankOne chainFour) (orientationRankOne chainTwo)
        counterterm = 0 := by
  rintro ⟨counterterm, hSemantic, hClosed⟩
  have hZero :=
    (preservesRankOneDirectedReconstruction_iff_eq_zero
      chainTwo counterterm).1 hSemantic
  rw [infraredCorrectedDefect_eq, hZero, sub_zero] at hClosed
  exact chainFourPath22Defect_nonzero hClosed

/-! ## Trust regression -/

#print axioms preservesDirectedDeterminantReconstruction_iff_eq_zero
#print axioms preservesRankOneDirectedReconstruction_iff_eq_zero
#print axioms generatedLongRangeOrientationOnChambers_nonzero
#print axioms generatedLongRange_not_reconstruction_preserving
#print axioms generated_orientation_requires_independent_operator
#print axioms chainFourPath13_no_reconstruction_preserving_ir_counterterm

end UnifiedTheory.Audit.KFOrientationCountertermRigidity
